force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <formula>IF( NOT(ISBLANK(First_Name__c)) , First_Name__c, &apos;&apos;) + &apos; &apos; + IF( NOT(ISBLANK(Middle_Name__c)) , Middle_Name__c, &apos;&apos;) + &apos; &apos; + IF( NOT(ISBLANK(Last_Name__c)) , Last_Name__c, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Co-Applicant</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/BL_SendRejectionEmailToCustomer.cls
public class BL_SendRejectionEmailToCustomer {
    
    @InvocableMethod(label='Send Rejection email')
    public static void BL_SendRejectionEmail(list<String> loanId){
        system.debug('inside invocable method');
        EmailTemplate template = [SELECT Id, DeveloperName, Subject, HtmlValue, Body 
                                  FROM EmailTemplate 
                                  WHERE DeveloperName =: BL_ConstantsUtil.REJECTION_LETTER
                                  LIMIT 1];
        system.debug('template>> ' + template);
        system.debug('LAF_ID>> ' + loanId);
        if(!loanId.isEmpty() && template.Id != null){
            Loan_Application__c lafrecord = [Select Id,(SELECT Id,Email__c, Name,Applicant_Name__c,Applicant_Type__c 
                                                        FROM Loan_Applicants__r WHERE Applicant_Type__c = 'Applicant' ) 
                                             FROM Loan_Application__c WHERE Id =:loanId[0]];
            system.debug('lafrecord>> ' + lafrecord);
            if(lafrecord != null){
                if(lafrecord.Loan_Applicants__r[0].Email__c != null){
                    
                    Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
                    message.setTargetObjectId(UserInfo.getUserId());
                    OrgWideEmailAddress owea = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = :UB_ConstantsUtil.NO_REPLY_EMAIL_DISPLAY_NAME LIMIT 1];
                    if (owea != null) {
                        message.setOrgWideEmailAddressId(owea.Id);
                    } else {
                        System.debug('No noreply email address not found.');
                    }
                    System.debug('No noreply email address found.>>' + owea);
                    message.setSaveAsActivity(false); 
                    message.setTreatTargetObjectAsRecipient(false);
                    message.setTemplateID(template.Id); 
                    system.debug('lafrecord.Id-> ' + lafrecord.Id);
                    message.setWhatId(lafrecord.Id);
                    message.toAddresses = new String[] {lafrecord.Loan_Applicants__r[0].Email__c};
                        System.debug('message.toAddresses.>>' + message.toAddresses);
                    system.debug('message>> ' + message);
                    Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
                        try{
                            system.debug('success fully send email');
                            Messaging.sendEmail(messages); // email send
                        }catch(Exception e){
                            system.debug('error > ' + e);
                        }
                }
            }
        }
    }
}