force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BL_SendApplicationCancellationEmail.cls
public class BL_SendApplicationCancellationEmail {
    
    @InvocableMethod(label='Send Cancellation Email')
    public static void sendCancellationEmail(List<LoanApplicationRequest> requestList) {
        System.debug('invoked : '+requestList);
        Loan_Application__c loanApp = [SELECT Id, (SELECT Email__c FROM Loan_Applicants__r) 
                                       FROM Loan_Application__c WHERE Id = :requestList[0].loanApplicationId LIMIT 1];
        
        List<Loan_Applicant__c> applicants = loanApp.Loan_Applicants__r;
        
        if (applicants.isEmpty()) {
            System.debug('Exit');
            return;
        }
        System.debug('called');
        sendEmail(applicants[0].Email__c, requestList[0].emailTemplateName, loanApp.Id);
    }
    
    private static void sendEmail(String recipientEmail, String templateName, Id loanAppId) {
        System.debug('sendEmail');
        EmailTemplate template = [SELECT Id FROM EmailTemplate WHERE DeveloperName = :templateName LIMIT 1];
        
        if (template != null) {
            if(recipientEmail != null){
                Messaging.SingleEmailMessage message = Messaging.renderStoredEmailTemplate(template.Id, null, loanAppId);
                message.setTargetObjectId(UserInfo.getUserId());
                OrgWideEmailAddress owea = [SELECT Id FROM OrgWideEmailAddress WHERE DisplayName = :UB_ConstantsUtil.NO_REPLY_EMAIL_DISPLAY_NAME LIMIT 1];
                if (owea != null) {
                    message.setOrgWideEmailAddressId(owea.Id);
                } else {
                    System.debug('No noreply email address not found.');
                }
                System.debug('No noreply email address found.>>' + owea);
                message.setSaveAsActivity(false); 
                message.setTreatTargetObjectAsRecipient(false);
                message.toAddresses = new String[] {recipientEmail};
                    System.debug('message.toAddresses.>>' + message.toAddresses);
                Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage> {message};
                    try{
                        system.debug('success fully send email');
                        Messaging.sendEmail(messages); // email send
                    }catch(Exception e){
                        system.debug('error > ' + e);
                    }
            }
        }
    }
    
    public class LoanApplicationRequest {
        @InvocableVariable(required=true)
        public Id loanApplicationId;
        
        @InvocableVariable(required=true)
        public String emailTemplateName;
    }
}