force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Is_Report_available__c.field-meta.xml
<CustomField>
    <fullName>Is_Report_available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Report available ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Perfios_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Perfios_Transaction_Id__c</fullName>
    <label>Perfios Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Processing_Files_Done__c.field-meta.xml
<CustomField>
    <fullName>Processing_Files_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processing Files Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UB_Perfios_Scheduler.cls
/**
* @File Name          : UB_Perfios_Generate_Report_Integration
* @Description        : Class to schedule the status and retrieve the report
* @Author             : Chandan Kumar
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0                           Initial Version
*/
public class UB_Perfios_Scheduler implements Schedulable {
    public void execute(SchedulableContext sc) {
        
        List<Verification__c> verificationLstForReport = [SELECT Id,Loan_Applicant__c,Perfios_Transaction_Id__c FROM Verification__c where Perfios_Transaction_Id__c != null AND Is_Report_available__c = false AND Processing_Files_Done__c = true];
        if(verificationLstForReport.size()>0){
              for(Verification__c verify : verificationLstForReport){
            UB_Perfios_Status queueableInstance = new UB_Perfios_Status(verify.Perfios_Transaction_Id__c,verify.Loan_Applicant__c);
            System.enqueueJob(queueableInstance);
        }
        }
    }
}