force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Identification_Number__c</fullName>
    <label>Identification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/KYC_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>KYC_Document_Type__c</fullName>
    <label>KYC Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>Voter Identity Card</fullName>
            </value>
            <value>
                <fullName>MNREGA Job Card</fullName>
            </value>
            <value>
                <fullName>National Population Register (NPR)</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/KYC_Document_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>KYC_Document_Type_Name__c</fullName>
    <label>KYC Document Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Occupation_Type__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Type__c</fullName>
    <label>Occupation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private Sector</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Unorganized Sector</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Agriculturist</fullName>
            </value>
            <value>
                <fullName>Housewife</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Not Categorized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Type_Of_Profession__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Profession__c</fullName>
    <label>Type Of Profession</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>CA/CS</fullName>
            </value>
            <value>
                <fullName>Lawyer</fullName>
            </value>
            <value>
                <fullName>Architect</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/Reference_Member__c.object-meta.xml
<CustomObject>
    <label>Reference/Member</label>
    <nameField>
        <displayFormat>RM-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reference/Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reference_Member__c/fields/Date_of_birth__c.field-meta.xml
<CustomField>
    <fullName>Date_of_birth__c</fullName>
    <label>Date of birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Designation__c.field-meta.xml
<CustomField>
    <fullName>Designation__c</fullName>
    <label>Designation</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Identification_Number__c.field-meta.xml
<CustomField>
    <fullName>Identification_Number__c</fullName>
    <label>Identification Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/KYC_Document_Type__c.field-meta.xml
<CustomField>
    <fullName>KYC_Document_Type__c</fullName>
    <label>KYC Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>Voter Identity Card</fullName>
            </value>
            <value>
                <fullName>MNREGA Job Card</fullName>
            </value>
            <value>
                <fullName>National Population Register (NPR)</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/KYC_Document_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>KYC_Document_Type_Name__c</fullName>
    <label>KYC Document Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Reference/Members</relationshipLabel>
    <relationshipName>Reference_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Loan_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant_Name__c</fullName>
    <formula>Loan_Applicant__r.Applicant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Reference/Members</relationshipLabel>
    <relationshipName>Reference_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Loan_Application_Name__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Name__c</fullName>
    <formula>Loan_Application__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Loan Application Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Member_Name__c.field-meta.xml
<CustomField>
    <fullName>Member_Name__c</fullName>
    <formula>IF( NOT(ISBLANK(First_Name__c)) , First_Name__c, &apos;&apos;) + &apos; &apos; + IF( NOT(ISBLANK(Middle_Name__c)) , Middle_Name__c, &apos;&apos;) + &apos; &apos; + IF( NOT(ISBLANK(Last_Name__c)) , Last_Name__c, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Member Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <label>Middle Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Indian</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Occupation_Type__c.field-meta.xml
<CustomField>
    <fullName>Occupation_Type__c</fullName>
    <label>Occupation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Private Sector</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Unorganized Sector</fullName>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
            <value>
                <fullName>Self Employed</fullName>
            </value>
            <value>
                <fullName>Retired</fullName>
            </value>
            <value>
                <fullName>Agriculturist</fullName>
            </value>
            <value>
                <fullName>Housewife</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Not Categorized</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pincode</label>
    <referenceTo>Pincode__c</referenceTo>
    <relationshipLabel>Reference/Members</relationshipLabel>
    <relationshipName>Reference_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Pincode_Name__c.field-meta.xml
<CustomField>
    <fullName>Pincode_Name__c</fullName>
    <formula>Pincode__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Pincode Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Reference_Address__c.field-meta.xml
<CustomField>
    <fullName>Reference_Address__c</fullName>
    <label>Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Reference_Member__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Authorised Signatory</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Directo</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>HUF Member</fullName>
            </value>
            <value>
                <fullName>Trade References</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UB_Reference_MemberSelector.cls
/**
* @File Name          : UB_Reference_MemberSelector.cls
* @Description        : This class used to fetch/query Reference records based on conditions.
* @Author             : Mansur
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         30-07-2024               Mansur                 Initial Version
*/
public class UB_Reference_MemberSelector extends fflib_SObjectSelector {
	public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
          
          Reference_Member__c.Reference_Address__c,
          Reference_Member__c.Identification_Number__c,
          Reference_Member__c.Id,
          Reference_Member__c.First_Name__c,
          Reference_Member__c.Designation__c,
          Reference_Member__c.Date_of_birth__c,
          Reference_Member__c.KYC_Document_Type__c,
          Reference_Member__c.KYC_Document_Type_Name__c,
          Reference_Member__c.Last_Name__c,
          Reference_Member__c.Loan_Application__c,
          Reference_Member__c.Loan_Applicant_Name__c,
          Reference_Member__c.Loan_Applicant__c,
          Reference_Member__c.Loan_Application_Name__c,
          Reference_Member__c.Member_Name__c,
          Reference_Member__c.Middle_Name__c,
          Reference_Member__c.Mobile__c,
          Reference_Member__c.Name,
          Reference_Member__c.Nationality__c,
          Reference_Member__c.Occupation_Type__c,
          Reference_Member__c.Pincode__c,
          Reference_Member__c.Pincode_Name__c,
          Reference_Member__c.Reference_Member__c.Type__c,
          Reference_Member__c.Type_of_Profession__c,
          Reference_Member__c.Type_of_Profession_Name__c

        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Reference_Member__c.sObjectType;
    }
   
    public List<Reference_Member__c> selectById(Set<Id> recordIds){
        return (List<Reference_Member__c>) selectSObjectsById(recordIds);
    }
    public List<Reference_Member__c > selectByLoanApplicantId(Set<Id> loanApplcantId){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Applicant__c  IN : loanApplcantId' );
           query.selectField('RecordType.Name');
            query.selectField('Loan_Applicant__r.Name');
        return (List<Reference_Member__c >) Database.query(query.toSOQL());
    }
    public List<Reference_Member__c > selectByLoanApplicationId(Set<Id> loanApplcationId,String recordTypeId){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Application__c  IN : loanApplcationId AND RecordTypeId = :recordTypeId' );
           query.selectField('RecordType.Name');
        return (List<Reference_Member__c >) Database.query(query.toSOQL());
    }
   	
}