force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Aadhaar_Verification__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aadhaar Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Aadhar Verification)</relationshipLabel>
    <relationshipName>Loan_Applicants2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Application__c.field-meta.xml
<CustomField>
    <fullName>Application__c</fullName>
    <formula>Loan_Application__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/PAN_Verification__c.field-meta.xml
<CustomField>
    <fullName>PAN_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PAN Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/IsReadOnly__c.field-meta.xml
<CustomField>
    <fullName>IsReadOnly__c</fullName>
    <formula>IF(
AND(
(ISPICKVAL(Loan_Application_Status__c, &apos;Inactive&apos;) ||
ISPICKVAL(Loan_Application_Status__c, &apos;Disbursed&apos;) ||
ISPICKVAL(Loan_Application_Status__c, &apos;Closed&apos;) ||
ISPICKVAL(Loan_Application_Status__c, &apos;Cancelled&apos;) ||
ISPICKVAL(Loan_Application_Status__c, &apos;Rejected&apos;) ||
ISPICKVAL(Loan_Application_Status__c, &apos;Approved&apos;) ||
ISPICKVAL(Loan_Application_Status__c, &apos;Revoke&apos;) ||
$User.Id != OwnerId
),
NOT($Setup.Bypass_Validations__c.Bypass_Validation__c),
NOT(
AND(
User_Role__c = &apos;Relationship Manager&apos;,
ISPICKVAL(Loan_Application_Status__c, &apos;Rejected&apos;)
) ||
User_Role__c = &apos;RCU Manager&apos; ||
User_Role__c = &apos;BL RCU Manager&apos;
)
),
true,
false
)</formula>
    <label>Is Read Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UB_DynamicRelatedListCtrl.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 06-05-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class UB_DynamicRelatedListCtrl {
    @AuraEnabled
    public static GenericDataTableController.DataTableResponse returnRelatedRecords(String applicationId, String metadataName, String query, String queryParameters){
        System.debug('applicationId=  '+applicationId);
        System.debug('queryParameters  '+queryParameters);
        GenericDataTableController genericDTObj = new GenericDataTableController();
        genericDTObj.METADATA_NAME = metadataName; 
        genericDTObj.IDS_SET = new Set<String>(); 
        //Added by Mohit on 21-06-2024 - Hide Actions if the IsReadOnly check box is true on Loan Application
        List<Loan_Application__c> loanApplicationList = new UB_LoanApplicationsSelector().selectByIds(new Set<Id>{applicationId});
        if(!loanApplicationList.isEmpty() && loanApplicationList.size() > 0){
            genericDTObj.IS_READ_ONLY = loanApplicationList[0].IsReadOnly__c ? true : false;
        }else{
            genericDTObj.IS_READ_ONLY = false;
        }
        
        if(String.isNotBlank(queryParameters)){ 
            genericDTObj.IDS_SET.addAll(queryParameters.split(';'));
        }
        genericDTObj.IDS_SET.add(applicationId);
        // genericDTObj.WHERE_CLAUSE = ' Application__c IN : IDS_SET';
        System.debug('IDS_SET is = '+genericDTObj.IDS_SET);
        System.debug('Query is = '+query);
        genericDTObj.WHERE_CLAUSE = query;
        System.debug('genericDTObj  '+genericDTObj);
        System.debug('genericDTObj.getTable()-> ' + genericDTObj.getTable());
        return genericDTObj.getTable();     
    }

    @AuraEnabled
    public static List<sObject> getFilterRecords(String sObjectName, Id recordId, String filterConditions) {
        return Database.query('Select Id From '+sObjectName+' Where Id =:recordId AND '+filterConditions);
    }

    /*@AuraEnabled
    Public static Opportunity getOppRecord(String recordId) {
        System.debug('Current User Id - '+UserInfo.getUserId());
    
        List<Opportunity> oppRecord = [Select IsReadOnly__c, StageName, RecordType.Name, Previous_Sales_Owner__c From opportunity where id = : recordId LIMIT 1];
        System.debug(recordId);
        return [SELECT Id, StageName,  RecordType.Name, Previous_Sales_Owner__c,IsReadOnly__c FROM Opportunity WHERE Id = :recordId LIMIT 1];
    }*/


    /**
    * @description  method wil return map having pan verification for all applicants.
    * @author  Zafaruddin | 04-05-2024 
    * @param loanId 
    * @return Map<Object, Boolean> 
    **/
    @AuraEnabled
    Public static Map<Object,Boolean> checkPanAndAadharVerify(String loanId) {
        Map<Object,Boolean> loanApplicantMap = new Map<Object,Boolean>();
        if(String.isNotBlank(loanId)) {
            for(Loan_Applicant__c applicantRecord : [SELECT Id, PAN_Verification__c, Aadhaar_Verification__c FROM  Loan_Applicant__c WHERE Loan_Application__c = :loanId]) {
                if(applicantRecord.PAN_Verification__c == NULL /*|| applicantRecord.Aadhaar_Verification__c == NULL */) {
                    loanApplicantMap.put(applicantRecord.Id,false);
                } else {
                    loanApplicantMap.put(applicantRecord.Id,True);
                }
            }
        }
        return loanApplicantMap;

    }

}