force-app/main/default/objects/Document_Checklist__c/Document_Checklist__c.object-meta.xml
<CustomObject>
    <label>Document Checklist</label>
    <nameField>
        <displayFormat>Doc-{00000}</displayFormat>
        <label>Doc Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklist</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist__c/fields/Applicable_For__c.field-meta.xml
<CustomField>
    <fullName>Applicable_For__c</fullName>
    <label>Applicable For</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Application</fullName>
            </value>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Co-Applicant</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
            <value>
                <fullName>Gaurantor</fullName>
                <isActive>false</isActive>
                <label>Gaurantor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Co-Applicant</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Main Director</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Main Promoter</fullName>
            </value>
            <value>
                <fullName>Promotor</fullName>
            </value>
            <value>
                <fullName>Division</fullName>
            </value>
            <value>
                <fullName>Shareholder</fullName>
            </value>
            <value>
                <fullName>Holding Company</fullName>
            </value>
            <value>
                <fullName>Subsidiary Company</fullName>
            </value>
            <value>
                <fullName>Proprietor</fullName>
            </value>
            <value>
                <fullName>Trustee</fullName>
            </value>
            <value>
                <fullName>Karta</fullName>
            </value>
            <value>
                <fullName>Co Parceners</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Constituation_of_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Constituation_of_Applicant__c</fullName>
    <label>Constituation of Applicant</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Sole Proprietorship</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Public Ltd</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>HUF</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
            <value>
                <fullName>Society</fullName>
            </value>
            <value>
                <fullName>Section 25 Company</fullName>
            </value>
            <value>
                <fullName>Govt Body/Statutory Body</fullName>
            </value>
            <value>
                <fullName>Limited Liability Partnership</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Private Ltd</fullName>
            </value>
            <value>
                <fullName>Ltd</fullName>
                <isActive>false</isActive>
                <label>Ltd</label>
            </value>
            <value>
                <fullName>Private Ltd/Ltd</fullName>
                <isActive>false</isActive>
                <label>Private Ltd/Ltd</label>
            </value>
            <value>
                <fullName>Proprietorship</fullName>
                <isActive>false</isActive>
                <label>Proprietorship</label>
            </value>
            <value>
                <fullName>Pvt Ltd</fullName>
                <isActive>false</isActive>
                <label>Pvt Ltd</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Disbursement_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Sub_Type__c</fullName>
    <label>Disbursement Sub Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Disbursement_Type__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Type__c</fullName>
    <label>Disbursement Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Document_Subtype__c.field-meta.xml
<CustomField>
    <fullName>Document_Subtype__c</fullName>
    <label>Document Sub Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Sub_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Is_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Product_Parameters__c.field-meta.xml
<CustomField>
    <fullName>Product_Parameters__c</fullName>
    <label>Product Parameters</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CV</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Retail &amp; Strategic</fullName>
            </value>
            <value>
                <fullName>FTU &amp; FTB</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consent Pending</fullName>
            </value>
            <value>
                <fullName>Document Verification</fullName>
            </value>
            <value>
                <fullName>Disbursal In Progress</fullName>
            </value>
            <value>
                <fullName>Pre-Disbursal Document Collection</fullName>
            </value>
            <value>
                <fullName>Credit Due Deliquency</fullName>
                <isActive>false</isActive>
                <label>Credit Due Deliquency</label>
            </value>
            <value>
                <fullName>Credit Due Diligence</fullName>
                <isActive>false</isActive>
                <label>Credit Due Diligence</label>
            </value>
            <value>
                <fullName>Customer Due Diligence</fullName>
                <isActive>false</isActive>
                <label>Customer Due Diligence</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
            <value>
                <fullName>Post Disbursement</fullName>
                <isActive>false</isActive>
                <label>Post Disbursement</label>
            </value>
            <value>
                <fullName>Pre Disbursement</fullName>
                <isActive>false</isActive>
                <label>Pre Disbursement</label>
            </value>
            <value>
                <fullName>Pre Login</fullName>
                <isActive>false</isActive>
                <label>Pre Login</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Document_Sub_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Photo</fullName>
    </customValue>
    <customValue>
        <fullName>Passport</fullName>
    </customValue>
    <customValue>
        <fullName>Driving License</fullName>
    </customValue>
    <customValue>
        <fullName>MNREGA Job Card</fullName>
    </customValue>
    <customValue>
        <fullName>National Population Register</fullName>
    </customValue>
    <customValue>
        <fullName>Utility or Electricity Bill</fullName>
    </customValue>
    <customValue>
        <fullName>Property or Municipal tax receipt</fullName>
    </customValue>
    <customValue>
        <fullName>Pension or family pension payment orders (PPOs)</fullName>
    </customValue>
    <customValue>
        <fullName>Letter of allotment</fullName>
    </customValue>
    <customValue>
        <fullName>Marriage Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Registry Copy</fullName>
    </customValue>
    <customValue>
        <fullName>GPA</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Municipal Charges Bill [RCU Verified Document only]</fullName>
    </customValue>
    <customValue>
        <fullName>Purchase deed sale agreement [including sale through POA]</fullName>
    </customValue>
    <customValue>
        <fullName>Residential Society Allotment Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Bank verification Proof</fullName>
    </customValue>
    <customValue>
        <fullName>RC Copy</fullName>
    </customValue>
    <customValue>
        <fullName>Insurances</fullName>
    </customValue>
    <customValue>
        <fullName>Invoices</fullName>
    </customValue>
    <customValue>
        <fullName>Permit copy of commercial Vehicles</fullName>
    </customValue>
    <customValue>
        <fullName>Contract Copy</fullName>
    </customValue>
    <customValue>
        <fullName>Title Deed</fullName>
    </customValue>
    <customValue>
        <fullName>GST Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Partnership Deed</fullName>
    </customValue>
    <customValue>
        <fullName>Commencement of Business Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>IT Return Challan</fullName>
    </customValue>
    <customValue>
        <fullName>Form 16</fullName>
    </customValue>
    <customValue>
        <fullName>ITR Showing Business Income</fullName>
    </customValue>
    <customValue>
        <fullName>Documents of Karta</fullName>
    </customValue>
    <masterLabel>Document Sub Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Document_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Collateral Details If Any</fullName>
    </customValue>
    <customValue>
        <fullName>Preliminary Credit Application Form</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Information Sheet</fullName>
    </customValue>
    <customValue>
        <fullName>Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Photo</fullName>
    </customValue>
    <customValue>
        <fullName>ID Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Address Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Stability Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Signature Verification Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Experience Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Owned House Proof</fullName>
    </customValue>
    <customValue>
        <fullName>GST Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Partnership Deed</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Incorporation [Pvt Ltd &amp; LTD]</fullName>
    </customValue>
    <customValue>
        <fullName>Registration Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>MOA, AOA, COI [Pvt. Ltd./Ltd.]</fullName>
    </customValue>
    <customValue>
        <fullName>Form 32 [Pvt. Ltd./Ltd.]</fullName>
    </customValue>
    <customValue>
        <fullName>List of Directors [Pvt Ltd &amp; LTD]</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Commencement of Business [Ltd]</fullName>
    </customValue>
    <customValue>
        <fullName>HUF Deed Of Declaration [HUF]</fullName>
    </customValue>
    <customValue>
        <fullName>Quotation with USFBL HPA</fullName>
    </customValue>
    <customValue>
        <fullName>RC of Proposed Asset in Used Case</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance of Proposed Asset in Used Case</fullName>
    </customValue>
    <customValue>
        <fullName>Loan Calculation Sheet</fullName>
    </customValue>
    <customValue>
        <fullName>IRR Sheet</fullName>
    </customValue>
    <customValue>
        <fullName>Six Month Latest Banking</fullName>
    </customValue>
    <masterLabel>Document Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_DocumentChecklistsSelector.cls
/**
* @File Name          : UB_DocumentChecklistsSelector.cls
* @Description        : This class used to fetch/query document checklist based on conditions.
* @Author             : Deepak Joshi
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         02-04-2024               Deepak Joshi                 Initial Version
*/
public class UB_DocumentChecklistsSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Document_Checklist__c.Id,
                Document_Checklist__c.Stage__c,
                Document_Checklist__c.LOB__c,
                Document_Checklist__c.Is_Active__c,
                Document_Checklist__c.Document_Type__c,
                Document_Checklist__c.Is_Required__c,
                Document_Checklist__c.Document_Subtype__c,
                Document_Checklist__c.Constituation_of_Applicant__c,
                Document_Checklist__c.Applicant_Type__c,
                Document_Checklist__c.Applicable_For__C,
                Document_Checklist__c.Product_Parameters__c,
                Document_Checklist__c.Disbursement_Type__c,
                Document_Checklist__c.Disbursement_Sub_Type__c 
        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Document_Checklist__c.sObjectType;
    }
   
    public List<Document_Checklist__c> selectById(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN : recordIds');
        return (List<Document_Checklist__c>) Database.query(query.toSOQL());
    }
    public List<Document_Checklist__c> selectByStage(String stage){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('stage__c =: stage');
        return (List<Document_Checklist__c>) Database.query(query.toSOQL());
    }
    
    public List<Document_Checklist__c> selectByCondition(String condition){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition(condition);
        return (List<Document_Checklist__c>) Database.query(query.toSOQL());
    }
}