force-app/main/default/objects/Exception_Logger__c/Exception_Logger__c.object-meta.xml
<CustomObject>
    <label>Exception Logger</label>
    <nameField>
        <displayFormat>EL-{000000000}</displayFormat>
        <label>Exception Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Logger__c/fields/Exception_Cause__c.field-meta.xml
<CustomField>
    <fullName>Exception_Cause__c</fullName>
    <label>Exception Cause</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Exception_Logger__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Logger__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Exception_Logger__c/fields/Module_Name__c.field-meta.xml
<CustomField>
    <fullName>Module_Name__c</fullName>
    <label>Module Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_LogException.cls
/**
* @File Name          : UB_LogException.cls
* @Description        : Class to insert ExceptionLog into system.
* @Author             : Zafaruddin
* @Test CLass         : UB_LogExceptionTest
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         20-03-2024           Zafaruddin         Initial Version
*/
public class UB_LogException extends Exception {
    
    public String ModuleName {get; set;}
    public String StackTrace {get; set;}
    public String ClassName {get; set;}
    public String MethodName {get; set;}
     
    /**
     * @Description : Method to insert Exception record in system
     * @Author      :Zafaruddin
     * @Date        :21/03/2024
    */
    public void log(Exception ex,String lob)
    {
            System.debug('EORRRRR LOGGGGGGG');
        	if(ex != null) {
                System.debug('EORRRRR LOGGGGGGG 111 ' +ex);
                stackTrace = ex.getStackTraceString().substringBefore('\n');
                System.debug('stackTrace  '+stackTrace);
                className = stackTrace.substringAfter('.').substringBefore('.');
                System.debug('className   '+className);
                methodName = stackTrace.substringBefore(':').substringAfter(className).substringAfter('.');  
                System.debug('methodName   '+methodName);
                System.debug('Exception EEEE  '+ex);
            
                Exception_Logger__c logger = new Exception_Logger__c();
                logger.Module_Name__c = ModuleName;
                logger.Stack_Trace__c = ex.getStackTraceString();
                logger.Class_Name__c = className;
                logger.Method_Name__c = methodName;
                logger.Line_Number__c = ex.getLineNumber();
                logger.Exception_Type__c = ex.getTypeName();
                logger.Exception_Cause__c = String.valueOf(ex.getCause());
                logger.LOB__c = lob;
                logger.Exception_Message__c = ex.getMessage();
                System.debug('BEFORE INSERT  logger   '+logger);
                insert logger; 
            
            System.debug('AFTER INSERT    logger   '+logger);
        }
        	        
    }
    
}