force-app/main/default/objects/BL_Rate_Code_Master__c/BL_Rate_Code_Master__c.object-meta.xml
<CustomObject>
    <label>Rate Code Master</label>
    <nameField>
        <displayFormat>RC-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Code Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/BL_Rate_Code_Master__c/fields/BL_Index_Rate__c.field-meta.xml
<CustomField>
    <fullName>BL_Index_Rate__c</fullName>
    <label>Index Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/BL_Rate_Code_Master__c/fields/BL_Rate_Code__c.field-meta.xml
<CustomField>
    <fullName>BL_Rate_Code__c</fullName>
    <label>Rate Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Applied Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New CV</fullName>
            </value>
            <value>
                <fullName>Used CV</fullName>
            </value>
            <value>
                <fullName>New CE</fullName>
            </value>
            <value>
                <fullName>Used CE</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <defaultValue>&apos;WHE999&apos;</defaultValue>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WHE999</fullName>
                <default>true</default>
                <label>CV/CE(WHE999)</label>
            </value>
            <value>
                <fullName>266</fullName>
                <label>Business Loan Plus</label>
            </value>
            <value>
                <fullName>129</fullName>
                <label>Business Loan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Product_Vertical__c</fullName>
    <label>Product Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wheels</fullName>
            </value>
            <value>
                <fullName>Retail Assets</fullName>
            </value>
            <value>
                <fullName>MSME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/recordTypes/Login.recordType-meta.xml
<RecordType>
    <fullName>Login</fullName>
    <active>true</active>
    <label>Login</label>
</RecordType>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/BL_Applied_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>BL_Applied_Loan_Amount__c</fullName>
    <label>Applied Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Balance_Transfer_Applicable__c.field-meta.xml
<CustomField>
    <fullName>BL_Balance_Transfer_Applicable__c</fullName>
    <label>Balance Transfer Applicable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Index_Rate__c.field-meta.xml
<CustomField>
    <fullName>BL_Index_Rate__c</fullName>
    <label>Index Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Interest_Type__c.field-meta.xml
<CustomField>
    <fullName>BL_Interest_Type__c</fullName>
    <label>Interest Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Floating</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Loan_Tenure_months__c.field-meta.xml
<CustomField>
    <fullName>BL_Loan_Tenure_months__c</fullName>
    <label>Loan Tenure(in months)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Moratorium_Period_Month__c.field-meta.xml
<CustomField>
    <fullName>BL_Moratorium_Period_Month__c</fullName>
    <label>Moratorium Period (Month)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Rate_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>BL_Rate_of_Interest__c</fullName>
    <label>Rate of Interest(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Spread__c.field-meta.xml
<CustomField>
    <fullName>BL_Spread__c</fullName>
    <label>Spread (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Number_Of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Vehicles__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Master__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Schemes__c.field-meta.xml
<CustomField>
    <fullName>Product_Schemes__c</fullName>
    <formula>TEXT( Product__r.Product_Schemes__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Schemes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <formula>TEXT( Product__r.Product_Sub_Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Sub Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Product_Vertical__c</fullName>
    <label>Product Vertical</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Master__c/Product_Master__c.object-meta.xml
<CustomObject>
    <label>Product Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Master__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CV-New</fullName>
            </value>
            <value>
                <fullName>CE-New</fullName>
            </value>
            <value>
                <fullName>CV-Used</fullName>
            </value>
            <value>
                <fullName>CE-Used</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Schemes__c.field-meta.xml
<CustomField>
    <fullName>Product_Schemes__c</fullName>
    <label>Product Schemes</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTU &amp; FTB</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Institutional Strategic</fullName>
            </value>
            <value>
                <fullName>Captive Retail</fullName>
            </value>
            <value>
                <fullName>Captive Strategic</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>GPR</fullName>
            </value>
            <value>
                <fullName>Banking Surrogate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <label>Product Sub Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transporter</fullName>
            </value>
            <value>
                <fullName>Bus Operator</fullName>
            </value>
            <value>
                <fullName>Captive</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Hirer</fullName>
            </value>
            <value>
                <fullName>Mine Owner</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial Vehicle Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Construction Equipment Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Tractor Loan</fullName>
        <isActive>false</isActive>
        <label>Tractor Loan</label>
    </customValue>
    <customValue>
        <fullName>Three Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Three Wheeler Loan</label>
    </customValue>
    <customValue>
        <fullName>Car Loan</fullName>
        <isActive>false</isActive>
        <label>Car Loan</label>
    </customValue>
    <customValue>
        <fullName>Office Equipment</fullName>
        <isActive>false</isActive>
        <label>Office Equipment</label>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
        <isActive>false</isActive>
        <label>Medical Equipment</label>
    </customValue>
    <customValue>
        <fullName>Two Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Two Wheeler Loan</label>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_ProductSelectionController.cls
/**
* @File Name          : UB_ProductSelectionController.cls
* @Description        : This controller used to fetch product master info and used in ProductSelectionScreen LWC.
* @Author             : Mohit
* @Test CLass         : UB_ProductSelectionControllerTest
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         24-04-2024               Mohit                 Initial Version
*/
public class UB_ProductSelectionController {
    @AuraEnabled
    public static List<PicklistSet> fetchSubCategoryValues(String productCategory, String productSubCategory){
        List<PicklistSet> picklistValues = new List<PicklistSet>();
        Set<String> picklistValueSet = new Set<String>();
        List<Product_Master__c> productMasterList = new List<Product_Master__c>();
        String query = 'SELECT Id, Product_Sub_Category__c, Product_Schemes__c FROM Product_Master__c ';
        if(String.isNotBlank(productCategory) && String.isNotBlank(productSubCategory)){
            query += ' WHERE Active__c = true AND Product_Category__c = \''+productCategory+'\'';
            query += ' AND Product_Sub_Category__c = \''+productSubCategory+'\'';
        }else if(String.isNotBlank(productCategory) && String.isBlank(productSubCategory)){
            query += ' WHERE Active__c = true AND Product_Category__c = \''+productCategory+'\'';
        }
        productMasterList = Database.query(query);
        
        if(!productMasterList.isEmpty() && productMasterList.size() > 0){
            for(Product_Master__c obj : productMasterList){
                if(String.isBlank(productSubCategory)){
                    picklistValueSet.add(obj.Product_Sub_Category__c);
                }else{
                    picklistValueSet.add(obj.Product_Schemes__c);
                }
            }
            
            for(String str : picklistValueSet){
                picklistValues.add(new PicklistSet(str, str));
            }
            return picklistValues;
        }
        return null;
    }
    
    @AuraEnabled
    public static String checkValidations(String loanApplicationId, String recordId){
        List<Loan_Application__c> loanApplicationList = new UB_LoanApplicationsSelector().selectById(new Set<Id>{loanApplicationId});
        List<Product__c> productList = new List<Product__c>();
        String query = ' SELECT Id,Product_Category__c,Product_Sub_Category__c,Product_Schemes__c,Number_Of_Vehicles__c, ';
        query       += ' BL_Applied_Loan_Amount__c, BL_Balance_Transfer_Applicable__c, BL_Index_Rate__c,BL_Interest_Type__c, ';
        query       += ' BL_Loan_Tenure_months__c, BL_Moratorium_Period_Month__c, BL_Purpose_of_Loan__c, BL_Rate_Code__c, ';
        query       += ' BL_Rate_of_Interest__c, BL_Spread__c, Product__r.LOB__c, Product_Vertical__c ';
        query       += ' FROM Product__c ';
        query       += ' WHERE Loan_Application__c = \''+loanApplicationId+'\'';
        if(String.isNotBlank(recordId)){
            query += ' AND Id = \''+recordId+'\'';
        }
        //query       += ' ORDER BY CreatedDate ASC ';
        productList = Database.query(query);
        
        //Added By Mohit on 30-07-24 for BL - <Product can't update after login stage for BL process>
        if(String.isNotBlank(loanApplicationList[0].LOB__c) && loanApplicationList[0].LOB__c == UB_ConstantsUtil.LOB_BL){
            if(loanApplicationList[0].RecordTypeId != UB_ConstantsUtil.LOGIN_LOAN_APPLICATION_RECORD_TYPE){
                Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('ProductScreenValidation');
                return messageConfigMap.get('ProductEditRestriction') != null ? messageConfigMap.get('ProductEditRestriction').Message__c : null;
            }
        }
        
        if(!productList.isEmpty() && productList.size() > 0){
            if(String.isNotBlank(loanApplicationList[0].LOB__c)){
                if(loanApplicationList[0].LOB__c == BL_ConstantsUtil.LOB_BL){
                    if(productList.size() > 0 && String.isBlank(recordId)){
                        Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('ProductScreenValidation');
                        return messageConfigMap.get('TwoProductValidation') != null ? messageConfigMap.get('TwoProductValidation').Message__c : null;
                    }else if(productList.size() == 1 && String.isNotBlank(recordId)){
                        ProductDetails obj = new ProductDetails();
                        obj.category    			  = productList[0].Product_Category__c;
                        obj.subCategory 			  = productList[0].Product_Sub_Category__c;
                        obj.scheme                    = productList[0].Product_Schemes__c;
                        obj.vertical                  = productList[0].Product_Vertical__c;
                        obj.balanceTransferApplicable = productList[0].BL_Balance_Transfer_Applicable__c;
                        obj.loanAmount                = productList[0].BL_Applied_Loan_Amount__c;
                        obj.indexRate      			  = productList[0].BL_Index_Rate__c;
                        obj.interestType      		  = productList[0].BL_Interest_Type__c;
                        obj.loanTenure      		  = productList[0].BL_Loan_Tenure_months__c;
                        obj.moratoriumPeriod      	  = Integer.valueOf(productList[0].BL_Moratorium_Period_Month__c);
                        obj.loanPurpose      		  = productList[0].BL_Purpose_of_Loan__c;
                        obj.rateCode      			  = productList[0].BL_Rate_Code__c;
                        obj.disableInterest           = productList[0].BL_Interest_Type__c == BL_ConstantsUtil.FLOATING_INTEREST_TYPE ? true : false;
                        obj.rateOfInterest      	  = productList[0].BL_Rate_of_Interest__c;
                        obj.spread      			  = productList[0].BL_Spread__c;
                        obj.lob                       = productList[0].Product__r.LOB__c;
                        return 'recordFound#'+JSON.serialize(obj);
                    }
                }else{
                    if(productList.size() >= 2 && String.isBlank(recordId)){
                        Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('ProductScreenValidation');
                        return messageConfigMap.get('TwoProductValidation') != null ? messageConfigMap.get('TwoProductValidation').Message__c : null;
                    }else if(productList.size() == 1 || (productList.size() >= 2 && String.isNotBlank(recordId))){
                        ProductDetails obj = new ProductDetails();
                        for(Product__c productObj : productList){
                            if(String.isBlank(recordId)){
                                if(productObj.Product_Category__c.contains('New')){
                                    obj.category = productObj.Product_Category__c.replace('New','Used');
                                }else if(productObj.Product_Category__c.contains('Used')){
                                    obj.category = productObj.Product_Category__c.replace('Used','New');
                                }
                            }else{
                                obj.category = productObj.Product_Category__c;
                            }
                            obj.subCategory     = productObj.Product_Sub_Category__c;
                            obj.scheme          = productObj.Product_Schemes__c;
                            obj.numberOfVehicle = productObj.Number_Of_Vehicles__c != null && productObj.Number_Of_Vehicles__c > 0 ? Integer.valueOf(productObj.Number_Of_Vehicles__c) : 1;
                            obj.lob             = productList[0].Product__r.LOB__c;
                        } return 'recordFound#'+JSON.serialize(obj);
                    }    
                }
            }else{
                Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('ProductScreenValidation');
                return messageConfigMap.get('NoApplicationLOBFound') != null ? messageConfigMap.get('NoApplicationLOBFound').Message__c : null;
            }
        } 
        ProductDetails obj = new ProductDetails();
        obj.category    = BL_ConstantsUtil.BL_PRODUCT_CATEGORY;
        if(String.isNotBlank(loanApplicationList[0].Lead__r.Product_Name__c)){
            obj.subCategory = loanApplicationList[0].Lead__r.Product_Name__c.contains('129') ? BL_ConstantsUtil.BL_PRODUCT_CATEGORY : BL_ConstantsUtil.BUSINESS_LOAN_PLUS_CATEGORY; 
        }else{
            obj.subCategory = BL_ConstantsUtil.BL_PRODUCT_CATEGORY;
        }
        obj.loanTenure  = loanApplicationList[0].Lead__r.Loan_Period__c != null ? loanApplicationList[0].Lead__r.Loan_Period__c : 0;
        obj.loanAmount  = loanApplicationList[0].Lead__r.Amount__c != null ? loanApplicationList[0].Lead__r.Amount__c : 0;
        obj.lob         = loanApplicationList[0].LOB__c;
        return 'Success#'+JSON.serialize(obj);
    }
    
    @AuraEnabled
    public static String createProduct(String recordId, String loanApplicationId, String productDetails){
        if(productDetails != null && String.isNotBlank(productDetails)){
            ProductDetails customObj = (ProductDetails) JSON.deserialize(productDetails, ProductDetails.class);
            List<Product_Master__c> productList = new UB_ProductMastersSelector().filterByCriteria(customObj.category, customObj.subCategory, customObj.scheme);
            if(!productList.isEmpty() && productList.size() > 0){
                Product__c createProduct = new Product__c();
                createProduct.Name                  = productList[0].Name;
                createProduct.Loan_Application__c   = loanApplicationId;
                createProduct.Product__c            = productList[0].Id;
                if(productList[0].LOB__c != UB_ConstantsUtil.LOB_BL){
                    createProduct.Number_Of_Vehicles__c = customObj.numberOfVehicle != null && customObj.numberOfVehicle > 0 ? customObj.numberOfVehicle : 1;
                }
                if(productList[0].LOB__c == UB_ConstantsUtil.LOB_BL){
                    createProduct.Product_Vertical__c               = customObj.vertical;
                    createProduct.BL_Balance_Transfer_Applicable__c = String.isNotBlank(customObj.balanceTransferApplicable) ? customObj.balanceTransferApplicable : '';              
                    createProduct.BL_Applied_Loan_Amount__c         = customObj.loanAmount != null && customObj.loanAmount > 0 ? customObj.loanAmount : 0;
                    createProduct.BL_Index_Rate__c                  = customObj.indexRate != null && customObj.indexRate > 0 ? customObj.indexRate : 0;          
                    createProduct.BL_Interest_Type__c 			    = String.isNotBlank(customObj.interestType) ? customObj.interestType : '';          
                    createProduct.BL_Loan_Tenure_months__c 			= customObj.loanTenure != null && customObj.loanTenure > 0 ? customObj.loanTenure : 0;
                    createProduct.BL_Moratorium_Period_Month__c 	= customObj.moratoriumPeriod != null && customObj.moratoriumPeriod > 0 ? customObj.moratoriumPeriod : 0;
                    createProduct.BL_Purpose_of_Loan__c				= String.isNotBlank(customObj.loanPurpose) ? customObj.loanPurpose : '';          
                    createProduct.BL_Rate_Code__c					= String.isNotBlank(customObj.rateCode) ? customObj.rateCode : '';          
                    createProduct.BL_Rate_of_Interest__c 			= customObj.rateOfInterest != null && customObj.rateOfInterest > 0 ? customObj.rateOfInterest : 0;
                    createProduct.BL_Spread__c 						= customObj.spread != null && customObj.spread > 0 ? customObj.spread : 0;
                }
                
                // Set up the unit of work
                fflib_ISObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<Schema.SObjectType>{Product__c.sObjectType});
                uow.registerNew(new List<Product__c>{createProduct});
                
                if(String.isNotBlank(recordId)){
                    uow.registerDeleted(new List<Product__c>{new Product__c(Id = recordId)});
                }
                // Commit all of the work at a safe moment
                uow.commitWork();
                
                List<Product__c> existingProductList = new UB_ProductsSelector().selectByLoanApplicationIds(new Set<Id>{loanApplicationId});
                Loan_Application__c updateObj = new Loan_Application__c(Id = loanApplicationId);
                updateObj.LOB__c = String.isNotBlank(productList[0].LOB__c) ? productList[0].LOB__c : '';
                if(productList[0].LOB__c != UB_ConstantsUtil.LOB_BL){
                    updateObj.CB_Customer_Category__c = String.isNotBlank(customObj.scheme) ? customObj.scheme : '';
                    if(!existingProductList.isEmpty() && existingProductList.size() > 1){
                        updateObj.Application_Type__c = UB_ConstantsUtil.NEW_USED_CATEGORY;
                    }else{
                        updateObj.Application_Type__c = productList[0].Product_Category__c.contains(UB_ConstantsUtil.NEW_CATEGORY) ? UB_ConstantsUtil.NEW_CATEGORY : UB_ConstantsUtil.USED_CATEGORY;
                    }
                    if(String.isNotBlank(productList[0].LOB__c)){
                        if(productList[0].LOB__c == UB_ConstantsUtil.LOB_CV){
                            updateObj.Product__c = UB_ConstantsUtil.COMMERCIAL_VEHICLE_LOAN;
                        }else if(productList[0].LOB__c == UB_ConstantsUtil.LOB_CE){
                            updateObj.Product__c = UB_ConstantsUtil.CONSTRUCTION_EQUIPMENT_LOAN;
                        }
                    }
                }
                // Set up the unit of work
                fflib_ISObjectUnitOfWork uowApp = new fflib_SObjectUnitOfWork(new List<Schema.SObjectType>{Loan_Application__c.sObjectType});
                uowApp.registerDirty(updateObj);
                // Commit all of the work at a safe moment
                uowApp.commitWork();
                return 'Success';
            }else{
                Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('ProductScreenValidation');
                return messageConfigMap.get('NoProductMasterRecordFound') != null ? messageConfigMap.get('NoProductMasterRecordFound').Message__c : null;
            }
        } return null;
    }
    
    @AuraEnabled(cacheable=true)
    public static Map<String,Decimal> fetchProductRateCodes(String productDetails){
        ProductDetails customObj = (ProductDetails) JSON.deserialize(productDetails, ProductDetails.class);
        List<Product_Master__c> productList = new UB_ProductMastersSelector().filterByCriteria(customObj.category, customObj.subCategory, customObj.scheme);
        if(!productList.isEmpty() && productList.size() > 0){
            String query = ' SELECT Id,BL_Rate_Code__c,BL_Product_Master__c,BL_Is_Active__c,BL_Effective_Date__c,BL_Index_Rate__c ';
            query       += ' FROM BL_Rate_Code_Master__c ';
            query       += ' WHERE BL_Product_Master__c = \''+productList[0].Id+'\' AND ';
            query       += ' BL_Effective_Date__c != null AND BL_Is_Active__c = true ';
            query       += ' ORDER BY BL_Effective_Date__c DESC ';
            List<BL_Rate_Code_Master__c> rateCodeList = Database.query(query);
            if(!rateCodeList.isEmpty() && rateCodeList.size() > 0){
                Set<String> rateCodeSet = new Set<String>();
                Map<String,Decimal> mapCodeWithIndexRate = new Map<String,Decimal>();
                for(BL_Rate_Code_Master__c obj : rateCodeList){
                    rateCodeSet.add(obj.BL_Rate_Code__c);
                    if(!mapCodeWithIndexRate.containsKey(obj.BL_Rate_Code__c)){
                        mapCodeWithIndexRate.put(obj.BL_Rate_Code__c, obj.BL_Index_Rate__c);
                    }
                }
                return mapCodeWithIndexRate;
            }
        }
        return null;
    }
    
     @AuraEnabled(cacheable=true)
    public static String fetchInterestRange(String productDetails){
        ProductDetails customObj = (ProductDetails) JSON.deserialize(productDetails, ProductDetails.class);
        List<Product_Master__c> productList = new UB_ProductMastersSelector().filterByCriteria(customObj.category, customObj.subCategory, customObj.scheme);
        if(!productList.isEmpty() && productList.size() > 0){
            return productList[0].BL_Minimum_ROI__c+'#'+productList[0].BL_Maximum_ROI__c;
        }
        return null;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<PicklistSet> fetchDropdownValues(String objectApiName, String fieldApiName){
        List<PicklistSet> options = new List<PicklistSet>();
        Schema.DescribeFieldResult fieldResult = Schema.getGlobalDescribe().get(objectApiName).getDescribe().fields.getMap().get(fieldApiName).getDescribe();

        List<Schema.PicklistEntry> picklistValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry entry : picklistValues) {
            options.add(new PicklistSet(entry.getValue(), entry.getLabel()));
        }
        return options;
    }
    
    public class PicklistSet {
        @AuraEnabled public String label { get; set; }
        @AuraEnabled public String value { get; set; }
        
        public PicklistSet(String label, String value){
            this.label = label;
            this.value = value;
        }
    }
    
    public class ProductDetails {
        @AuraEnabled public String  category { get; set; }
        @AuraEnabled public String  subCategory { get; set; }
        @AuraEnabled public String  scheme { get; set; }
        @AuraEnabled public String  vertical { get; set; }
        @AuraEnabled public String  balanceTransferApplicable { get; set; }
        @AuraEnabled public String  loanPurpose { get; set; } 
		@AuraEnabled public String  interestType { get; set; } 
        @AuraEnabled public String  rateCode { get; set; }
        @AuraEnabled public String  lob { get; set; } 
        @AuraEnabled public Integer numberOfVehicle { get; set; }
        @AuraEnabled public Integer moratoriumPeriod { get; set; }
        @AuraEnabled public Decimal indexRate { get; set; }
        @AuraEnabled public Decimal loanAmount { get; set; }
        @AuraEnabled public Decimal loanTenure { get; set; }
        @AuraEnabled public Decimal spread { get; set; } 
        @AuraEnabled public Decimal rateOfInterest { get; set; }
        @AuraEnabled public Boolean disableInterest { get; set; } 
    }
}