force-app/main/default/objects/Product_Master__c/Product_Master__c.object-meta.xml
<CustomObject>
    <label>Product Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Master__c/fields/BL_Maximum_ROI__c.field-meta.xml
<CustomField>
    <fullName>BL_Maximum_ROI__c</fullName>
    <label>Maximum ROI(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/BL_Minimum_ROI__c.field-meta.xml
<CustomField>
    <fullName>BL_Minimum_ROI__c</fullName>
    <label>Minimum ROI(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/CoApplicant_Applicant_Office_FI_Mandator__c.field-meta.xml
<CustomField>
    <fullName>CoApplicant_Applicant_Office_FI_Mandator__c</fullName>
    <label>CoApplicant Applicant Office FI Mandator</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Propertioship</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>Public Ltd</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/CoApplicant_applicant_Residence_FI_Manda__c.field-meta.xml
<CustomField>
    <fullName>CoApplicant_applicant_Residence_FI_Manda__c</fullName>
    <label>CoApplicant applicant Residence FI Manda</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Propertioship</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>Public Ltd</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Credit_Assessment_Method__c.field-meta.xml
<CustomField>
    <fullName>Credit_Assessment_Method__c</fullName>
    <label>Credit Assessment Method</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Financials</fullName>
            </value>
            <value>
                <fullName>Viability-CV</fullName>
            </value>
            <value>
                <fullName>Viability-CE</fullName>
            </value>
            <value>
                <fullName>FFR</fullName>
            </value>
            <value>
                <fullName>Hire vs Buy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Guarantor_applicant_Office_FI_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Guarantor_applicant_Office_FI_Mandatory__c</fullName>
    <label>Guarantor applicant Office FI Mandatory</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Propertioship</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>Public Ltd</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Guarantor_applicant_Residence_FI_Mandato__c.field-meta.xml
<CustomField>
    <fullName>Guarantor_applicant_Residence_FI_Mandato__c</fullName>
    <label>Guarantor applicant Residence FI Mandato</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Propertioship</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>Public Ltd</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Primary_applicant_Office_FI_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Primary_applicant_Office_FI_Mandatory__c</fullName>
    <label>Primary applicant Office FI Mandatory</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Propertioship</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>Public Ltd</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Primary_applicant_Residence_FI_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Primary_applicant_Residence_FI_Mandatory__c</fullName>
    <label>Primary applicant Residence FI Mandatory</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Propertioship</fullName>
            </value>
            <value>
                <fullName>Partnership</fullName>
            </value>
            <value>
                <fullName>Pvt Ltd</fullName>
            </value>
            <value>
                <fullName>Public Ltd</fullName>
            </value>
            <value>
                <fullName>LLP</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CV-New</fullName>
            </value>
            <value>
                <fullName>CE-New</fullName>
            </value>
            <value>
                <fullName>CV-Used</fullName>
            </value>
            <value>
                <fullName>CE-Used</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Schemes__c.field-meta.xml
<CustomField>
    <fullName>Product_Schemes__c</fullName>
    <label>Product Schemes</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTU &amp; FTB</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Institutional Strategic</fullName>
            </value>
            <value>
                <fullName>Captive Retail</fullName>
            </value>
            <value>
                <fullName>Captive Strategic</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>GPR</fullName>
            </value>
            <value>
                <fullName>Banking Surrogate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <label>Product Sub Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transporter</fullName>
            </value>
            <value>
                <fullName>Bus Operator</fullName>
            </value>
            <value>
                <fullName>Captive</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Hirer</fullName>
            </value>
            <value>
                <fullName>Mine Owner</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_ProductMastersSelector.cls
/**
* @File Name          : UB_ProductMastersSelector.cls
* @Description        : This class used to fetch/query Product Master records based on conditions.
* @Author             : Deepak Joshi 
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         25-04-2024               Deepak Joshi                 Initial Version
*/
public with sharing class UB_ProductMastersSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
           Product_Master__c.Name,
           Product_Master__c.Id,
           Product_Master__c.Credit_Assessment_Method__c,
           Product_Master__c.Product_Category__c,
           Product_Master__c.Product_Sub_Category__c,
           Product_Master__c.Product_Schemes__c,
           Product_Master__c.LOB__c,
                 Product_Master__c.CoApplicant_Applicant_Office_FI_Mandator__c,
                Product_Master__c.CoApplicant_applicant_Residence_FI_Manda__c,
                Product_Master__c.Guarantor_applicant_Office_FI_Mandatory__c,
                Product_Master__c.Guarantor_applicant_Residence_FI_Mandato__c,
                Product_Master__c.Primary_applicant_Office_FI_Mandatory__c,
                Product_Master__c.Primary_applicant_Residence_FI_Mandatory__c
        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Product_Master__c.sObjectType;
    }
    
    public List<Product_Master__c> selectById(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN : recordIds');
        return (List<Product_Master__c>) Database.query(query.toSOQL());
    }
    
    public List<Product_Master__c> filterByCriteria(String category, String subCategory, String schemes){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Product_Category__c =: category AND Product_Sub_Category__c =: subCategory AND Product_Schemes__c =: schemes');
        query.selectField('BL_Maximum_ROI__c');
        query.selectField('BL_Minimum_ROI__c');
        return (List<Product_Master__c>) Database.query(query.toSOQL());
    }
}