force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UB_Perfios_Retrieve_Report_Integration.cls
/**
* @File Name          : UB_Perfios_Retrieve_Report_Integration
* @Description        : Class to Trigger Perfios APIs for Retrieving Reports
* @Author             : Chandan Kumar
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0                           Initial Version
*/
public without sharing class UB_Perfios_Retrieve_Report_Integration implements Queueable, Database.AllowsCallouts {
    
    // Class level variables
    private final UB_HTTPCalloutService service; 
    public Id customerDocId;
    public String transactionID;
    List<API_Logger__c> createLogList = new List<API_Logger__c>();
    
    // Constants
    private static final Integer STATUS_CODE_SUCCESS = 200;
    private static final String FILE_TYPE = 'xlsx';
    
    /**
* Parameterized Constructor
* 
* @param customerDocId - The ID of the customer document.
* @param transactionID - The transaction ID.
*/
    public UB_Perfios_Retrieve_Report_Integration(Id customerDocId, String transactionID) {
        this.service = new UB_HTTPCalloutService('Perfios_Initiate_Transaction_API');
        this.customerDocId = customerDocId;
        this.transactionID = transactionID;
    }
    
    /**
* Non-Parameterized Constructor needed for the implementation of UbRetryApiLwcController.IReTryAPI (Interface).
*/
    public UB_Perfios_Retrieve_Report_Integration() {
        // this.service = new UB_HTTPCalloutService();
    }
    
    /**
* Method to execute the Queueable job
*/
    public void execute(QueueableContext context) {
        if (isValidCustomerDocId(this.customerDocId)) {           
            retrieveReportFile(this.transactionID);
        }
    }
    
    /**
* Method to check if the customer document ID is valid
*/
    private Boolean isValidCustomerDocId(Id customerDocId) {
        return customerDocId != null && String.isNotEmpty(customerDocId);
    }
    
    /**
* Method to retrieve the report file
* 
* @param transactionId - The transaction ID.
*/
    public void retrieveReportFile(String transactionId) {   
        try {
            List<Loan_Applicant__c> applicants = new UB_LoanApplicantsSelector().selectByIdWithParentRecords(new Set<Id>{customerDocId});
            HTTPResponse res = UB_Perfios_IntegrationUtil.retrieveReport(transactionId, FILE_TYPE,string.valueof(customerDocId));
            system.debug('res====>'+res);
            
            
            if (res.getStatusCode() == STATUS_CODE_SUCCESS) {
                String verificationId = UB_CommonUtil.fetchVerificationId(customerDocId,UB_ConstantsUtil.PERFIOS_API);               
                UB_Perfios_IntegrationUtil.saveFile(res, verificationId, 'Report', FILE_TYPE,customerDocId,applicants[0].Loan_Application__c);
            } else {
                handleUnsuccessfulResponse(res);
            }
        } catch (Exception e) {
            System.debug('Error :' + e.getMessage());
            System.debug('In Line Number :' + e.getLineNumber());
            UB_LogException error = new UB_LogException();
            error.log(e, '');
        }
    }
    
    /**
* Method to handle unsuccessful responses
* 
* @param res - The HTTP response.
*/
    private void handleUnsuccessfulResponse(HTTPResponse res) {
        System.debug('Unexpected status code: ' + res.getStatusCode());
    }
}