force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>IF(ISBLANK(Entity_Name__c ), First_Name__c +&apos; &apos;+ Middle_Name__c +&apos; &apos;+ Last_Name__c , Entity_Name__c )</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Date_Of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Incorporation__c</fullName>
    <label>Date Of Incorporation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Pan_Number__c.field-meta.xml
<CustomField>
    <fullName>Pan_Number__c</fullName>
    <label>Pan Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/PAN_Verification__c.field-meta.xml
<CustomField>
    <fullName>PAN_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PAN Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Messages_Config__mdt/Messages_Config__mdt.object-meta.xml
<CustomObject>
    <label>Messages Config</label>
    <pluralLabel>Messages Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failed_Reason__c</fullName>
    <label>Failed Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Is_Aadhar_Linked__c.field-meta.xml
<CustomField>
    <fullName>Is_Aadhar_Linked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Aadhar Linked?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Is_DOB_Matched__c.field-meta.xml
<CustomField>
    <fullName>Is_DOB_Matched__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is DOB Matched?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Is_Duplicate__c.field-meta.xml
<CustomField>
    <fullName>Is_Duplicate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Duplicate?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Is_Name_Matched__c.field-meta.xml
<CustomField>
    <fullName>Is_Name_Matched__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Name Matched?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/PAN_DOB__c.field-meta.xml
<CustomField>
    <fullName>PAN_DOB__c</fullName>
    <label>PAN DOB</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/PAN_Name__c.field-meta.xml
<CustomField>
    <fullName>PAN_Name__c</fullName>
    <label>PAN Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>OTP Sent</fullName>
            </value>
            <value>
                <fullName>OTP Attempt Failed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_PAN_PROFILE_API.cls
/**
* @File Name          : UB_PAN_PROFILE_API.cls
* @Description        : This API is used to check PAN Profile for customer.
* @Author             : Mohd Musab
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         26-06-2024               Mohd Musab                 Initial Version
*/

public class UB_PAN_PROFILE_API {
    UB_HTTPCalloutService service;
    
    @future(callout = true)
    public static void validateAccountNumber (Id customerId, String accessToken){
        Map<String,Messages_Config__mdt> errorMessageConfigMap = UB_CommonUtil.getMessageRecord('GenericErrorMessage');
        List<Verification__c> insertRecords = new List<Verification__c>();
        List<API_Logger__c> createLogList = new List<API_Logger__c>();
        List<Loan_Applicant__c> loanAppList = new UB_LoanApplicantsSelector().selectById(new Set<Id>{customerId});
        //Savepoint sp = Database.setSavepoint();
        try{
            UB_PAN_PROFILE_API panStatusCheck = new UB_PAN_PROFILE_API();
            panStatusCheck.service = new UB_HTTPCalloutService('PAN_PROFILE_API');
            
            JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('pan',String.isNotBlank(loanAppList[0].Pan_Number__c) ? loanAppList[0].Pan_Number__c : '');
            gen.writeStringField('name',loanAppList[0].Account_Name__c);
            if(loanAppList[0].RecordTypeId == UB_ConstantsUtil.INDIVIDUAL_APPICANT_RECORD_TYPE && loanAppList[0].Date_of_Birth__c != null){
                gen.writeStringField('dob',
                                     DateTime.newInstance(
                                         loanAppList[0].Date_of_Birth__c.year(), 
                                         loanAppList[0].Date_of_Birth__c.month(), 
                                         loanAppList[0].Date_of_Birth__c.day()
                                     ).format('yyyy-MM-dd')
                                    );
            }else if(loanAppList[0].RecordTypeId == UB_ConstantsUtil.NON_INDIVIDUAL_APPICANT_RECORD_TYPE && loanAppList[0].Date_Of_Incorporation__c != null){
            	gen.writeStringField('dob',
                                     DateTime.newInstance(
                                         loanAppList[0].Date_Of_Incorporation__c.year(), 
                                         loanAppList[0].Date_Of_Incorporation__c.month(), 
                                         loanAppList[0].Date_Of_Incorporation__c.day()
                                     ).format('yyyy-MM-dd')
                                    );
            }
            gen.writeStringField('consent','Y');
            gen.writeFieldName('clientData');
            gen.writeStartObject();
            gen.writeStringField('caseId',loanAppList[0].Id);
            gen.writeEndObject();
            gen.writeEndObject();
            
            panStatusCheck.service.setHeaderParameter('Authorization','Bearer '+accessToken);
        	panStatusCheck.service.setRequestBody(gen.getAsString());        
            HttpResponse response = panStatusCheck.service.sendRequest(); 
            System.debug('response## '+response.getBody());
            Map<String,Object> mapResponseResult = (Map<String,Object>) JSON.deserializeUntyped(response.getBody());
            Verification__c verify = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.PAN_VERIFICATION_RECORD_TYPE, UB_ConstantsUtil.COMPLETEDSTATUS);
            if(response.getStatusCode() == 200){
                if(mapResponseResult.keySet().size() > 0 && mapResponseResult.containsKey('result')){
                    Map<String,Object> mapResponseBody = (Map<String,Object>) (mapResponseResult.get('result'));
                    if(mapResponseBody != null && mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('name')){
                        verify.PAN_Name__c = (String) String.valueOf(mapResponseBody.get('name'));
                    }
                    if(mapResponseBody != null && mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('dob')){
                        verify.PAN_DOB__c = (String) String.valueOf(mapResponseBody.get('dob'));
                    }
                    if(mapResponseBody != null && mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('aadhaarLinked')){
                        verify.Is_Aadhar_Linked__c = (boolean)mapResponseBody.get('aadhaarLinked');
                    }
                    if(mapResponseBody.containsKey('profileMatch')){
                        List<Object> profileMatchList = (List<Object>) mapResponseBody.get('profileMatch');
                        if(profileMatchList.size() > 0){
                            for(Object profileMatchObj : profileMatchList){
                                Map<String, Object> profileMatchMap = (Map<String, Object>) profileMatchObj;
                                String parameter = (String) profileMatchMap.get('parameter');
                                Boolean matchResult = (Boolean) profileMatchMap.get('matchResult');
                                
                                if(parameter == 'name'){
                                    verify.Is_Name_Matched__c = matchResult;
                                } else if(parameter == 'dob'){
                                    verify.Is_DOB_Matched__c = matchResult;
                                }
                            }
                        }

                    }
                    /*if(mapResponseBody != null && mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('dobMatch')){
                        String isDOBMatched = (String) String.valueOf(mapResponseBody.get('dobMatch'));
                        verify.Is_DOB_Matched__c = isDOBMatched != null && String.isNotBlank(isDOBMatched) && isDOBMatched == 'true' ? true : false; 
                    }*/
                    /*if(mapResponseBody != null && mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('duplicate')){
                        String isDupMatched = (String) String.valueOf(mapResponseBody.get('duplicate'));
                        verify.Is_Duplicate__c = isDupMatched != null && String.isNotBlank(isDupMatched) && isDupMatched == 'true' ? true : false;
                    }*/
                    /*
                    if(mapResponseBody != null && mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('nameMatch')){
                        String isNameMatched = (String) String.valueOf(mapResponseBody.get('nameMatch'));
                        verify.Is_Name_Matched__c = isNameMatched != null && String.isNotBlank(isNameMatched) && isNameMatched == 'true' ? true : false; 
                    }*/
                }else{
                    verify.Failed_Reason__c = errorMessageConfigMap.get('NoResultFound').Message__c;
                    verify.Status__c = UB_ConstantsUtil.FAILED_STATUS;
                }
            }else{
                verify.Failed_Reason__c = errorMessageConfigMap.get('NoResultFound').Message__c;
                verify.Status__c = UB_ConstantsUtil.FAILED_STATUS;
            }
            insertRecords.add(verify);
            API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                panStatusCheck.service.getEndpointURL(), 
                String.valueOf(panStatusCheck.service.getHeaderParameters()), 
                panStatusCheck.service.getRequestMethod(), 
                gen.getAsString(), 
                response.getBody(), 
                response.getStatusCode(), 
                UB_PAN_API.class.getName(), 
                customerId, 
                Id.valueOf(customerId).getSObjectType().getDescribe().getName(), 
                UB_ConstantsUtil.REST_API_TYPE,
                'PAN Profile API',
                loanAppList[0].Loan_Application__r.LOB__c
            );
            if(mapResponseResult.containsKey('status')){
                apiLogger.Status__c = (String) String.valueOf(mapResponseResult.get('status'));
            }
            createLogList.add(apiLogger);
            
            if(!createLogList.isEmpty() && createLogList.size() > 0){
                UB_API_LoggerUtility.insertRecords(createLogList);
            }
        }catch(Exception e) {
            //Database.rollback(sp);
            //Database.releaseSavepoint(sp);
            Verification__c verify = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.PAN_VERIFICATION_RECORD_TYPE, UB_ConstantsUtil.FAILED_STATUS);
			verify.Failed_Reason__c = e.getMessage();
            insertRecords.add(verify); 
            System.debug('Exception@@'+e.getMessage());
            UB_CommonUtil.createExceptionLogRecord(e, loanAppList[0].Loan_Application__r.LOB__c);
        }
        
        if(!insertRecords.isEmpty() && insertRecords.size() > 0){
            insertRecords = UB_VerificationUtility.insertRecords(insertRecords);
            UB_LoanApplicantUtility.updateRecords(new List<Loan_Applicant__c>{new Loan_Applicant__c(Id = customerId, PAN_Verification__c = insertRecords[0].Id)});
        }
    }
}