force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Details__c/Bank_Details__c.object-meta.xml
<CustomObject>
    <label>Bank Details</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Bank Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Details__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Saving</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>CC/OD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>Disbursement__c</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>IFSC_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IFSC Code</label>
    <referenceTo>IFSC_Master__c</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Is_Primary_Repayment_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Repayment_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Repayment Account?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Disbursement__c/fields/E_Nach_Verification__c.field-meta.xml
<CustomField>
    <fullName>E_Nach_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>E-Nach Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/First_EMI_Date__c.field-meta.xml
<CustomField>
    <fullName>First_EMI_Date__c</fullName>
    <label>First EMI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Last_Emi_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Emi_Date__c</fullName>
    <label>Last Emi Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Tenure</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IFSC_Master__c/IFSC_Master__c.object-meta.xml
<CustomObject>
    <label>IFSC Master</label>
    <nameField>
        <label>Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IFSC Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Co-Applicant</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <label>Is Deleted</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Official_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Official_Email_ID__c</fullName>
    <label>Official Email ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Pan_Number__c.field-meta.xml
<CustomField>
    <fullName>Pan_Number__c</fullName>
    <label>Pan Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Messages_Config__mdt/Messages_Config__mdt.object-meta.xml
<CustomObject>
    <label>Messages Config</label>
    <pluralLabel>Messages Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>Disbursement__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/E_Nach_Reference__c.field-meta.xml
<CustomField>
    <fullName>E_Nach_Reference__c</fullName>
    <label>E-Nach Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failed_Reason__c</fullName>
    <label>Failed Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>IFSC_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IFSC Code</label>
    <referenceTo>IFSC_Master__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>OTP Sent</fullName>
            </value>
            <value>
                <fullName>OTP Attempt Failed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_ENACH_API.cls
/**
* @File Name          : UB_ENACH_API.cls
* @Description        : This API is used .......
* @Author             : Mohd Musab
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         01-07-2024               Mohd Musab                 Initial Version
*/
public class UB_ENACH_API {
	UB_HTTPCalloutService service;

    @future(callout = true)
    public static void getENach(Id disbursementId, String accessToken){
        System.debug('disbursementId '+disbursementId);
        System.debug('accessToken '+accessToken);
        //String accessToken = UB_GenerateAccessToken.getToken('Token_Generate_API');
        List<Disbursement__c> listOfDisbursement = [SELECT Id,Loan_Application__c,Loan_Amount__c,Tenure__c,ROI__c,First_EMI_Date__c,Last_Emi_Date__c,EMI_Amount__c from Disbursement__c WHERE Id =: disbursementId];
        List<Loan_Applicant__c> loanAppList = [SELECT Id,Name,Official_Email_ID__c,Mobile__c,Telephone__c,Loan_Application__c,Loan_Application__r.LOB__c,Pan_Number__c from Loan_Applicant__c WHERE Loan_Application__c =: listOfDisbursement[0].Loan_Application__c AND Is_Deleted__c = 'No' AND Applicant_Type__c =: UB_ConstantsUtil.APPLICANT LIMIT 1];
        List<Verification__c> insertVerifyRecords = new List<Verification__c>();
        List<API_Logger__c> createLogList = new List<API_Logger__c>();
        Map<String,Messages_Config__mdt> errorMessageConfigMap = UB_CommonUtil.getMessageRecord('GenericErrorMessage');
        try{
        //List<Loan_Applicant__c> loanAppList = new UB_LoanApplicantsSelector().selectById(new Set<Id>{customerId});
        List<Bank_Details__c> bankDetailList = [SELECT Id,Account_Number__c, Account_Type__c,IFSC_Code__r.Name from Bank_Details__c WHERE Is_Primary_Repayment_Account__c = true AND Loan_Application__c =: listOfDisbursement[0].Loan_Application__c LIMIT 1];
        System.debug('listOfDisbursement@@ '+listOfDisbursement);
        System.debug('loanAppList@@ '+loanAppList);
        System.debug('errorMessageConfigMap@@ '+errorMessageConfigMap);
        System.debug('bankDetailList@@ '+bankDetailList);

        UB_ENACH_API e_NachInstance = new UB_ENACH_API();
        e_NachInstance.service = new UB_HTTPCalloutService('E_NACH_API');

        JSONGenerator gen = JSON.createGenerator(true);
            gen.writeStartObject();
            gen.writeStringField('referenceNumber', 'NACHUTK12345679');
            gen.writeStringField('utilityCode', 'NACH00000000000019');
            gen.writeStringField('categoryCode', 'L002');
            gen.writeStringField('schmNm', 'Loan amount security');
            gen.writeStringField('consRefNo', 'NACHCRT000000091');
            gen.writeStringField('seqTp', 'RCUR');
            gen.writeStringField('frqcy', 'MNTH');
            gen.writeStringField('frstColltnDt', listOfDisbursement[0].First_EMI_Date__c != null ? String.Valueof(listOfDisbursement[0].First_EMI_Date__c): null);
            gen.writeStringField('fnlColltnDt', listOfDisbursement[0].Last_Emi_Date__c != null ? String.Valueof(listOfDisbursement[0].Last_Emi_Date__c) : null);
            gen.writeStringField('amountTp', 'MAXA');
            gen.writeStringField('colltnAmt', listOfDisbursement[0].EMI_Amount__c != null ? String.Valueof(listOfDisbursement[0].EMI_Amount__c):null);
            gen.writeStringField('dbtrNm', !String.isBlank(loanAppList[0].Name) ? loanAppList[0].Name : '');
            gen.writeStringField('phone', !String.isBlank(loanAppList[0].Telephone__c) ? loanAppList[0].Telephone__c : '');
            gen.writeStringField('mobile', !String.isBlank(loanAppList[0].Mobile__c) ? loanAppList[0].Mobile__c : '');
            gen.writeStringField('email', !String.isBlank(loanAppList[0].Official_Email_ID__c) ? loanAppList[0].Official_Email_ID__c : '');
            gen.writeStringField('pan', !String.isBlank(loanAppList[0].Pan_Number__c) ? loanAppList[0].Pan_Number__c : '');
            gen.writeStringField('bnkId', (bankDetailList.size()>0 && bankDetailList[0].IFSC_Code__r.Name != null) ? bankDetailList[0].IFSC_Code__r.Name.substring(0, 4):'');
            gen.writeStringField('dbtrAccTp', (bankDetailList.size()>0 && bankDetailList[0].Account_Type__c != null) ? String.valueOf(bankDetailList[0].Account_Type__c) : '' );
            gen.writeStringField('dbtrAccNo', (bankDetailList.size()>0 && bankDetailList[0].Account_Number__c != null) ? String.valueOf(bankDetailList[0].Account_Number__c) : '');
            gen.writeEndObject();
              e_NachInstance.service.setHeaderParameter('Authorization','Bearer '+accessToken);

        System.debug('URL params@@  '+e_NachInstance.service.getURLParameters());
        e_NachInstance.service.setRequestBody(gen.getAsString());        
        HttpResponse response = e_NachInstance.service.sendRequest(); 
        System.debug('response@@@ '+response);
        System.debug('response## '+response.getBody());
        String mockResponse = '{"timestamp":"2024-03-18T11:37:04.664674665Z","status":"200","code":"201","message":"2878091999088880f","moreInfo":"mandate request created.","reference":"81af5adc-1c26-457b-b694-0bd317b14923"}';
        Map<String,Object> mapResponseResult = (Map<String,Object>) JSON.deserializeUntyped(response.getBody());
        //Map<String,Object> mapResponseResult = (Map<String,Object>) JSON.deserializeUntyped(mockResponse);
            Verification__c verify = UB_CommonUtil.createVerfication(loanAppList[0].Id, UB_ConstantsUtil.ENACH_VERIFICATION_RECORD_TYPE, UB_ConstantsUtil.COMPLETEDSTATUS);
            verify.Disbursement__c = disbursementId;
            System.debug('verify@@ '+verify);
            //Verification__c verify = new Verification__c();
            if(response.getStatusCode() == 200){
                System.debug('Success##');
                if(mapResponseResult.keySet().size() > 0 && mapResponseResult.containsKey('reference')){
                    verify.E_Nach_Reference__c = (String) String.valueOf(mapResponseResult.get('reference'));
                }else{
                    verify.Failed_Reason__c = errorMessageConfigMap.get('NoResultFound').Message__c;
                    verify.Status__c = UB_ConstantsUtil.FAILED_STATUS;
                }
            }else{
                verify.Failed_Reason__c = errorMessageConfigMap.get('NoResultFound').Message__c;
                verify.Status__c = UB_ConstantsUtil.FAILED_STATUS;
            }
            insertVerifyRecords.add(verify);
            if(insertVerifyRecords.size()>0){
               insert insertVerifyRecords;
               update new Disbursement__c(Id = disbursementId, E_Nach_Verification__c = insertVerifyRecords[0].Id);
            }
            API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                e_NachInstance.service.getEndpointURL(), 
                String.valueOf(e_NachInstance.service.getHeaderParameters()), 
                e_NachInstance.service.getRequestMethod(), 
                gen.getAsString(), 
                response.getBody(), 
                response.getStatusCode(), 
                UB_ENACH_API.class.getName(), 
                loanAppList[0].Id, 
                Id.valueOf(loanAppList[0].Id).getSObjectType().getDescribe().getName(), 
                UB_ConstantsUtil.REST_API_TYPE,
                'E-NACH API',
                UB_ConstantsUtil.LOB_CV
            );
            if(mapResponseResult.containsKey('status')){
                apiLogger.Status__c = (String) String.valueOf(mapResponseResult.get('status'));
            }
            createLogList.add(apiLogger);
            
            if(!createLogList.isEmpty() && createLogList.size() > 0){
                UB_API_LoggerUtility.insertRecords(createLogList);
            }
        }
        catch(Exception e) { 
            UB_CommonUtil.createExceptionLogRecord(e, loanAppList[0].Loan_Application__r.LOB__c);   
            System.debug('Exception@@'+e.getMessage());   
            System.debug('Exception@@'+e.getLineNumber());      
        }
    }
}