force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Applied Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Consent_Received__c.field-meta.xml
<CustomField>
    <fullName>Consent_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent Received?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <label>GUID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Loan_Period__c.field-meta.xml
<CustomField>
    <fullName>Loan_Period__c</fullName>
    <label>Loan Tenure(in months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New CV</fullName>
            </value>
            <value>
                <fullName>Used CV</fullName>
            </value>
            <value>
                <fullName>New CE</fullName>
            </value>
            <value>
                <fullName>Used CE</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/SUBMIT_DATE__c.field-meta.xml
<CustomField>
    <fullName>SUBMIT_DATE__c</fullName>
    <label>SUBMIT DATE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Cibil_Verification__c.field-meta.xml
<CustomField>
    <fullName>Cibil_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cibil Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Cibil Verification)</relationshipLabel>
    <relationshipName>Loan_Applicants3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Consent_Received__c.field-meta.xml
<CustomField>
    <fullName>Consent_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent Received?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Consent_Verification__c.field-meta.xml
<CustomField>
    <fullName>Consent_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consent Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Consent Verification)</relationshipLabel>
    <relationshipName>Loan_Applicants5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/BL_Product_Name__c.field-meta.xml
<CustomField>
    <fullName>BL_Product_Name__c</fullName>
    <formula>TEXT(Lead__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Period__c.field-meta.xml
<CustomField>
    <fullName>Loan_Period__c</fullName>
    <label>Loan Tenure (in Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Messages_Config__mdt/Messages_Config__mdt.object-meta.xml
<CustomObject>
    <label>Messages Config</label>
    <pluralLabel>Messages Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Master__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failed_Reason__c</fullName>
    <label>Failed Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <label>GUID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/SUBMIT_DATE__c.field-meta.xml
<CustomField>
    <fullName>SUBMIT_DATE__c</fullName>
    <label>SUBMIT DATE</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial Vehicle Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Construction Equipment Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Tractor Loan</fullName>
        <isActive>false</isActive>
        <label>Tractor Loan</label>
    </customValue>
    <customValue>
        <fullName>Three Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Three Wheeler Loan</label>
    </customValue>
    <customValue>
        <fullName>Car Loan</fullName>
        <isActive>false</isActive>
        <label>Car Loan</label>
    </customValue>
    <customValue>
        <fullName>Office Equipment</fullName>
        <isActive>false</isActive>
        <label>Office Equipment</label>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
        <isActive>false</isActive>
        <label>Medical Equipment</label>
    </customValue>
    <customValue>
        <fullName>Two Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Two Wheeler Loan</label>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_ConsentValueFirstApi.cls
/**
* @File Name          : UB_ConsentValueFirstApi.cls
* @Description        : 
* @Author             :Zafaruddin
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         20-05-2024            Zafaruddin         Initial Version

**/

public with sharing class UB_ConsentValueFirstApi {

    UB_HTTPCalloutService service;

    @AuraEnabled
    public static string checkCustomerConsent(String leadId){
        try {
            if(String.isNotBlank(leadId)) {
                String accessToken = UB_GenerateAccessToken.getToken('Token_Generate_API');
                UB_ConsentValueFirstApi.getCustomerConsent(leadId,accessToken);
                return 'success';
            }
        } catch (Exception e) {
            System.debug('Exception@@'+e.getMessage());
            System.debug('Exception@@ LINEEEEEE  '+e.getLineNumber());
            return e.getMessage();
        }
        return 'Please connect with System Admin, Internal Error.';
    }


    @future(callout = true)
    public static void getCustomerConsent (Id customerId, String accessToken){
        String sObjName = customerId.getSObjectType().getDescribe().getName();
        List<Loan_Applicant__c> loanAppList = new List<Loan_Applicant__c> ();
        List<Loan_Application__c> applicationList = new List<Loan_Application__c> ();
        List<Lead__c> leadList = new List<Lead__c> ();
        String RequestJson;
        UB_ConsentValueFirstApi consentApi = new UB_ConsentValueFirstApi();
        Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('ReadTimeOutIssue');
        Verification__c verifyRecord = new Verification__c();
        consentApi.service = new UB_HTTPCalloutService('Consent_Api_Value_First');
        consentApi.service.setHeaderParameter('Authorization', 'Bearer '+accessToken);
        Savepoint sp;
        String LOB = UB_ConstantsUtil.LOB_CV; 
        try {
            if(sObjName == 'Loan_Applicant__c') {
                loanAppList= new UB_LoanApplicantsSelector().selectByIdWithParentRecords(new Set<Id>{customerId});
                applicationList = new UB_LoanApplicationsSelector().selectById(new Set<Id>{loanAppList[0].Loan_Application__c});
                LOB = applicationList[0].LOB__c;
                if(LOB != UB_ConstantsUtil.LOB_BL){
                    RequestJson = '{"@VER":"1.2","USER":{"@CH_TYPE":"4","@UNIXTIMESTAMP":""},"SMS":[{"@UDH":"0","@CODING":"1","@TEXT":"","@TEMPLATEINFO":"' + consentApi.service.getExtraParameter('TEMPLATEINFO') + '~' + applicationList[0].Product__c   + '~' + applicationList[0].Amount__c  + '~' + applicationList[0].Loan_Period__c + '","@BTN_PAYLOAD0":"SFDC_CV","@BTN_PAYLOAD1":"SFDC_CV","@PROPERTY":"0","@MSGTYPE":"3","@MEDIADATA":"'+ System.Label.consentValueFirstUrl  +'","@TYPE":"' + 'document' + '~' + 'USFB T&C' + '","@ID":"'+ applicationList[0].Id +'","ADDRESS":[{"@FROM":"' + consentApi.service.getExtraParameter('FROM') +'","@TO":"' + loanAppList[0].Mobile__c+ '","@SEQ":"1","@TAG":"some clientside random data"}]}]}';
                }else{
                    if(applicationList[0].Lead__c != null){
                        RequestJson = '{"@VER":"1.2","USER":{"@CH_TYPE":"4","@UNIXTIMESTAMP":""},"SMS":[{"@UDH":"0","@CODING":"1","@TEXT":"","@TEMPLATEINFO":"' + consentApi.service.getExtraParameter('TEMPLATEINFO') + '~' + applicationList[0].BL_Product_Name__c   + '~' + applicationList[0].Lead__r.Amount__c  + '~' + applicationList[0].Lead__r.Loan_Period__c + '","@BTN_PAYLOAD0":"SFDC_CV","@BTN_PAYLOAD1":"SFDC_CV","@PROPERTY":"0","@MSGTYPE":"3","@MEDIADATA":"'+ System.Label.consentValueFirstUrl  +'","@TYPE":"' + 'document' + '~' + 'USFB T&C' + '","@ID":"'+ applicationList[0].Id +'","ADDRESS":[{"@FROM":"' + consentApi.service.getExtraParameter('FROM') +'","@TO":"' + loanAppList[0].Mobile__c+ '","@SEQ":"1","@TAG":"some clientside random data"}]}]}';
                    }
                }
            } else {
                leadList = new UB_LeadsSelector().selectById(new Set<Id>{customerId});
                System.debug('LEADDDDDD  '+leadList);
            	LOB = leadList[0].LOB__c;
                if(LOB != UB_ConstantsUtil.LOB_BL){
                    RequestJson = '{"@VER":"1.2","USER":{"@CH_TYPE":"4","@UNIXTIMESTAMP":""},"SMS":[{"@UDH":"0","@CODING":"1","@TEXT":"","@TEMPLATEINFO":"' + consentApi.service.getExtraParameter('TEMPLATEINFO') + '~' + leadList[0].Product_Category__c + ' Loan'  + '~' + leadList[0].Amount__c  + '~' + leadList[0].Loan_Period__c  + '","@BTN_PAYLOAD0":"SFDC_CV","@BTN_PAYLOAD1":"SFDC_CV","@PROPERTY":"0","@MSGTYPE":"3","@MEDIADATA":"'+ System.Label.consentValueFirstUrl  +'","@TYPE":"' + 'document' + '~' +'USFB T&C'+ '","@ID":"'+ leadList[0].Id +'","ADDRESS":[{"@FROM":"' + consentApi.service.getExtraParameter('FROM') +'","@TO":"' + leadList[0].Mobile_Number__c+ '","@SEQ":"1","@TAG":"some clientside random data"}]}]}';
                }else{
                    RequestJson = '{"@VER":"1.2","USER":{"@CH_TYPE":"4","@UNIXTIMESTAMP":""},"SMS":[{"@UDH":"0","@CODING":"1","@TEXT":"","@TEMPLATEINFO":"' + consentApi.service.getExtraParameter('TEMPLATEINFO') + '~' + leadList[0].Product_Category__c + '~' + leadList[0].Amount__c  + '~' + leadList[0].Loan_Period__c  + '","@BTN_PAYLOAD0":"SFDC_CV","@BTN_PAYLOAD1":"SFDC_CV","@PROPERTY":"0","@MSGTYPE":"3","@MEDIADATA":"'+ System.Label.consentValueFirstUrl  +'","@TYPE":"' + 'document' + '~' +'USFB T&C'+ '","@ID":"'+ leadList[0].Id +'","ADDRESS":[{"@FROM":"' + consentApi.service.getExtraParameter('FROM') +'","@TO":"' + leadList[0].Mobile_Number__c+ '","@SEQ":"1","@TAG":"some clientside random data"}]}]}';
                }
            }

            consentApi.service.setRequestBody(RequestJson);
            HTTPResponse responeObj = new HTTPResponse();
            responeObj = consentApi.service.sendRequest();
            String JSONResponse = responeObj.getBody();//res.getBody();
            
            Map<String,Object> ResponseMap = (Map<String,Object>)JSON.deserializeUntyped(JSONResponse);
            if(ResponseMap.get('MESSAGEACK') != NULL) {
                ResponseMap = (Map<String,Object>)ResponseMap.get('MESSAGEACK');
                if(ResponseMap.get('GUID') != NULL) {
                    API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                        consentApi.service.getEndpointURL(), 
                        String.valueOf(consentApi.service.getHeaderParameters()), 
                        consentApi.service.getRequestMethod(), 
                        RequestJson, 
                        responeObj.getBody(), 
                        responeObj.getStatusCode(), 
                        UB_ConsentValueFirstApi.class.getName(), 
                        customerId, 
                        Id.valueOf(customerId).getSObjectType().getDescribe().getName(), 
                        UB_ConstantsUtil.REST_API_TYPE,
                        'Consent API',
                        LOB
                        );
                    if(apiLogger != NULL) {
                        insert apiLogger;
                        System.debug('apiLogger  '+apiLogger);
                    }
                    
                    ResponseMap = (Map<String,Object>)ResponseMap.get('GUID');
                    if(sObjName == 'Loan_Applicant__c') {
                        verifyRecord = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.CONSENT_CHECK_RECORD_TYPE,UB_ConstantsUtil.IN_PROGRESS_STATUS);
                    } else {
                        verifyRecord = UB_CommonUtil.createVerfication(null, UB_ConstantsUtil.CONSENT_CHECK_RECORD_TYPE,UB_ConstantsUtil.IN_PROGRESS_STATUS);
                        verifyRecord.Lead__c = customerId;
                        update new Lead__c(Id = customerId, Consent_Received__c	= false,
                            GUID__c = String.valueOf(ResponseMap.get('GUID')),
                            SUBMIT_DATE__c = String.valueOf(ResponseMap.get('SUBMITDATE'))
                        ); 
                    }
                    verifyRecord.SUBMIT_DATE__c = String.valueOf(ResponseMap.get('SUBMITDATE'));
                    verifyRecord.GUID__c = String.valueOf(ResponseMap.get('GUID'));
                    insert verifyRecord;
                    if(sObjName == 'Loan_Applicant__c') {
                        update new Loan_Applicant__c(Id = customerId, Consent_Verification__c = verifyRecord.Id); 
                    }
                }          
            } else {
                if(sObjName == 'Loan_Applicant__c') {
                    verifyRecord = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.DEDUPE_VERIFICATION_RECORD_TYPE,UB_ConstantsUtil.FAILED_STATUS);
                    verifyRecord.Failed_Reason__c = messageConfigMap.get('Read_Time_Out_Api_Issue').Message__c;
                    insert verifyRecord;
                    update new Loan_Applicant__c(Id = customerId, Cibil_Verification__c = verifyRecord.Id);
                }
            }
        }catch(Exception e) {
            //Database.rollback(sp);
            System.debug('Exception@@'+e.getMessage());
            System.debug('Exception@@ LINEEEEEE  '+e.getLineNumber());
            UB_CommonUtil.createExceptionLogRecord(e, LOB);
        }
    }
}