force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Is_Report_available__c.field-meta.xml
<CustomField>
    <fullName>Is_Report_available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Report available ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Perfios_API_Status__c.field-meta.xml
<CustomField>
    <fullName>Perfios_API_Status__c</fullName>
    <label>Perfios Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>ERROR_USER</fullName>
            </value>
            <value>
                <fullName>ERROR_SITE</fullName>
            </value>
            <value>
                <fullName>ERROR_SESSION_EXPIRED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Perfios_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Perfios_Transaction_Id__c</fullName>
    <label>Perfios Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Processing_Files_Done__c.field-meta.xml
<CustomField>
    <fullName>Processing_Files_Done__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processing Files Done</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UB_Perfios_Generate_Report_Integration.cls
/**
* @File Name          : UB_Perfios_Generate_Report_Integration
* @Description        : Class to Trigger Perfios APIs for Generating Reports
* @Author             : Chandan Kumar
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0                           Initial Version
*/
public without sharing class UB_Perfios_Generate_Report_Integration implements Queueable, Database.AllowsCallouts {
    
    // Class level variables
    private final UB_HTTPCalloutService service;
    public String transactionID;
    public String customerDocumentID,verificationId;
    List<API_Logger__c> createLogList = new List<API_Logger__c>();
    
    // Constants
    private static final Integer STATUS_CODE_ACCEPTED = 202;
    
    /**
* Parameterized Constructor
* 
* @param customerDocumentID - The ID of the customer document.
* @param transactionID - The transaction ID.
*/
    public UB_Perfios_Generate_Report_Integration(String customerDocumentID, String transactionID,string verificationId) {
        // this.service = new UB_HTTPCalloutService();
        this.transactionID = transactionID;
        this.customerDocumentID = customerDocumentID;
        this.verificationId = verificationId;
         this.service = new UB_HTTPCalloutService('Perfios_Generate_Report_API');
    }
    
    // Default constructor
    public UB_Perfios_Generate_Report_Integration() {
      
    }
    
    /**
* Method to execute the Queueable job
*/
    public void execute(QueueableContext context) {
        if (isValidTransactionId(this.transactionID)) {
            generateReport(this.transactionID);
        }
    }
    
    /**
* Method to check if the transaction ID is valid
*/
    private Boolean isValidTransactionId(String transactionId) {
        return String.isNotEmpty(transactionId) && String.isNotBlank(transactionId);
    }
    
    /**
* Method to generate the report
* 
* @param transactionId - The transaction ID.
*/
    public void generateReport(String transactionId) {  
        try {
            Verification__c verification = [SELECT Id,Perfios_API_Status__c,Is_Report_available__c,Loan_Applicant__c,Processing_Files_Done__c FROM Verification__c WHERE Perfios_Transaction_Id__c =:transactionId AND Loan_Applicant__c =:customerDocumentID LIMIT 1];          
            HTTPResponse res = UB_Perfios_IntegrationUtil.generateReport(transactionId,customerDocumentID);            
            if (res.getStatusCode() == STATUS_CODE_ACCEPTED) {
                System.enqueueJob(new UB_Perfios_Status(transactionID,customerDocumentID));
               // HTTPResponse res1 = UB_Perfios_IntegrationUtil.getPerfiosSatus(transactionID,customerDocumentID);
                
                // Deserialize the JSON string into a map
              //  Map<String, Object> deserializedResult = (Map<String, Object>) JSON.deserializeUntyped(res1.getBody());
               // System.debug('deserializedResult==>' + deserializedResult);
                
                // Access the nested map to get the required values
              /*    if (deserializedResult.containsKey('transactions')) {
                    Map<String, Object> transactions = (Map<String, Object>) deserializedResult.get('transactions');
                    
                  if (transactions.containsKey('transaction')) {
                        Map<String, Object> transactionRec = (Map<String, Object>) transactions.get('transaction');
                        Boolean reportAvailable = (Boolean) transactionRec.get('reportAvailable');
                        String status = (String) transactionRec.get('status');
                        
                        System.debug('reportAvailable==>' + reportAvailable);
                        System.debug('status==>' + status);
                        verification.Perfios_API_Status__c = status;
                        verification.Is_Report_available__c = reportAvailable;
                        update verification;
                        if(status == 'COMPLETED' && reportAvailable){
                            system.debug('inside fetching the document');
                            System.enqueueJob(new UB_Perfios_Retrieve_Report_Integration(customerDocumentID, transactionID));
                        }
                    }
                }*/
                // System.enqueueJob(new UB_Perfios_Retrieve_Report_Integration(customerDocumentID, transactionID));
            } else {
                updateVerificationRecordWithFailureStatus(res);
            }
        } catch (Exception e) {           
            System.debug('Error :' + e.getMessage());
            System.debug('In Line Number :' + e.getLineNumber()); 
            UB_LogException error = new UB_LogException();
            error.log(e, '');
            
        }
    }
    
    /**
* Method to update the verification record with failure status
*/
    private void updateVerificationRecordWithFailureStatus(HTTPResponse res ) {
}
}