force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Details__c/Bank_Details__c.object-meta.xml
<CustomObject>
    <label>Bank Details</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Bank Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Details__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <formula>IFSC_Code__r.Bank_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bank Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Institution_Id__c.field-meta.xml
<CustomField>
    <fullName>Institution_Id__c</fullName>
    <label>Institution Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{00000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Uploaded</fullName>
                <default>true</default>
                <label>Not Uploaded</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Submitted to CPA</fullName>
            </value>
            <value>
                <fullName>CPA Acknowledged</fullName>
            </value>
            <value>
                <fullName>CM Acknowledged</fullName>
            </value>
            <value>
                <fullName>RCU Acknowledged</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Not Received</fullName>
                <isActive>false</isActive>
                <label>Not Received</label>
            </value>
            <value>
                <fullName>OTC</fullName>
                <isActive>false</isActive>
                <label>OTC</label>
            </value>
            <value>
                <fullName>PDD</fullName>
                <isActive>false</isActive>
                <label>PDD</label>
            </value>
            <value>
                <fullName>Query Raised</fullName>
                <isActive>false</isActive>
                <label>Query Raised</label>
            </value>
            <value>
                <fullName>RCU Verified</fullName>
                <isActive>false</isActive>
                <label>RCU Verified</label>
            </value>
            <value>
                <fullName>Verified</fullName>
                <isActive>false</isActive>
                <label>Verified</label>
            </value>
            <value>
                <fullName>Waived Off</fullName>
                <isActive>false</isActive>
                <label>Waived Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Name_of_the_Bank__c.field-meta.xml
<CustomField>
    <fullName>Name_of_the_Bank__c</fullName>
    <label>Name of the Bank</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Perfios_Verification__c.field-meta.xml
<CustomField>
    <fullName>Perfios_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Perfios Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Verification)</relationshipLabel>
    <relationshipName>Loan_Applicants8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Period__c.field-meta.xml
<CustomField>
    <fullName>Loan_Period__c</fullName>
    <label>Loan Tenure (in Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Master__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failed_Reason__c</fullName>
    <label>Failed Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Perfios_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Perfios_Transaction_Id__c</fullName>
    <label>Perfios Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>OTP Sent</fullName>
            </value>
            <value>
                <fullName>OTP Attempt Failed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial Vehicle Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Construction Equipment Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Tractor Loan</fullName>
        <isActive>false</isActive>
        <label>Tractor Loan</label>
    </customValue>
    <customValue>
        <fullName>Three Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Three Wheeler Loan</label>
    </customValue>
    <customValue>
        <fullName>Car Loan</fullName>
        <isActive>false</isActive>
        <label>Car Loan</label>
    </customValue>
    <customValue>
        <fullName>Office Equipment</fullName>
        <isActive>false</isActive>
        <label>Office Equipment</label>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
        <isActive>false</isActive>
        <label>Medical Equipment</label>
    </customValue>
    <customValue>
        <fullName>Two Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Two Wheeler Loan</label>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_BANK_STATEMENT_Perfios_Integration.cls
/**
* @File Name          : UB_BANK_STATEMENT_Perfios_Integration
* @Description        : Class to Trigger Perfios APIs for retrieving TransactionId.
* @Author             : Chandan Kumar
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0                           Initial Version
*/

public without sharing class UB_BANK_STATEMENT_Perfios_Integration implements Queueable, Database.AllowsCallouts {
    
    // Class level variables
    public Id customerId;
    private String password;
    private UB_HTTPCalloutService service;
    private UB_HTTPCalloutService callbackService;
    
    private static final String PROCESS_TYPE = 'STATEMENT';
    private static final String LOAN_TYPE = 'Personal Loan';
    
    /**
* Description: Parameterized Constructor for Passing the Parameters to Queueable Class.
* @param customerId - The ID of the customer for whom the transaction is being created.
*/
    public UB_BANK_STATEMENT_Perfios_Integration(Id customerId, String password) {
        this.customerId = customerId;
        this.password = password;
        this.service = new UB_HTTPCalloutService('Perfios_Initiate_Transaction_API');
       // this.callbackService = new UB_HTTPCalloutService('Perfios_Transaction_Callback');
    } 
    
    /**
* Description: Executes the Queueable job to create a transaction.
* @param context - The context of the queueable job.
*/
    public void execute(QueueableContext context) {
        try {
            createTransaction();
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            System.debug('In Line Number: ' + e.getLineNumber());
            UB_LogException error = new UB_LogException();
            error.log(e, '');
        }
    }
    
    /**
* Description: Method to create a transaction with Perfios.
*/
    public void createTransaction() {
        Verification__c verify = null;
        List<Verification__c> createVerifyList = new List<Verification__c>();
        List<API_Logger__c> createLogList = new List<API_Logger__c>();
        
        HTTPResponse res = new HTTPResponse();
        List<Loan_Applicant__c> applicants = new UB_LoanApplicantsSelector().selectByIdWithParentRecords(new Set<Id>{customerId});
        try {
            
            String bankName = applicants[0].Name_of_the_Bank__c;
            /*  Bank_Details__c bankDetail = selectBankDetailsByBankName(bankName);

if (bankDetail == null || String.isBlank(bankDetail.Institution_Id__c)) {
verify = createVerificationRecord('Institution Id is not available in Application Bank Details');
createVerifyList.add(verify);
insert createVerifyList;
applicants[0].Perfios_Verification__c = createVerifyList[0].Id;
update applicants;
return;
}*/
            
            String rangeFrom = '2019-01'; //system.now().addMonths(-6).format('yyyy-MM')
            String rangeTo = '2019-03'; //system.now().format('yyyy-MM');
            String loanType = applicants[0].Loan_Application__r.LOB__c != UB_ConstantsUtil.LOB_BL ? String.valueOf(applicants[0].Loan_Application__r.Product__c) : BL_ConstantsUtil.BL_PRODUCT_CATEGORY;
            UB_Perfios_IntegrationUtil.payloadParent plDetails = new UB_Perfios_IntegrationUtil.payloadParent(
                applicants[0].Id,
                String.valueOf(Integer.valueOf(applicants[0].Loan_Application__r.Amount__c)),
                String.valueOf(applicants[0].Loan_Application__r.Loan_Period__c),
                loanType,
                PROCESS_TYPE,
                rangeFrom,
                rangeTo,
                '',
                'atLeastOneTransactionPerMonthInRange',
                '20'//bankDetail.Institution_Id__c
            );
            
            UB_Perfios_IntegrationUtil.processPayload processPayload = new UB_Perfios_IntegrationUtil.processPayload();
            processPayload.payload = plDetails;
            String payload = JSON.serialize(processPayload, true);
            
            res = UB_Perfios_IntegrationUtil.initiateTransaction(payload);
            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            
            if (res.getStatusCode() == 200 && responseMap.containsKey('transaction')) {
                Map<String, Object> perfiosTransactionIdMap = (Map<String, Object>) responseMap.get('transaction');
                String perfiosTransactionId = (String) perfiosTransactionIdMap.get('perfiosTransactionId');
                
                verify = createVerificationRecord(null);
                verify.Perfios_Transaction_Id__c =perfiosTransactionId;//'RN3A1720448347043';
                verify.Loan_Applicant__c = customerId;
                verify.Password__c = password;
                createVerifyList.add(verify);
                
                insert createVerifyList;
                applicants[0].Perfios_Verification__c = createVerifyList[0].Id;
                update applicants;
                
                Document__c document = createDocumentRecord(applicants[0].Loan_Application__c, customerId, createVerifyList[0].Id);
                document.Document_Type__c = 'Banking Document';
                insert document;
                
                List<ContentVersion> cvObjList = selectContentVersionsByLinkedEntityId(customerId);
                UB_DisplayUBDocumentsController.uploadDocument('', cvObjList[0].Title, String.valueOf(cvObjList[0].VersionData), document.Id, cvObjList[0].Id);
                
                System.enqueueJob(new UB_Perfios_Upload_Files_Integration(customerId,perfiosTransactionId, cvObjList,  createVerifyList[0].Id));
            } else {
                verify = createVerificationRecord('Received status code ' + res.getStatusCode());
                createVerifyList.add(verify);
            }
            
            API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                service.getEndpointURL(), 
                String.valueOf(service.getHeaderParameters()), 
                service.getRequestMethod(), 
                String.valueOf(plDetails), 
                res.getBody(), 
                res.getStatusCode(), 
                UB_BANK_STATEMENT_Perfios_Integration.class.getName(), 
                customerId, 
                Id.valueOf(customerId).getSObjectType().getDescribe().getName(), 
                UB_ConstantsUtil.REST_API_TYPE,
                'Perfios Initiate Transaction',
                'CV'
            );
            createLogList.add(apiLogger);
            if (!createLogList.isEmpty()) {
                UB_API_LoggerUtility.insertRecords(createLogList);
            }
            
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            System.debug('In Line Number: ' + e.getLineNumber());
            UB_LogException error = new UB_LogException();
            error.log(e, '');
            
            verify = createVerificationRecord(e.getMessage() + ' at line ' + e.getLineNumber());
            createVerifyList.add(verify);
        }
        
        if (!createVerifyList.isEmpty() && createVerifyList[0].Id == null) {
            insert createVerifyList;
            applicants[0].Perfios_Verification__c = createVerifyList[0].Id;
            update applicants;
        }
    }
    
    private Verification__c createVerificationRecord(String failedReason) {
        Verification__c verify = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.PERFIOS_API_RECORD_TYPE, 'In Progress');
        verify.Failed_Reason__c = failedReason;
        verify.Loan_Applicant__c = customerId;
        return verify;
    }
    
    private Document__c createDocumentRecord(Id loanApplicationId, Id customerId, Id verificationId) {
        Document__c document = new Document__c();
        document.Loan_Application__c = loanApplicationId;
        document.Loan_Applicant__c = customerId;
        document.Verification__c = verificationId;
        document.Document_Type__c = 'Banking Document';
        document.Status__c = 'Uploaded';
        return document;
    }
    
    private Bank_Details__c selectBankDetailsByBankName(String bankName) {
        List<Bank_Details__c> bankDetails = [SELECT Id, Institution_Id__c 
                                             FROM Bank_Details__c 
                                             WHERE Bank_Name__c = :bankName];
        if (!bankDetails.isEmpty()) {
            return bankDetails[0];
        }
        return null;
    }
    
    private List<ContentVersion> selectContentVersionsByLinkedEntityId(Id linkedEntityId) {
        List<String> contentDocumentIdList = new List<String>();
        for (ContentDocumentLink docLink : [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId = :customerId]) {
            contentDocumentIdList.add(docLink.ContentDocumentId);
            System.debug('document id: ' + docLink.ContentDocumentId);
        }
        
        // Fetch the content versions of the documents
        List<ContentVersion> cvObjList = [SELECT Title, Id, VersionData, FileType FROM ContentVersion WHERE ContentDocumentId IN :contentDocumentIdList ORDER BY CreatedDate DESC LIMIT 1];
        
        return cvObjList;
       
    }
}