force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Signatory__mdt/Bank_Signatory__mdt.object-meta.xml
<CustomObject>
    <label>Bank Signatory</label>
    <pluralLabel>Bank Signatorys</pluralLabel>
</CustomObject>

force-app/main/default/objects/Bank_Signatory__mdt/fields/Group_Id__c.field-meta.xml
<CustomField>
    <fullName>Group_Id__c</fullName>
    <label>Group Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Signatory__mdt/fields/Name_of_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Name_of_Signatory__c</fullName>
    <label>Name of Signatory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Signatory__mdt/fields/Order_Of_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Order_Of_Signatory__c</fullName>
    <label>Order Of Signatory</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <formula>IF( NOT(ISBLANK(First_Name__c)) , First_Name__c, &apos;&apos;) + &apos; &apos; + IF( NOT(ISBLANK(Middle_Name__c)) , Middle_Name__c, &apos;&apos;) + &apos; &apos; + IF( NOT(ISBLANK(Last_Name__c)) , Last_Name__c, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Co-Applicant</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Leegality_Verification__c.field-meta.xml
<CustomField>
    <fullName>Leegality_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Leegality Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Leegality Verification)</relationshipLabel>
    <relationshipName>Loan_Applicants7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/DocumentId__c.field-meta.xml
<CustomField>
    <fullName>DocumentId__c</fullName>
    <label>DocumentId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failed_Reason__c</fullName>
    <label>Failed Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/recordTypes/Leegality.recordType-meta.xml
<RecordType>
    <fullName>Leegality</fullName>
    <active>true</active>
    <label>Leegality</label>
</RecordType>

force-app/main/default/classes/UB_LeegalityApi.cls
/**
* @File Name          : UB_LeegalityApi.cls
* @Description        : 
* @Author             :Zafaruddin
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         12-06-2024            Zafaruddin         Initial Version

**/


public with sharing class UB_LeegalityApi {

    UB_HTTPCalloutService service;

        /**
    * @author Zafaruddin | 06-05-2024  
    * @param loanApplicationId 
    **/

    @AuraEnabled
    public static Boolean legalityApiCall (Id loanApplicationId){        
        try {
            Verification__c verifyRecord = new Verification__c();
            List<Invitees> inviteesList = new List<Invitees>();
            UB_LeegalityApi leegalityApi = new UB_LeegalityApi();
            String accessToken = UB_GenerateAccessToken.getToken('Token_Generate_API');
            for(Loan_Applicant__c applicant : new UB_LoanApplicantsSelector().getApplicants(new Set<Id>{loanApplicationId},UB_ConstantsUtil.APPLICANT) ) {
                if(applicant.Email__c != NULL ) {
                    Invitees invitee = new Invitees();
                    invitee.name =   applicant.Applicant_Name__c;
                    invitee.email =  applicant.Email__c ;
                    invitee.phone =  applicant.Mobile__c;
                    inviteesList.add(invitee);
                }
            }
            for(Loan_Applicant__c applicant :  new UB_LoanApplicantsSelector().getApplicants(new Set<Id>{loanApplicationId},UB_ConstantsUtil.CO_APPLICANT)) {
                if(applicant.Email__c != NULL ) {
                    Invitees invitee = new Invitees();
                    invitee.name =   applicant.Applicant_Name__c;
                    invitee.email =  applicant.Email__c ;
                    invitee.phone =  applicant.Mobile__c;
                    inviteesList.add(invitee);
                }
            }
            for(Loan_Applicant__c applicant : new UB_LoanApplicantsSelector().getApplicants(new Set<Id>{loanApplicationId},UB_ConstantsUtil.GUATANTOR) ) {
                if(applicant.Email__c != NULL ) {
                    Invitees invitee = new Invitees();
                    invitee.name =   applicant.Applicant_Name__c;
                    invitee.email =  applicant.Email__c ;
                    invitee.phone =  applicant.Mobile__c;
                    inviteesList.add(invitee);
                }
            }
            System.debug('inviteesList  '+ JSON.serialize(inviteesList)  );
            List<Bank_Signatory__mdt> inviteeDetailList = [SELECT Id, Email__c, Group_Id__c, Group_Name__c, Name_of_Signatory__c, Order_Of_Signatory__c, Phone__c FROM Bank_Signatory__mdt];
            System.debug('inviteeDetailList META DATA>>'+ inviteeDetailList);
            if( !inviteeDetailList.isEmpty() ){
                for(Bank_Signatory__mdt bnkSigntry : inviteeDetailList){
                    Invitees signatory = new Invitees();
                    signatory.email=bnkSigntry.Email__c;
                    signatory.name = bnkSigntry.Name_of_Signatory__c;
                    signatory.groupId = bnkSigntry.Group_Id__c;
                    signatory.groupName = bnkSigntry.Group_Name__c;
                    inviteesList.add(signatory);
                }
            }
            System.debug('inviteesList UPDATEDDDDDDDDD '+ JSON.serialize(inviteesList)  );
            leegalityApi.service = new UB_HTTPCalloutService('Leegality_Api');
            leegalityApi.service.setHeaderParameter('Authorization', 'Bearer '+accessToken);
            // code to get LAF pdf base 64 againts application.
            PageReference PDf =  Page.CV_VehicleEquipment;
            PDf.getParameters().put('Id',loanApplicationId);
            PDf.setRedirect(false);
            Blob b = PDf.getContentAsPdf();
            List<String> base64 = new List<String>();
            base64.add(EncodingUtil.base64Encode(b));
            String RequestJson = '{"profileId":"4mcWfoO","file":{"name":"","fields":[{}],"additionalFiles": ' + JSON.serialize(base64,true) + ' },"invitees":' + JSON.serialize(inviteesList,true) + ',"irn":""}';
           
            System.debug('requestBodyXXXXXXXXXX  '+RequestJson);
            leegalityApi.service.setRequestBody(RequestJson);
            HTTPResponse responeObj = new HTTPResponse();
            responeObj = leegalityApi.service.sendRequest();
            System.debug('responeObj   '+responeObj);
            System.debug('STATUS CODE   '+responeObj.getStatusCode());
            String JSONResponse = responeObj.getBody();//res.getBody();
            List<Loan_Applicant__c> loanAppList = [SELECT Id FROM Loan_Applicant__c WHERE Loan_Application__c=:loanApplicationId AND Applicant_Type__c=:UB_ConstantsUtil.APPLICANT];
            if(responeObj.getStatusCode() == 200) {
                Map<String,Object> ResponseMap = (Map<String,Object>)JSON.deserializeUntyped(JSONResponse);
                System.debug('ResponseMap  '+ResponseMap);
                if(ResponseMap.get('data') != NULL) {
                    ResponseMap =   (Map<String,Object>)ResponseMap.get('data') ;
                    System.debug('ResponseMap   1111 '+ResponseMap);
                    verifyRecord = UB_CommonUtil.createVerfication(loanAppList[0].Id, UB_ConstantsUtil.LEEGALITY_VERIFICATION_RECORD_TYPE,UB_ConstantsUtil.COMPLETEDSTATUS);
                    verifyRecord.DocumentId__c = String.valueOf(ResponseMap.get('documentId'));
                }

            } else {
                verifyRecord = UB_CommonUtil.createVerfication(loanAppList[0].Id, UB_ConstantsUtil.LEEGALITY_VERIFICATION_RECORD_TYPE,UB_ConstantsUtil.FAILED_STATUS);
                verifyRecord.Failed_Reason__c = JSONResponse  ;
            }
            insert verifyRecord;
            System.debug('verifyRecord  '+verifyRecord);
            update new Loan_Applicant__c(Id = loanAppList[0].Id, Leegality_Verification__c = verifyRecord.Id);
            system.debug('JSONResponse>> '+JSONResponse);
            system.debug('JSONResponse>> LENGTH '+RequestJson.length());
            //When Request Length > 131072
            if(RequestJson.length() > 131072) {
                RequestJson =  RequestJson.substring(0,131072);
                System.debug('jsonRequestBody  jsonRequestBody   '+RequestJson);
            } 

            API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                leegalityApi.service.getEndpointURL(), 
                String.valueOf(leegalityApi.service.getHeaderParameters()), 
                leegalityApi.service.getRequestMethod(), 
                RequestJson, 
                JSONResponse, 
                responeObj.getStatusCode(), 
                UB_LeegalityApi.class.getName(), 
                loanAppList[0].Id, 
                Id.valueOf(loanAppList[0].Id).getSObjectType().getDescribe().getName(), 
                UB_ConstantsUtil.REST_API_TYPE,
                'LEEGALITY API',
                UB_ConstantsUtil.LOB_CV
                );
            if(apiLogger != NULL) {
                insert apiLogger;
                System.debug('apiLogger  '+apiLogger);
            } 

            return true;
            
        }catch(Exception e) {
            System.debug('Exception@@'+e.getMessage());
            System.debug('Exception@@ LINEEEEEE  '+e.getLineNumber());
            UB_CommonUtil.createExceptionLogRecord(e, UB_ConstantsUtil.LOB_CV);
        } 

        return false;
    }

    public class Invitees {
        public String name;
        public String email;
        public String phone;
        public String groupId;
        public String groupName;
    }


}