force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Aadhaar_Verification__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aadhaar Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Aadhar Verification)</relationshipLabel>
    <relationshipName>Loan_Applicants2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Cibil_Verification__c.field-meta.xml
<CustomField>
    <fullName>Cibil_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cibil Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Cibil Verification)</relationshipLabel>
    <relationshipName>Loan_Applicants3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/CIF__c.field-meta.xml
<CustomField>
    <fullName>CIF__c</fullName>
    <label>CIF</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Date_Of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Incorporation__c</fullName>
    <label>Date Of Incorporation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Dedupe_Verification__c.field-meta.xml
<CustomField>
    <fullName>Dedupe_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dedupe Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Dedupe Verification)</relationshipLabel>
    <relationshipName>Loan_Applicants1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Pan_Number__c.field-meta.xml
<CustomField>
    <fullName>Pan_Number__c</fullName>
    <label>Pan Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/UCID__c.field-meta.xml
<CustomField>
    <fullName>UCID__c</fullName>
    <label>UCID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Messages_Config__mdt/Messages_Config__mdt.object-meta.xml
<CustomObject>
    <label>Messages Config</label>
    <pluralLabel>Messages Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Aadhaar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Number__c</fullName>
    <inlineHelpText>Masked Aadhaar Number via API</inlineHelpText>
    <label>Aadhaar Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Dedupe_Address__c.field-meta.xml
<CustomField>
    <fullName>Dedupe_Address__c</fullName>
    <label>Address From CBS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Dedupe_Response_Id__c.field-meta.xml
<CustomField>
    <fullName>Dedupe_Response_Id__c</fullName>
    <label>Dedupe Response Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Dedupe_Status__c.field-meta.xml
<CustomField>
    <fullName>Dedupe_Status__c</fullName>
    <label>Dedupe Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MATCH FOUND</fullName>
            </value>
            <value>
                <fullName>NO MATCH FOUND</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failed_Reason__c</fullName>
    <label>Failed Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>OTP Sent</fullName>
            </value>
            <value>
                <fullName>OTP Attempt Failed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/UCID__c.field-meta.xml
<CustomField>
    <fullName>UCID__c</fullName>
    <label>UCID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_DedupeApi.cls
/**
* @File Name          : UB_DedupeApi.cls
* @Description        : 
* @Author             :Zafaruddin
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         01-04-2024            Zafaruddin         Initial Version

**/

public class UB_DedupeApi {
    
    UB_HTTPCalloutService service;

    
    /**
    * @description method will check dedupe based on Pan,Aadhar and DOB and return response data on verification Object.
    * @author ChangeMeIn@UserSettingsUnder.SFDoc | 04-15-2024 
    * @param customerId 
    * @param accessToken 
    **/
    @future(callout = true)
    public static void checkDedupe (Id customerId, String accessToken){
        Savepoint sp;
        String maskAadhar;
        String unMaskAadhar;
        String Endpoint ;
        Verification__c verifyRecord = new Verification__c();
        Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('ReadTimeOutIssue');
        List<Loan_Applicant__c> loanAppList = new UB_LoanApplicantsSelector().selectById(new Set<Id>{customerId});
        try{
            Date dob;
            System.debug('loanAppList  '+loanAppList);
            if((loanAppList[0].RecordTypeId == UB_ConstantsUtil.INDIVIDUAL_APPICANT_RECORD_TYPE || loanAppList[0].RecordTypeId == BL_ConstantsUtil.BL_INDIVIDUAL_APPICANT_RECORD_TYPE) && loanAppList[0].Date_of_Birth__c != null){
                dob = loanAppList[0].Date_of_Birth__c;
            } else if((loanAppList[0].RecordTypeId == UB_ConstantsUtil.NON_INDIVIDUAL_APPICANT_RECORD_TYPE || loanAppList[0].RecordTypeId == BL_ConstantsUtil.BL_NON_INDIVIDUAL_APPICANT_RECORD_TYPE) && loanAppList[0].Date_Of_Incorporation__c != null) {
                dob = loanAppList[0].Date_Of_Incorporation__c;
            }
            System.debug('dobdobdob  '+dob);
            System.debug('loanAppList  '+loanAppList);
            UB_DedupeApi dedupeApi = new UB_DedupeApi();
            dedupeApi.service = new UB_HTTPCalloutService('Dedupe_Api');
            dedupeApi.service.setHeaderParameter('Authorization', 'Bearer '+accessToken);
            System.debug('Header VALUESS '+dedupeApi.service.getHeaderParameters());
            dedupeApi.service.setURLParameter('transactionDateTime', Datetime.now().formatGMT('YYYYMMddHHmmss'));
            dedupeApi.service.setURLParameter('PAN', String.isNotBlank(loanAppList[0].Pan_Number__c) ? loanAppList[0].Pan_Number__c : '');
            dedupeApi.service.setURLParameter('DOB', dob != NULL ? UB_CommonUtil.dateFormatter(dob) : '');
            System.debug('loanAppList[0].Aadhaar_Verification__c  '+loanAppList[0].Aadhaar_Verification__c);
            if(loanAppList[0].Aadhaar_Verification__c != NULL  ) {
                List<Verification__c> verificationList = new UB_VerificationsSelector().selectById(new Set<Id>{loanAppList[0].Aadhaar_Verification__c});
                if( String.isNotBlank( verificationList[0].Aadhaar_Number__c)) {
                    maskAadhar = verificationList[0].Aadhaar_Number__c;
                    System.debug('MASK Aaadhar NUmber   '+maskAadhar);
                    unMaskAadhar = UB_Aadhaar_API.aadhaarNumberUnmasking(verificationList[0].Aadhaar_Number__c);
                    System.debug('Real Aadhar Number  '+unMaskAadhar);
                    dedupeApi.service.setURLParameter('AADHAAR', String.isNotBlank(unMaskAadhar) ? unMaskAadhar : '');
                }
            }
            System.debug('URL VALUEEEEE  '+dedupeApi.service.getURLParameters());
            HttpResponse response = dedupeApi.service.sendRequest() ;
            sp = Database.setSavepoint();
            System.debug('RESPONSEEEEEEEE  '+response);
            system.debug('Response Body - ' + response.getBody());
            if(response.getStatusCode() == 200) {
                verifyRecord = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.DEDUPE_VERIFICATION_RECORD_TYPE,UB_ConstantsUtil.COMPLETEDSTATUS);
                map<string,object> mapJSONResponse = (Map<String, object>) JSON.deserializeUntyped(response.getBody());
                system.debug('#@ '+mapJSONResponse.get('ResponseMessage'));
                system.debug('@#mapJSONResponse '+mapJSONResponse);
                mapJSONResponse = (Map<String, object>) mapJSONResponse.get('ResponseMessage');
                system.debug('mapJSONResponse ResponseMessage>>>>>'+ mapJSONResponse);
                mapJSONResponse = (Map<String, object>) mapJSONResponse.get('Payload');
                system.debug(' mapJSONResponse Payload>>>>>' + mapJSONResponse);
               // System.debug('mapJSONResponse.Status '+mapJSONResponse.get('Status'));
                //System.debug('mapJSONResponse.Status '+mapJSONResponse.get('RESPONSE_ID'));
                if(mapJSONResponse.get('Status') != NULL) {
                	verifyRecord.Dedupe_Status__c =  (String.ValueOf(mapJSONResponse.get('Status'))).toUppercase();
                    verifyRecord.Dedupe_Response_Id__c =  (String.ValueOf(mapJSONResponse.get('RESPONSE_ID')));

                } else if(mapJSONResponse.get('Status') == NULL) {
                    verifyRecord.Status__c = UB_ConstantsUtil.FAILED_STATUS;
                }
                mapJSONResponse = (Map<String, object>) mapJSONResponse.get('DECUST');
                System.debug('mapJSONResponse DECUST  '+mapJSONResponse);
                if(mapJSONResponse != NULL && mapJSONResponse.containsKey('Record') && mapJSONResponse.get('Record') != NULL) {
                       mapJSONResponse = (Map<String, object>) mapJSONResponse.get('Record');
                       verifyRecord.CIF__c = String.valueOf(mapJSONResponse.get('cif'));
                       verifyRecord.Dedupe_Address__c = String.valueOf(mapJSONResponse.get('address1'));
                       //verifyRecord.Dedupe_Response_Id__c = String.valueOf(mapJSONResponse.get('RESPONSE_ID'));
                       verifyRecord.UCID__c =  String.valueOf(mapJSONResponse.get('ucid'));
                } 
                
                if(verifyRecord != NULL) {
                    insert verifyRecord;
                    System.debug('verifyRecord  '+verifyRecord);
                    update new Loan_Applicant__c(Id = customerId, Dedupe_Verification__c = verifyRecord.Id, CIF__c=verifyRecord.CIF__c,UCID__c=verifyRecord.UCID__c);
                }
            } else {
                verifyRecord = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.DEDUPE_VERIFICATION_RECORD_TYPE,UB_ConstantsUtil.FAILED_STATUS);
                verifyRecord.Failed_Reason__c = messageConfigMap.get('Read_Time_Out_Api_Issue').Message__c;
                insert verifyRecord;
                update new Loan_Applicant__c(Id = customerId, Cibil_Verification__c = verifyRecord.Id);

            }
            Endpoint = dedupeApi.service.getEndpointURL();
            if(unMaskAadhar != NULL && Endpoint.contains(unMaskAadhar)) {
                Endpoint  = Endpoint.replace(unMaskAadhar,maskAadhar);
                SYstem.debug('Endpoint  '+Endpoint);
            }
            API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                Endpoint, 
                String.valueOf(dedupeApi.service.getHeaderParameters()), 
                dedupeApi.service.getRequestMethod(), 
                '', 
                response.getBody(), 
                response.getStatusCode(), 
                UB_DedupeApi.class.getName(), 
                customerId, 
                Id.valueOf(customerId).getSObjectType().getDescribe().getName(), 
                UB_ConstantsUtil.REST_API_TYPE,
                'DEDUPE API',
                loanAppList[0].Loan_Application__r.LOB__c
                );
            if(apiLogger != NULL) {
                insert apiLogger;
                System.debug('apiLogger  '+apiLogger);
            }
        }catch(System.CalloutException e) {
            System.debug('Exception@@'+e.getMessage());
            System.debug('Exception@@ LINEEEEEE  '+e.getLineNumber());
            verifyRecord = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.DEDUPE_VERIFICATION_RECORD_TYPE,UB_ConstantsUtil.FAILED_STATUS);
            verifyRecord.Failed_Reason__c = messageConfigMap.get('Read_Time_Out_Api_Issue').Message__c;
            insert verifyRecord;
            update new Loan_Applicant__c(Id = customerId, Dedupe_Verification__c = verifyRecord.Id);
            UB_CommonUtil.createExceptionLogRecord(e, loanAppList[0].Loan_Application__r.LOB__c);            
        }
        catch(Exception e) {
            //Database.rollback(sp);
            System.debug('Exception@@11111'+e.getMessage());
            System.debug('Exception@@ LINEEEEEE11111  '+e.getLineNumber());
            UB_CommonUtil.createExceptionLogRecord(e, loanAppList[0].Loan_Application__r.LOB__c);
        }
    }
    


}