force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/BL_URC__c.field-meta.xml
<CustomField>
    <fullName>BL_URC__c</fullName>
    <label>URC Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Udyam_Verification__c.field-meta.xml
<CustomField>
    <fullName>Udyam_Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Udyam Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Loan Applicants (Udyam Verification)</relationshipLabel>
    <relationshipName>Udyam_Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/PSL_Category__c.field-meta.xml
<CustomField>
    <fullName>PSL_Category__c</fullName>
    <label>PSL Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PSL_Non_PSL__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture (1000)</fullName>
            </value>
            <value>
                <fullName>MSME (2000)</fullName>
            </value>
            <value>
                <fullName>Export Credit (3000)</fullName>
                <label>Export Credit (3000</label>
            </value>
            <value>
                <fullName>Education Loans (4000)</fullName>
            </value>
            <value>
                <fullName>Non PSL (9000)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Messages_Config__mdt/Messages_Config__mdt.object-meta.xml
<CustomObject>
    <label>Messages Config</label>
    <pluralLabel>Messages Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Failed_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failed_Reason__c</fullName>
    <label>Failed Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification_Line_Item__c/Verification_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Verification Line Item</description>
    <label>Verification Line Item</label>
    <nameField>
        <displayFormat>VLI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verification Line Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification_Line_Item__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verification Line Items</relationshipLabel>
    <relationshipName>Verification_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification_Line_Item__c/fields/PSL_Category__c.field-meta.xml
<CustomField>
    <fullName>PSL_Category__c</fullName>
    <label>PSL Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PSL</fullName>
            </value>
            <value>
                <fullName>Non-PSL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification_Line_Item__c/fields/PSL_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>PSL_Sub_Category__c</fullName>
    <label>PSL Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manufacture of food products</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification_Line_Item__c/fields/PSL_Sub_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>PSL_Sub_Sub_Category__c</fullName>
    <label>PSL Sub-Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manufacture of other food products n.e.c.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification_Line_Item__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Verification Line Items</relationshipLabel>
    <relationshipName>Verification_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_Udyam_API.cls
/**
* @File Name          : UB_Udyam_API.cls
* @Description        : This API is used to fetch Udyam for the non-individual customer.
* @Author             : Mohit Saxena
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         15-07-2024               Mohit Saxena          Initial Version
*/
public class UB_Udyam_API {
    UB_HTTPCalloutService service;
    
    public static void fetchPdfData (Id customerId, String accessToken){
        Map<String,Messages_Config__mdt> errorMessageConfigMap = UB_CommonUtil.getMessageRecord('GenericErrorMessage');
        List<Verification__c> insertRecords = new List<Verification__c>();
        List<API_Logger__c> createLogList = new List<API_Logger__c>();
        List<Loan_Applicant__c> loanAppList = new UB_LoanApplicantsSelector().selectById(new Set<Id>{customerId});
        List<Verification_Line_Item__c> insertLineItemRecords = new List<Verification_Line_Item__c>();

        //Savepoint sp = Database.setSavepoint();
        try{
            if(String.isNotBlank(accessToken)){
                UB_Udyam_API udyamAPI = new UB_Udyam_API();
                udyamAPI.service = new UB_HTTPCalloutService('Udyam_API');
                
                JSONGenerator gen = JSON.createGenerator(true);
                gen.writeStartObject();
                gen.writeStringField('consent','Y');
                gen.writeStringField('udyamRegistrationNo',loanAppList[0].BL_URC__c);
                gen.writeStringField('isPDFRequired','Y');
                gen.writeStringField('getEnterpriseDetails','Y');
                gen.writeFieldName('clientData');
                gen.writeStartObject();
                //gen.writeStringField('caseId',loanAppList[0].Id);
                gen.writeStringField('caseId','123456');
                gen.writeEndObject();
                gen.writeEndObject();
                
                udyamAPI.service.setHeaderParameter('Authorization','Bearer '+accessToken);
                udyamAPI.service.setRequestBody(gen.getAsString());        
                HttpResponse response = new HttpResponse(); 
                if(udyamAPI.service.calloutMetadata.Active__c){
                    response = udyamAPI.service.sendRequest();
                }else{
                    response.setStatusCode(200);
                    response.setBody(udyamAPI.service.calloutMetadata.Mock_Response__c);
                } 
                Verification__c verify = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.UDYAM_VERIFICATION_RECORD_TYPE, UB_ConstantsUtil.COMPLETEDSTATUS);
                if(response.getStatusCode() == 200){
                    Map<String,Object> mapResponseResult = (Map<String,Object>) JSON.deserializeUntyped(response.getBody());
                    if(mapResponseResult.keySet().size() > 0 && mapResponseResult.containsKey('result')){
                        Map<String,Object> mapResponseBody = (Map<String,Object>) (mapResponseResult.get('result'));
                        if(mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('pdfData')){
                            Blob blobContent = EncodingUtil.base64Decode((String) String.valueOf(mapResponseBody.get('pdfData')));
                            UB_CommonUtil.createDocument('Udyam Certificate', 'Udyam Certificate.pdf', blobContent, loanAppList[0].Loan_Application__c, loanAppList[0].Id, 'Udyam Certificate', null);
                        }
                        if(mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('industry')){
                            List<Object> industryList = (List<Object>) (mapResponseBody.get('industry'));
                            if(!industryList.isEmpty() && industryList.size() > 0){
                                for(Object obj : industryList){
                                    Verification_Line_Item__c lineItem = new Verification_Line_Item__c();
                                    lineItem.RecordTypeId      = UB_ConstantsUtil.UDYAM_PSL_VERIFY_LINE_ITEM_RECORD_TYPE;
                                    lineItem.PSL_Category__c   = UB_ConstantsUtil.PSL_CATEGORY;
                                    lineItem.Loan_Applicant__c = customerId;
                                    Map<String,Object> mapIndustryData = (Map<String,Object>) obj;
                                    if(mapIndustryData.containsKey('industry')){
                                        lineItem.PSL_Sub_Category__c = (String) String.valueOf(mapIndustryData.get('industry'));
                                    }
                                    if(mapIndustryData.containsKey('subSector')){
                                        lineItem.PSL_Sub_Sub_Category__c = (String) String.valueOf(mapIndustryData.get('subSector'));
                                    }
                                    insertLineItemRecords.add(lineItem);
                                }
                            }
                        }
                    }
                }
                insertRecords.add(verify); 
                
                API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                    udyamAPI.service.getEndpointURL(), 
                    String.valueOf(udyamAPI.service.getHeaderParameters()), 
                    udyamAPI.service.getRequestMethod(), 
                    gen.getAsString(), 
                    response.getBody(), 
                    response.getStatusCode(), 
                    UB_Udyam_API.class.getName(), 
                    customerId, 
                    Id.valueOf(customerId).getSObjectType().getDescribe().getName(), 
                    UB_ConstantsUtil.REST_API_TYPE,
                    'Udyam API',
                    loanAppList[0].Loan_Application__r.LOB__c
                );
                createLogList.add(apiLogger);
                if(!createLogList.isEmpty() && createLogList.size() > 0){
                    // Set up the unit of work
                    fflib_ISObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(new List<Schema.SObjectType>{API_Logger__c.sObjectType});
                    uow.registerNew(createLogList);
                    // Commit all of the work at a safe moment
                    uow.commitWork();
                }
            }
        }catch(Exception e) {
            //Database.rollback(sp);
            //Database.releaseSavepoint(sp);
            Verification__c verify = UB_CommonUtil.createVerfication(customerId, UB_ConstantsUtil.UDYAM_VERIFICATION_RECORD_TYPE, UB_ConstantsUtil.FAILED_STATUS);
            verify.Failed_Reason__c = e.getMessage();
            insertRecords.add(verify); 
            System.debug('Exception@@'+e.getMessage());
            UB_CommonUtil.createExceptionLogRecord(e, loanAppList[0].Loan_Application__r.LOB__c);
        }
        
        if(!insertRecords.isEmpty() && insertRecords.size() > 0){
            insertRecords = UB_VerificationUtility.insertRecords(insertRecords);
            UB_LoanApplicantUtility.updateRecords(new List<Loan_Applicant__c>{new Loan_Applicant__c(Id = customerId, Udyam_Verification__c = insertRecords[0].Id)});
            if(!insertLineItemRecords.isEmpty() && insertLineItemRecords.size() > 0){
                for(Verification_Line_Item__c obj : insertLineItemRecords){
                    obj.Verification__c = insertRecords[0].Id;
                }
                insert insertLineItemRecords;
            }
        }
    }
}