force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Co-Applicant</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reject_Reason_Master__mdt/Reject_Reason_Master__mdt.object-meta.xml
<CustomObject>
    <label>Reject Reason Master</label>
    <pluralLabel>Reject Reason Master</pluralLabel>
</CustomObject>

force-app/main/default/objects/Reject_Reason_Master__mdt/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BL</fullName>
                <default>true</default>
                <label>BL</label>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_SmsApi.cls
/**
* @File Name          : UB_SmsApi.cls
* @Description        : 
* @Author             :Zafaruddin
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         15-07-2024            Zafaruddin         Initial Version

**/

public with sharing class UB_SmsApi {

    UB_HTTPCalloutService service;

        /**
    * @description  Funtion will invoke from flow whenever Lead/Loan status got rejeted. 
    * @author Zafaruddin | 15-07-2024  
    * @param recordId 
    **/
    @InvocableMethod(label='SMS API Invoke' description='Method used for calling SMS Api')
    public static void initiateSmsApi(List<Id> recordId) {
        System.debug('recordIdrecordIdrecordIdrecordId  '+recordId);
        if(recordId != NULL && recordId.size()>0){     
             UB_SmsApi.sendSmsToCustomer(recordId[0]);
        }
    }  

        
    /**
    * @description  Funtion will Call SMS APi 
    * @author Zafaruddin | 15-07-2024  
    * @param recordId 
    **/
    public static void sendSmsToCustomer (Id recordId){
        String lob='';
        String Mobile;
        List<Loan_Applicant__c> loanAppList  = new List<Loan_Applicant__c>();
        try {
            String sObjName = recordId.getSObjectType().getDescribe().getName();
            System.debug('sObjName  '+sObjName);
            if(sObjName == 'Lead__c') {
                List<Lead__c> leadList =   new UB_LeadsSelector().selectById(new Set<Id>{recordId});
                System.debug('leadList   '+leadList);
                Mobile = leadList[0].Mobile_Number__c;
                lob = leadList[0].LOB__c;
            } else {
                loanAppList = [SELECT Id,Mobile__c,Loan_Application__r.LOB__c FROM Loan_Applicant__c WHERE Loan_Application__c=:recordId AND Applicant_Type__c=:UB_ConstantsUtil.APPLICANT] ;
                Mobile = loanAppList[0].Mobile__c;
                System.debug('loanAppList   '+loanAppList);
                lob = loanAppList[0].Loan_Application__r.LOB__c;
            }
            System.debug('MobileMobile  '+Mobile);
            Reject_Reason_Master__mdt rejectMdt = [SELECT Id,TemplateId__c FROM Reject_Reason_Master__mdt WHERE LOB__c=:lob LIMIT 1];
            System.debug('rejectMdt  '+rejectMdt);
            UB_SmsApi smsApi = new UB_SmsApi();
            String accessToken = UB_GenerateAccessToken.getToken('Token_Generate_API');
            smsApi.service = new UB_HTTPCalloutService('SMS_Api');
            smsApi.service.setHeaderParameter('Authorization', 'Bearer '+accessToken);
            // passing hard coded value as for now we don't have template code.
            String requestJson = '{"RequestMessage":{"Header":{"PartnerID":"' + smsApi.service.getExtraParameter('PartnerID') + '","TraceId ":"' + smsApi.service.getExtraParameter('TraceId') +  '","JwtAuthToken":"'  + smsApi.service.getExtraParameter('JwtAuthToken') + '","SendDateTime":"'  + smsApi.service.getExtraParameter('SendDateTime') +  '","RemoteIPAddress":"' + smsApi.service.getExtraParameter('RemoteIPAddress') + '"},"Payload":{"SMSData":{"RECIPIENT_MOBILE_NUMBER":"' + Mobile +   '","RECIPIENT_EMAIL_ID":"","OTP_CODE":"","OTP_REFRENCE_NUMBER":"","TEMPLATE_CODE":"' + smsApi.service.getExtraParameter('TEMPLATE_CODE') +  '","HMAC":"","REMARKS":"102","BENEFICIARY_NAME":"","BENEFICIARY_ACCOUNT_NUMBER":"","COOLING_PERIOD_TIME":"","BENE_FULL_NAME":"","LIMIT":"","PAYEE_ACCT_NO":"","TRANSFER_AMOUNT":"","LINK":"","SAVINGS_ACCT_NO":"","MESSAGE_ID":"","DEBIT_CARD_NO":"","PERSONAL_LOAN_APL_NO":"","LOAN_AMOUNT":""}}}}';
            System.debug('requestJson   '+requestJson);

            smsApi.service.setRequestBody(requestJson);
            HTTPResponse responeObj = new HTTPResponse();
            responeObj = smsApi.service.sendRequest();
            System.debug('responeObj   '+responeObj);
            system.debug( 'RESPONSE BODY - ' + responeObj.getBody());
            API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                smsApi.service.getEndpointURL(), 
                String.valueOf(smsApi.service.getHeaderParameters()), 
                smsApi.service.getRequestMethod(), 
                requestJson, 
                responeObj.getBody(), 
                responeObj.getStatusCode(), 
                UB_SmsApi.class.getName(), 
                recordId, 
                Id.valueOf(recordId).getSObjectType().getDescribe().getName(), 
                UB_ConstantsUtil.REST_API_TYPE,
                'SMS API',
                lob
                );
            if(apiLogger != NULL) {
                insert apiLogger;
                System.debug('apiLogger  '+apiLogger);
            } 
        } catch(Exception e) {
            System.debug('Exception--->'+e.getMessage());
            System.debug('ERROR LINE NUMBER--->'+e.getLineNumber());
            // call method to create ExceptionLogRecord
            UB_CommonUtil.createExceptionLogRecord(e, lob);
        }

    }
}