force-app/main/default/objects/Disbursement__c/Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_Questionnaire__c/Health_Questionnaire__c.object-meta.xml
<CustomObject>
    <label>Health Questionnaire</label>
    <nameField>
        <displayFormat>QN-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Questionnaires</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_Questionnaire__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>Disbursement__c</referenceTo>
    <relationshipLabel>Health Questionnaires</relationshipLabel>
    <relationshipName>Health_Questionnaires</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UB_HealthQuestionnaireSelector.cls
/**
* @File Name          : UB_HealthQuestionnaireSelector.cls
* @Description        : This class used to fetch/query health questions based on conditions.
* @Author             : Deepak Joshi
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         26-07-2024              Umair Ahmad            Initial Version
*/
public class UB_HealthQuestionnaireSelector extends fflib_SObjectSelector{
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Health_Questionnaire__c.Id
                };
                    }
    
    
    public Schema.SObjectType getSObjectType(){
        return Health_Questionnaire__c.sObjectType;
    }
    
    public List<Health_Questionnaire__c> getHealthQuestionsByDisbIds(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        
        query.setCondition('Disbursement__c IN: recordIds');
        
        system.debug('Health_Questionnaire__c query==> '+query.toSOQL());
        return (List<Health_Questionnaire__c>) Database.query(query.toSOQL());
    }
}