force-app/main/default/objects/Disbursement__c/Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Disbursement__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/First_EMI_Date__c.field-meta.xml
<CustomField>
    <fullName>First_EMI_Date__c</fullName>
    <label>First EMI Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Last_Emi_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Emi_Date__c</fullName>
    <label>Last Emi Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Processing_Fee__c.field-meta.xml
<CustomField>
    <fullName>Processing_Fee__c</fullName>
    <label>Processing Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Repayment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Mode__c</fullName>
    <label>Repayment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standing Instructions</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>PDC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Tenure</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Credit_Shield_Premium__c.field-meta.xml
<CustomField>
    <fullName>Credit_Shield_Premium__c</fullName>
    <label>Credit Shield Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Is_Asset_Registrable__c.field-meta.xml
<CustomField>
    <fullName>Is_Asset_Registrable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Asset Registrable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Margin_Money__c.field-meta.xml
<CustomField>
    <fullName>Margin_Money__c</fullName>
    <label>Margin Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Tenure (In Month Per Vehicle)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Cost__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Cost__c</fullName>
    <label>Vehicle Cost (Per Vehicle)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Master</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Master</label>
    <nameField>
        <displayFormat>VM-{00000}</displayFormat>
        <label>Vehicle Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/UB_DisbursementsSelector.cls
/**
* @File Name          : UB_DisbursementsSelector.cls
* @Description        : This class used to fetch/query Disbursement based on conditions.
* @Author             : Deepak Joshi
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         22-07-2024              Umair Ahmad            Initial Version
*/
public class UB_DisbursementsSelector extends fflib_SObjectSelector{
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Disbursement__c.Loan_Application__c,
                Disbursement__c.Tenure__c,
                Disbursement__c.Loan_Amount__c,
                Disbursement__c.Loan_Application__c,
                Disbursement__c.EMI_Amount__c,
                Disbursement__c.First_EMI_Date__c,
                Disbursement__c.Last_Emi_Date__c,
                Disbursement__c.Processing_Fee__c,
                Disbursement__c.Repayment_Mode__c,
                Disbursement__c.ROI__c
                };
                    }
    
    
    public Schema.SObjectType getSObjectType(){
        return Disbursement__c.sObjectType;
    }
    
    public List<Disbursement__c> getDisbursementRecordsByIds(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        
        query.setCondition('Id IN: recordIds');
        query.selectField('Vehicle__r.Name');
        query.selectField('Vehicle__r.Make__c');
        query.selectField('Vehicle__r.Model__c');
        query.selectField('Vehicle__r.Is_Asset_Registrable__c');
        query.selectField('Vehicle__r.Vehicle_Cost__c');
        query.selectField('Vehicle__r.Margin_Money__c');
        query.selectField('Vehicle__r.Credit_Shield_Premium__c');
        query.selectField('Vehicle__r.Vehicle_Master__r.Vehicle_Type__c');
        system.debug('Disbursement__c query==> '+query.toSOQL());
        return (List<Disbursement__c>) Database.query(query.toSOQL());
    }
}