force-app/main/default/objects/Disbursement__c/Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Disbursement__c/fields/Insurance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Amount__c</fullName>
    <label>Insurance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Disbursement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Aadhaar_Number__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_Number__c</fullName>
    <inlineHelpText>Masked Aadhaar Number via API</inlineHelpText>
    <label>Aadhaar Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Aadhaar_OTP_Request_ID__c.field-meta.xml
<CustomField>
    <fullName>Aadhaar_OTP_Request_ID__c</fullName>
    <label>Aadhaar OTP Request ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Annual_Premium_With_Tax__c.field-meta.xml
<CustomField>
    <fullName>Annual_Premium_With_Tax__c</fullName>
    <label>Annual Premium With Tax</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Base_Premium__c.field-meta.xml
<CustomField>
    <fullName>Base_Premium__c</fullName>
    <label>Base Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/BRE_Decision__c.field-meta.xml
<CustomField>
    <fullName>BRE_Decision__c</fullName>
    <label>BRE Decision</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/CFR_Fraud_Information__c.field-meta.xml
<CustomField>
    <fullName>CFR_Fraud_Information__c</fullName>
    <label>CFR Fraud Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>Disbursement__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/ICICI_Partner_URL__c.field-meta.xml
<CustomField>
    <fullName>ICICI_Partner_URL__c</fullName>
    <label>ICICI Partner URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Insurance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Amount__c</fullName>
    <label>Insurance Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Is_Medical__c.field-meta.xml
<CustomField>
    <fullName>Is_Medical__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Medical</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Is_Report_available__c.field-meta.xml
<CustomField>
    <fullName>Is_Report_available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Report available ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Modal_Premium__c.field-meta.xml
<CustomField>
    <fullName>Modal_Premium__c</fullName>
    <label>Modal Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Perfios_API_Status__c.field-meta.xml
<CustomField>
    <fullName>Perfios_API_Status__c</fullName>
    <label>Perfios Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COMPLETED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>ERROR_USER</fullName>
            </value>
            <value>
                <fullName>ERROR_SITE</fullName>
            </value>
            <value>
                <fullName>ERROR_SESSION_EXPIRED</fullName>
            </value>
            <value>
                <fullName>CANCELLED</fullName>
            </value>
            <value>
                <fullName>REJECTED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Perfios_Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Perfios_Transaction_Id__c</fullName>
    <label>Perfios Transaction Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Premium_Paying_Term__c.field-meta.xml
<CustomField>
    <fullName>Premium_Paying_Term__c</fullName>
    <label>Premium Paying Term</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Response_Remarks__c.field-meta.xml
<CustomField>
    <fullName>Response_Remarks__c</fullName>
    <label>Response_Remarks</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Sherlock_Case_Id__c.field-meta.xml
<CustomField>
    <fullName>Sherlock_Case_Id__c</fullName>
    <label>Sherlock Case Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/SherLock_Status__c.field-meta.xml
<CustomField>
    <fullName>SherLock_Status__c</fullName>
    <label>SherLock Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>REFER</fullName>
            </value>
            <value>
                <fullName>REJECT</fullName>
            </value>
            <value>
                <fullName>IN PROCESS</fullName>
            </value>
            <value>
                <fullName>API FAILED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>OTP Sent</fullName>
            </value>
            <value>
                <fullName>OTP Attempt Failed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Total_First_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_First_Premium__c</fullName>
    <label>Total First Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Total_First_Premium_Show__c.field-meta.xml
<CustomField>
    <fullName>Total_First_Premium_Show__c</fullName>
    <label>Total First Premium Show</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Transaction_Id__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Id__c</fullName>
    <label>Transaction Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_VerificationsSelector.cls
/**
* @File Name          : UB_LeadsSelector.cls
* @Description        : This class used to fetch/query Verification records based on conditions.
* @Author             : Mohit
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         04-04-2024               Mohit                 Initial Version
*/
public class UB_VerificationsSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Verification__c.Id,
            Verification__c.RecordTypeId,
            Verification__c.Aadhaar_OTP_Request_ID__c,
            Verification__c.Status__c,
            Verification__c.Loan_Applicant__c,
            Verification__c.Sherlock_Case_Id__c,
            Verification__c.SherLock_Status__c,
            Verification__c.Aadhaar_Number__c,
            Verification__c.Perfios_API_Status__c,
            Verification__c.Is_Report_available__c,
            Verification__c.Perfios_Transaction_Id__c,
            Verification__c.Annual_Premium_With_Tax__c,
            Verification__c.BRE_Decision__c,
            Verification__c.Base_Premium__c,
            Verification__c.ICICI_Partner_URL__c,
            Verification__c.Insurance_Amount__c,
            Verification__c.Is_Medical__c,
            Verification__c.Modal_Premium__c,
            Verification__c.Premium_Paying_Term__c,
            Verification__c.Response_Remarks__c,
            Verification__c.Total_First_Premium_Show__c,
            Verification__c.Total_First_Premium__c,
            Verification__c.Transaction_Id__c
        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Verification__c.sObjectType;
    }
   
    public List<Verification__c> selectById(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN : recordIds');
        query.selectField('Loan_Applicant__r.Loan_Application__r.LOB__c');
        return (List<Verification__c>) Database.query(query.toSOQL());
    }
    
    public List<Verification__c> selectByIdWithParentInfo(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        fflib_SObjectSelector loanApplicantsSelector = new UB_LoanApplicantsSelector();
        loanApplicantsSelector.configureQueryFactoryFields(query, 'Loan_Applicant__r');
        query.setCondition('Id IN : recordIds');
        query.selectField('Loan_Applicant__r.Loan_Application__r.LOB__c');
        return (List<Verification__c>) Database.query(query.toSOQL());
    }

    public List<Verification__c> selectByIdLoanApplicationId(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Applicant__r.Loan_Application__c IN : recordIds');
        query.selectField('RecordType.Name');
        query.selectField('RecordType.DeveloperName');
        query.selectField('Loan_Applicant__c');
        query.selectField('Loan_Applicant__r.Name');
        query.selectField('Loan_Applicant__r.Proof_of_Address__c');
        query.selectField('LastModifiedDate');
        query.selectField('CreatedDate');
        query.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<Verification__c>) Database.query(query.toSOQL());
    }
    
    public List<Verification__c> selectByIdWithFraudInfo(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('CFR_Fraud_Information__c');
        query.setCondition('Id IN : recordIds');
        return (List<Verification__c>) Database.query(query.toSOQL());
    }
    
    public List<Verification__c> selectByDisbIdAndRecordType(Set<Id> recordIds, String recordType){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Disbursement__c IN : recordIds and RecordType.Name =: recordType')
            .setOrdering('createddate',fflib_QueryFactory.SortOrder.DESCENDING)
            .setLimit(1);
        return (List<Verification__c>) Database.query(query.toSOQL());
    }
}