force-app/main/default/objects/Activity_History__c/Activity_History__c.object-meta.xml
<CustomObject>
    <label>Activity History</label>
    <nameField>
        <displayFormat>App History-{00000}</displayFormat>
        <label>Activity History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Histories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_History__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipName>Application_Movement_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/Deviation_Sanction_Condition__c.object-meta.xml
<CustomObject>
    <label>Deviation/Sanction Condition</label>
    <nameField>
        <displayFormat>DSC-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deviation/Sanction Conditions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Approved_Rejected_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_Rejected_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved/Rejected By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Deviation_Sanction_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Approving_Authority__c.field-meta.xml
<CustomField>
    <fullName>Approving_Authority__c</fullName>
    <label>Approving Authority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent for Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Deviation_Description__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Description__c</fullName>
    <label>Deviation Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Deviation_Type__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Type__c</fullName>
    <label>Deviation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auto</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Deviation/Sanction Conditions</relationshipLabel>
    <relationshipName>Deviation_Sanction_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Mitigants__c.field-meta.xml
<CustomField>
    <fullName>Mitigants__c</fullName>
    <label>Mitigants</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Reason_Comments__c.field-meta.xml
<CustomField>
    <fullName>Reason_Comments__c</fullName>
    <label>Reason Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Reason_Special_Condition__c.field-meta.xml
<CustomField>
    <fullName>Reason_Special_Condition__c</fullName>
    <label>Reason/Special Condition</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Deviation</fullName>
            </value>
            <value>
                <fullName>Sanction Condition</fullName>
            </value>
            <value>
                <fullName>Special Condition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{00000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Valuation__c.field-meta.xml
<CustomField>
    <fullName>Valuation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Valuation</label>
    <referenceTo>Valuation__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Assessment__c/Financial_Assessment__c.object-meta.xml
<CustomObject>
    <label>Financial Assessment</label>
    <nameField>
        <displayFormat>FA-{0000000}</displayFormat>
        <label>financial assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Assessment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Assessment__c/fields/Current_Ratio__c.field-meta.xml
<CustomField>
    <fullName>Current_Ratio__c</fullName>
    <label>Current Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Assessment__c/fields/DSCR_should_be_1__c.field-meta.xml
<CustomField>
    <fullName>DSCR_should_be_1__c</fullName>
    <label>DSCR should be 1%</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Assessment__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Financial Assessment</relationshipLabel>
    <relationshipName>Financial_Assessment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Assessment__c/fields/TOL_TNW__c.field-meta.xml
<CustomField>
    <fullName>TOL_TNW__c</fullName>
    <label>TOL / TNW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Financial_Assessment__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Financial Assessment</relationshipLabel>
    <relationshipName>Financial_Assessment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Assessment__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <label>Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Working_in_a_bank_as_director_Sr_Office__c.field-meta.xml
<CustomField>
    <fullName>Working_in_a_bank_as_director_Sr_Office__c</fullName>
    <description>Is applicant or his relative working in a bank as director/Sr. Officer ?</description>
    <label>Working in bank as director/Sr. Officer?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Duplicate_LAF_Id__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_LAF_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dedupe Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Status__c</fullName>
    <label>Loan Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
            <value>
                <fullName>Revoke</fullName>
            </value>
            <value>
                <fullName>Query Raised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valuation__c/Valuation__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Valuation__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/recordTypes/RCU.recordType-meta.xml
<RecordType>
    <fullName>RCU</fullName>
    <active>true</active>
    <label>RCU</label>
</RecordType>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CAM_PDFController.cls
/**
* @File Name          : CAM_PDFController.cls
* @Description        : This class used to fetch data for CAM report.
* @Author             : Mohd Musab
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         09-07-2024               Mohd Musab                Initial Version
*/
public class CAM_PDFController {
    public Loan_Application__c applicationId { get; set; }
    public Loan_Application__c loanApplicationObj { get; set; }
    public List<Vehicle__c> newVehicleList { get; set; }
    public List<Vehicle__c> usedVehicleList { get; set; }
    public List<Loan_Applicant__c> primaryApplicantList {get; set;}
    public List<Loan_Applicant__c> coApplicantList {get; set;}
    public List<Loan_Applicant__c> guarantorApplicantList {get; set;}
    public List<Deviation_Sanction_Condition__c> deviationSanctionList {get; set;}
    public List<Deviation_Sanction_Condition__c> deviationDecisionSheet {get; set;}
    public List<Activity_History__c> activityHistoryList {get; set;}
    public Financial_Assessment__c financialAssessment{get;set;}
    public List<Valuation__c> applicantActivityFI{get;set;}
    public List<Valuation__c> applicantActivityOffice{get;set;}
    public List<Valuation__c> applicantActivityRCU{get;set;}
    public String loginDate {get; set;}
    public String internalDedupeStatus {get; set;}
    public String IsDirectorSrOfficer {get; set;}
    public String decisioningOfficeName {get;set;}
    public String recommendedOfficerName {get;set;}
    public String recommendedOfficerSignature {get;set;}
    public String decisioningOfficerSignature {get;set;}
    public String formattedDate {get; set;}
    public String lastModifiedDate {get; set;}
    public String decisioningStatus {get; set;}
    public CAM_PDFController() {
        try
        {
            Date currentDate = Date.today();
            DateTime currentDateTime = DateTime.newInstance(currentDate.year(), currentDate.month(), currentDate.day());
            formattedDate = currentDateTime.format('dd-MMMM-yyyy');
            Id applicationId = ApexPages.currentPage().getParameters().get('id');
            if (applicationId != null) {
            loanApplicationObj = new UB_LoanApplicationsSelector().getLoanApplicationRecord(applicationId);
            System.debug('loanApplicationObj '+ loanApplicationObj);
            loginDate = loanApplicationObj.createdDate.format('yyyy-MM-dd');
            lastModifiedDate = loanApplicationObj.LastModifiedDate.format('dd-MMMM-yyyy');
            if(loanApplicationObj.Duplicate_LAF_Id__c != null){
                internalDedupeStatus = 'Match Found';
            }
            else{
                internalDedupeStatus = 'No Match Found';
            }
            System.debug('internalDedupeStatus  '+internalDedupeStatus);
            newVehicleList = new UB_VehiclesSelector().selectByLoanApplicationIdforVehicle(applicationId,'New Vehicle');
            System.debug('newVehicleList '+newVehicleList);
            usedVehicleList = new UB_VehiclesSelector().selectByLoanApplicationIdforVehicle(applicationId,'Used Vehicle');
            System.debug('usedVehicleList '+usedVehicleList);

            primaryApplicantList = new UB_LoanApplicantsSelector().getApplicants(new Set<Id>{applicationId},UB_ConstantsUtil.APPLICANT);
            System.debug('primaryApplicantList '+primaryApplicantList);

            IsDirectorSrOfficer = primaryApplicantList[0].Working_in_a_bank_as_director_Sr_Office__c;
            System.debug('2222222222222  ');

            coApplicantList = new UB_LoanApplicantsSelector().getApplicants(new Set<Id>{applicationId},UB_ConstantsUtil.CO_APPLICANT);
            System.debug('coApplicantList '+coApplicantList);

            guarantorApplicantList = new UB_LoanApplicantsSelector().getApplicants(new Set<Id>{applicationId},UB_ConstantsUtil.GUATANTOR);
            System.debug('guarantorApplicantList '+guarantorApplicantList);

            deviationSanctionList = [SELECT Id,Deviation_Description__c,Approving_Authority__c,Deviation_Type__c,Mitigants__c,Decision__c, Approved_Rejected_By__c,
                                     Type__c,Loan_Application__c from Deviation_Sanction_Condition__c
                                     WHERE Loan_Application__c =: applicationId AND Type__c = 'Deviation'];

            System.debug('deviationSanctionList '+deviationSanctionList);


            deviationDecisionSheet = [SELECT Id,Reason_Special_Condition__c,Reason_Comments__c,CreatedBy.Name,CreatedDate,
            Type__c,Loan_Application__c,Approving_Authority__c from Deviation_Sanction_Condition__c
            WHERE Loan_Application__c =: applicationId AND Type__c = 'Special Condition'];                             
            System.debug('deviationDecisionSheet '+deviationDecisionSheet);
            financialAssessment = [SELECT Id,DSCR_should_be_1__c, TOL_TNW__c, Current_Ratio__c,Loan_Application__c
                                       from Financial_Assessment__c WHERE Loan_Application__c =: applicationId  Order by Year__c desc LIMIT 1];    
                                       
            System.debug('financialAssessment '+financialAssessment);
            applicantActivityFI = new UB_ActivitySelector().selectByApplicantId(primaryApplicantList[0].Id, 'Residence FI');
            applicantActivityOffice = new UB_ActivitySelector().selectByApplicantId(primaryApplicantList[0].Id, 'Office FI');
            applicantActivityRCU = new UB_ActivitySelector().selectByApplicantId(primaryApplicantList[0].Id, 'RCU');        
            activityHistoryList = new UB_ActivityHistoriesSelector().selectLatestByLoanApplicationId(new Set<Id>{applicationId});
            System.debug('applicantActivityFI '+applicantActivityFI);
            System.debug('applicantActivityOffice '+applicantActivityOffice);
            System.debug('applicantActivityRCU '+applicantActivityRCU);
            System.debug('activityHistoryList '+activityHistoryList);
            if(loanApplicationObj.Loan_Application_Status__c == UB_ConstantsUtil.APPROVED_STATUS){
                decisioningStatus = UB_ConstantsUtil.APPROVED_STATUS;
                recommendedOfficerName = activityHistoryList.size()>0 ? activityHistoryList[0].From_User__r.Name : '';
                decisioningOfficeName = UserInfo.getName();
                recommendedOfficerSignature = activityHistoryList.size()>0 ? activityHistoryList[0].From_User__r.Name + ' ' + activityHistoryList[0].From_User__r.EmployeeNumber +' '+ loanApplicationObj.LastModifiedDate.format('yyyy-MM-dd') : '';
                decisioningOfficerSignature = UserInfo.getName() + ' ' + loanApplicationObj.LastModifiedDate.format('dd-MMMM-yyyy');
            }
            else{
                decisioningStatus = 'Recommended for Approval';
                recommendedOfficerName = UserInfo.getName();
                decisioningOfficeName = 'NA';
                recommendedOfficerSignature = UserInfo.getName()  + ' ' + loanApplicationObj.LastModifiedDate.format('dd-MMMM-yyyy');
                decisioningOfficerSignature = 'NA';
                
            } 
        }                                        
        }
        catch (Exception e) {
            System.debug('the exception is >>'+e.getLineNumber()+'Exception message is >>'+e.getMessage());
        }
    }

	@AuraEnabled
    @Future(callout=true)
    public static void linkCamToDocument(String loanId) {
        try {
            List<Document__c> camDOcument = [SELECT Id FROM Document__c WHERE Document_Type__c='CAM Report' AND Loan_Application__c =:loanId];
            System.debug('lafDOcument   '+camDOcument);
            System.debug('loanId ID  '+loanId);
            Blob b ;
            if(loanId != null ) {
                PageReference PDf =  Page.CV_CAM_PDF;
                System.debug('PDfPDfPDf  '+PDf);
                PDf.getParameters().put('Id',loanId);
                System.debug('1AAAAAAAAAAAAAA');
                PDf.setRedirect(false);
                b = PDf.getContentAsPdf();
                System.debug('1BBBBBBBBBBBBBBBBB'+b );

                UB_CommonUtil.createDocument('CV CAM','CV CAM.pdf', b,loanId, NULL,'CAM Report','CAM Report with time stamp and Version number');
                Loan_Application__c loanApplication = new Loan_Application__c();
                loanApplication.Id = loanId;
                loanApplication.Cam_Generate__c = false;
                update loanApplication;
            } 
        } catch (Exception e) {
            System.debug('the exception is >>'+e.getLineNumber()+'Exception message is >>'+e.getMessage());
        }
    }

}