force-app/main/default/objects/Activity_History__c/Activity_History__c.object-meta.xml
<CustomObject>
    <label>Activity History</label>
    <nameField>
        <displayFormat>App History-{00000}</displayFormat>
        <label>Activity History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Histories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_History__c/fields/From_To_Queue__c.field-meta.xml
<CustomField>
    <fullName>From_To_Queue__c</fullName>
    <label>From-To Queue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Activity_History__c/fields/From_User__c.field-meta.xml
<CustomField>
    <fullName>From_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>From User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Application_Movement_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_History__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipName>Application_Movement_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_History__c/fields/TAT__c.field-meta.xml
<CustomField>
    <fullName>TAT__c</fullName>
    <label>TAT</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Activity_History__c/fields/To_User__c.field-meta.xml
<CustomField>
    <fullName>To_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>To User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Application_Movement_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UB_ActivityHistoriesSelector.cls
/**
* @File Name          : UB_ActivityHistoriesSelector.cls
* @Description        : This class used to fetch/query ActivityHistories records based on conditions.
* @Author             : Deepak Joshi
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         2-05-2024               Deepak Joshi                 Initial Version
*/
public with sharing class  UB_ActivityHistoriesSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Activity_History__c.Id,
            Activity_History__c.TAT__c,
            Activity_History__c.CreatedDate,
            Activity_History__c.Name,
            Activity_History__c.From_User__c,
            Activity_History__c.To_User__c,
            Activity_History__c.Loan_Application__c,
            Activity_History__c.From_To_Queue__c
        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Activity_History__c.sObjectType;
    }
    public override String getOrderBy(){
        return 'Name DESC';
     }
    public List<Activity_History__c> selectById(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN : recordIds');
        return (List<Activity_History__c>) Database.query(query.toSOQL());
    }
    public List<Activity_History__c> selectByLoanApplicationId(Set<Id> recordIds){  
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Application__c IN : recordIds');
        System.debug(query.toSOQL());
        return (List<Activity_History__c>) Database.query(query.toSOQL());
    }

    //Added by Musab || 13-07-2024
    public List<Activity_History__c> selectLatestByLoanApplicationId(Set<Id> recordIds){  
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Application__c IN : recordIds');
        query.selectField('From_User__r.Name');
        query.selectField('To_User__r.Name');
        query.selectField('From_User__r.EmployeeNumber');
        query.setOrdering('createddate',fflib_QueryFactory.SortOrder.DESCENDING);
        query.setLimit(1);
        System.debug(query.toSOQL());
        return (List<Activity_History__c>) Database.query(query.toSOQL());
    }
}