force-app/main/default/objects/Activity_History__c/Activity_History__c.object-meta.xml
<CustomObject>
    <label>Activity History</label>
    <nameField>
        <displayFormat>App History-{00000}</displayFormat>
        <label>Activity History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activity Histories</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity_History__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Activity Histories</relationshipLabel>
    <relationshipName>Activity_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity_History__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipName>Application_Movement_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{00000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consent Pending</fullName>
            </value>
            <value>
                <fullName>Document Verification</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
                <isActive>false</isActive>
                <label>Lead</label>
            </value>
            <value>
                <fullName>Login</fullName>
                <isActive>false</isActive>
                <label>Login</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/Document_Checklist__c.object-meta.xml
<CustomObject>
    <label>Document Checklist</label>
    <nameField>
        <displayFormat>Doc-{00000}</displayFormat>
        <label>Doc Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklist</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consent Pending</fullName>
            </value>
            <value>
                <fullName>Document Verification</fullName>
            </value>
            <value>
                <fullName>Disbursal In Progress</fullName>
            </value>
            <value>
                <fullName>Pre-Disbursal Document Collection</fullName>
            </value>
            <value>
                <fullName>Credit Due Deliquency</fullName>
                <isActive>false</isActive>
                <label>Credit Due Deliquency</label>
            </value>
            <value>
                <fullName>Credit Due Diligence</fullName>
                <isActive>false</isActive>
                <label>Credit Due Diligence</label>
            </value>
            <value>
                <fullName>Customer Due Diligence</fullName>
                <isActive>false</isActive>
                <label>Customer Due Diligence</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
            <value>
                <fullName>Post Disbursement</fullName>
                <isActive>false</isActive>
                <label>Post Disbursement</label>
            </value>
            <value>
                <fullName>Pre Disbursement</fullName>
                <isActive>false</isActive>
                <label>Pre Disbursement</label>
            </value>
            <value>
                <fullName>Pre Login</fullName>
                <isActive>false</isActive>
                <label>Pre Login</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Consent Pending</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Fields_Mapping__mdt/Lead_Fields_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Lead Fields Mapping</label>
    <pluralLabel>Lead Fields Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Lead_Fields_Mapping__mdt/fields/Lead_Fields_Name__c.field-meta.xml
<CustomField>
    <fullName>Lead_Fields_Name__c</fullName>
    <label>Lead Fields Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Fields_Mapping__mdt/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Loan_Application__c</fullName>
            </value>
            <value>
                <fullName>Loan_Applicant__c</fullName>
            </value>
            <value>
                <fullName>Product__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Fields_Mapping__mdt/fields/Target_Object_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Target_Object_Field_Name__c</fullName>
    <label>Target Object Field Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Master__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial Vehicle Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Construction Equipment Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Tractor Loan</fullName>
        <isActive>false</isActive>
        <label>Tractor Loan</label>
    </customValue>
    <customValue>
        <fullName>Three Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Three Wheeler Loan</label>
    </customValue>
    <customValue>
        <fullName>Car Loan</fullName>
        <isActive>false</isActive>
        <label>Car Loan</label>
    </customValue>
    <customValue>
        <fullName>Office Equipment</fullName>
        <isActive>false</isActive>
        <label>Office Equipment</label>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
        <isActive>false</isActive>
        <label>Medical Equipment</label>
    </customValue>
    <customValue>
        <fullName>Two Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Two Wheeler Loan</label>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_ConvertLeadController.cls
/**
* @File Name          : UB_ConvertLeadController.cls
* @Description        : This class will have convert lead
* @Author             : Deepak Joshi
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         22-03-2024            Deepak Joshi          Initial Version           
**/
public with sharing class UB_ConvertLeadController {
 /*
    This method is use to to convert lead and create new records 
    */
    @AuraEnabled
    public static string convertLead(String leadId){
        Savepoint sp = Database.setSavepoint();
        try {
            List<Lead_Fields_Mapping__mdt>  leadFieldsMappingList = Lead_Fields_Mapping__mdt.getAll().values();
            List<Lead__c> leadRecords = new UB_LeadsSelector().selectById(new Set<Id>{leadId});
            Lead__c leadObj  = leadRecords[0];
            if(leadObj.Lead_Stage__c == 'New'){
                leadObj.Lead_Stage__c = UB_ConstantsUtil.CONSENT_PENDING;
                update leadObj;
                createDocument(leadObj.Lead_Stage__c ,leadObj.Id);
                return 'SUCCESS';

            }



            Account accObje = new Account();
            Loan_Applicant__c loanApplicantObj = new Loan_Applicant__c();
            Loan_Application__c  loanApplicationObj = new Loan_Application__c();
            //Product__c  productObj = new Product__c();
            String loanApplicationId;

            for(Lead_Fields_Mapping__mdt leadFields : leadFieldsMappingList){
                
                if(leadFields.Target_Object__c == UB_ConstantsUtil.ACCOUNT && leadObj.get(leadFields.Lead_Fields_Name__c) !=null){
                   accObje.put(leadFields.Target_Object_Field_Name__c ,leadObj.get(leadFields.Lead_Fields_Name__c));
                
                }
                if(leadFields.Target_Object__c== UB_ConstantsUtil.LOAN_APPLICANT && leadObj.get(leadFields.Lead_Fields_Name__c) !=null){
                   loanApplicantObj.put(leadFields.Target_Object_Field_Name__c ,leadObj.get(leadFields.Lead_Fields_Name__c));
            
                }
                if(leadFields.Target_Object__c== UB_ConstantsUtil.LOAN_APPLICATION  && leadObj.get(leadFields.Lead_Fields_Name__c) !=null){
                   loanApplicationObj.put(leadFields.Target_Object_Field_Name__c ,leadObj.get(leadFields.Lead_Fields_Name__c));
            
                }
                //if(leadFields.Target_Object__c== UB_ConstantsUtil.PRODUCT && leadObj.get(leadFields.Lead_Fields_Name__c) !=null){
                //    productObj.put(leadFields.Target_Object_Field_Name__c ,leadObj.get(leadFields.Lead_Fields_Name__c));
            
                //}

            }
            //if(Schema.sObjectType.Account.isCreateable()){
                System.debug('** accObje   == '+accObje);
                accObje.RecordTypeId =Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(UB_ConstantsUtil.CUSTOMER).getRecordTypeId();
                Account checkedDupAccount= UB_CommonUtil.ckeckAccountduplicateWithPanNo(leadObj.PAN__c);
                if(checkedDupAccount != null){
                    accObje.Id = checkedDupAccount.Id;
                    
                }
                upsert accObje;
            //}
            //if(Schema.sObjectType.Product__c.isCreateable()){
             //   System.debug('** productObj   == '+productObj);
            //    insert productObj;
           // }
            if(Schema.sObjectType.Loan_Application__c.isCreateable()){
                System.debug('** loanApplicationObj   == '+loanApplicationObj);
                loanApplicationObj.Loan_Application_Stage__c =UB_ConstantsUtil.KYC_VALIDATION;
                insert loanApplicationObj;
                loanApplicationId =  loanApplicationObj.Id;
               
            }
            if(Schema.sObjectType.Loan_Applicant__c.isCreateable()){
                loanApplicantObj.Account__c =accObje.Id; 
                loanApplicantObj.Loan_Application__c =loanApplicationId;
                loanApplicantObj.Applicant_Type__c = UB_ConstantsUtil.APPLICANT;
                insert loanApplicantObj;
                updateDocument(leadId,loanApplicationId,loanApplicantObj.Id);
                updateAddress(leadId,loanApplicantObj.Id);
            }
            if(Schema.sObjectType.Lead__c.isUpdateable()){
                leadObj.Lead_Stage__c =UB_ConstantsUtil.CONVERTED;
                update leadObj;
            }
            
            Activity_History__c activityHistory   = UB_CommonUtil.createActivityHistory(UB_ConstantsUtil.LOAN_APPLICATION,loanApplicationId,UB_ConstantsUtil.KYC_VALIDATION ,'');
            insert activityHistory;
            return loanApplicationId;
        } catch (Exception e) {
            Database.rollback(sp);
            System.debug('** error Line   == '+ e.getLineNumber());
            System.debug('** error e   == '+ e);
            System.debug('Exception@@'+e.getMessage());
            UB_CommonUtil.createExceptionLogRecord(e, UB_ConstantsUtil.LOB_CV);
           return 'ERROR: '+e.getMessage();
           // throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string checkValidations(string recordId) {
        try{
            Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('ConvertLeadController');
            List<Lead__c> leadList = new UB_LeadsSelector().selectById(new Set<Id>{recordId});
            System.debug('**loanAppObj--checkValidations->   '+leadList);
            string validationMsg = checkValidation(leadList[0], messageConfigMap); 
            if(validationMsg.trim().length() > 0) {
                return validationMsg;
            }  
            return null;        
        } catch (Exception e) {
            System.debug('** error Line   == '+ e.getLineNumber());
            System.debug('** error e   == '+ e);
        
            throw new AuraHandledException(e.getMessage());
        }
    }
     // methode to check validations
     private static string checkValidation(Lead__c leadObj,Map<String,Messages_Config__mdt> messageConfigMap) {
        string validationMsg = '';
    

        if(leadObj.Lead_Stage__c == UB_ConstantsUtil.CONSENT_PENDING){
               System.debug('**leadObj== '+ leadObj.Consent_Received__c);
            if(leadObj.Consent_Received__c == false)  {
            validationMsg = '<li>'+messageConfigMap.get('Consent_Received').Message__c+'</li>';
            }
            if(leadObj.PAN__c == null)  {
                validationMsg  += '<li>'+messageConfigMap.get('PAN').Message__c+'</li>';
            }
        }
        if(leadObj.Lead_Stage__c == 'New'){
            if(leadObj.PAN__c == null)  {
                validationMsg = '<li>'+UB_ConstantsUtil.PAN_REQUIRED+'</li>';
            }
            
            if(leadObj.Addresses__r.size() == 0) {
                validationMsg += '<li>'+UB_ConstantsUtil.ADDRESS_REQUIRED+'</li>';
            } 
           
        }
        
        return validationMsg;
    }
    // update loan Application Id on leade Documents
    private static void updateDocument( String leadId, String loanApplicationId,String loanApplicantId){
        if(Schema.sObjectType.Document__c.isUpdateable() && loanApplicantId !=null){
            List<Document__c>  documentList = new UB_DocumentsSelector().selectByLeasId(new Set<Id>{leadId}); 
            System.debug('documentList  '+documentList);
            for(Document__c doc :documentList){
                doc.Loan_Application__c = loanApplicationId;
                doc.Loan_Applicant__c = loanApplicantId;
            }
            update documentList;
        }

    }
    // update loan Application Id on leade address 
    private static void updateAddress( String leadId, String loanApplicantId){
        if(Schema.sObjectType.Address__c.isUpdateable() && loanApplicantId !=null){ 
            List<Address__c>  addressList = new UB_AddressesSelector().selectByLeasId(new Set<Id>{leadId}); 
            System.debug('--addressList  '+addressList);
            for(Address__c addr :addressList){
                addr.Loan_Applicant__c = loanApplicantId;
            }
            update addressList;
        }

    }
    public static void createDocument(String stageName,String leadId) {
        Savepoint sp = Database.setSavepoint();
        try{
            System.debug('** stageName '+ stageName);
            List<Document_Checklist__c>  documentChecklists = new UB_DocumentChecklistsSelector().selectByStage(stageName); 
            System.debug('** documentChecklists '+ documentChecklists);
            List<Document__c> documentList = new List<Document__c>();
            for(Document_Checklist__c doc : documentChecklists ){
               Document__c documentObj = new Document__c();
                documentObj.Document_Checklist__c = doc.Id;
                documentObj.Lead__c = leadId;
                documentObj.Stage__c = doc.Stage__c;
                documentObj.Is_Required__c = doc.Is_Required__c;
                documentObj.Document_Type__c = doc.Document_Type__c;
                documentObj.Document_Sub_Type__c = doc.Document_Subtype__c;
                documentList.add(documentObj);
            }
            if(!documentList.isEmpty()){
                System.debug('** documentList '+ documentList);
                insert documentList;

            }
        
        } catch(Exception e) {
            Database.rollback(sp);
            System.debug('** error Line   == '+ e.getLineNumber());
            System.debug('** error e   == '+ e);
            System.debug('Exception@@'+e.getMessage());
        }

    }
    
    
}