force-app/main/default/objects/Dealer_Master__c/Dealer_Master__c.object-meta.xml
<CustomObject>
    <label>Dealer Master</label>
    <nameField>
        <label>Dealer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealer Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Master__c/fields/IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>IFSC_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IFSC Code</label>
    <referenceTo>IFSC_Master__c</referenceTo>
    <relationshipLabel>Dealer Master</relationshipLabel>
    <relationshipName>Dealer_Master</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Number_Of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Vehicles__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Actual_LTV__c.field-meta.xml
<CustomField>
    <fullName>Actual_LTV__c</fullName>
    <label>Actual LTV</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Advance_EMI__c.field-meta.xml
<CustomField>
    <fullName>Advance_EMI__c</fullName>
    <label>Advance EMI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Asset_Insurance_Premium__c.field-meta.xml
<CustomField>
    <fullName>Asset_Insurance_Premium__c</fullName>
    <label>Asset Insurance Premium</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Chassis_Number__c.field-meta.xml
<CustomField>
    <fullName>Chassis_Number__c</fullName>
    <label>Chassis Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Credit_Facility_Amount__c.field-meta.xml
<CustomField>
    <fullName>Credit_Facility_Amount__c</fullName>
    <label>Credit Facility Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Dealer_Master__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Eligible_LTV__c.field-meta.xml
<CustomField>
    <fullName>Eligible_LTV__c</fullName>
    <label>Eligible LTV</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/EMI__c.field-meta.xml
<CustomField>
    <fullName>EMI__c</fullName>
    <formula>CEILING((Vehicle_Cost__c* (ROI__c/12) )*
(((1+(ROI__c/12))^ VALUE(TEXT(Tenure__c)))/
(((1+(ROI__c/12))^ VALUE(TEXT(Tenure__c)))-1)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Engine_Number__c.field-meta.xml
<CustomField>
    <fullName>Engine_Number__c</fullName>
    <label>Engine Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Fitness_Validity__c.field-meta.xml
<CustomField>
    <fullName>Fitness_Validity__c</fullName>
    <label>Fitness Validity</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Funding_Limit__c.field-meta.xml
<CustomField>
    <fullName>Funding_Limit__c</fullName>
    <label>Financed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/IDV__c.field-meta.xml
<CustomField>
    <fullName>IDV__c</fullName>
    <label>IDV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Insurance_Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Expiry_Date__c</fullName>
    <label>Insurance Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Manufactured_Month_Year__c.field-meta.xml
<CustomField>
    <fullName>Manufactured_Month_Year__c</fullName>
    <label>Manufactured Month-Year</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Margin_Money__c.field-meta.xml
<CustomField>
    <fullName>Margin_Money__c</fullName>
    <label>Margin Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Number_of_Asset_Unit__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Asset_Unit__c</fullName>
    <label>Number of Asset Unit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Number_Of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Vehicles__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number of Existing Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Owner_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Owner_Serial_Number__c</fullName>
    <label>Owner Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Plough_Back__c.field-meta.xml
<CustomField>
    <fullName>Plough_Back__c</fullName>
    <label>Plough Back %</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Plough_Black_Amount__c.field-meta.xml
<CustomField>
    <fullName>Plough_Black_Amount__c</fullName>
    <label>Plough Black Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/RTO_Value__c.field-meta.xml
<CustomField>
    <fullName>RTO_Value__c</fullName>
    <label>RTO Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Subvention__c.field-meta.xml
<CustomField>
    <fullName>Subvention__c</fullName>
    <label>Subvention</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Tenure (In Month Per Vehicle)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Cost__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Cost__c</fullName>
    <label>Vehicle Cost (Per Vehicle)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Master</label>
    <nameField>
        <displayFormat>VM-{00000}</displayFormat>
        <label>Vehicle Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open Body</fullName>
            </value>
            <value>
                <fullName>Closed (Container)</fullName>
            </value>
            <value>
                <fullName>MS Tanker</fullName>
            </value>
            <value>
                <fullName>SS Tanker</fullName>
            </value>
            <value>
                <fullName>Milk Tanker</fullName>
            </value>
            <value>
                <fullName>Bulker</fullName>
            </value>
            <value>
                <fullName>Open Flat Body</fullName>
            </value>
            <value>
                <fullName>Refrigerated Container</fullName>
            </value>
            <value>
                <fullName>Tipper</fullName>
            </value>
            <value>
                <fullName>Route Bus</fullName>
            </value>
            <value>
                <fullName>Staff Bus</fullName>
            </value>
            <value>
                <fullName>Semi Luxury Bus</fullName>
            </value>
            <value>
                <fullName>Luxury Bus</fullName>
            </value>
            <value>
                <fullName>AC Sleeper</fullName>
            </value>
            <value>
                <fullName>Non-AC Sleeper</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Tip-Trailer</fullName>
            </value>
            <value>
                <fullName>BHL</fullName>
            </value>
            <value>
                <fullName>Excavator</fullName>
            </value>
            <value>
                <fullName>Compactor</fullName>
            </value>
            <value>
                <fullName>Generator</fullName>
            </value>
            <value>
                <fullName>Loader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tata Motors Ltd</fullName>
            </value>
            <value>
                <fullName>Ashok Leyland</fullName>
            </value>
            <value>
                <fullName>Mahindra &amp; Mahindra Ltd</fullName>
            </value>
            <value>
                <fullName>Eicher Ltd</fullName>
            </value>
            <value>
                <fullName>Body Builder</fullName>
            </value>
            <value>
                <fullName>JCB Ltd.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chassis</fullName>
            </value>
            <value>
                <fullName>Cab Chassis</fullName>
            </value>
            <value>
                <fullName>Fully Built</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial Vehicle Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Construction Equipment Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Tractor Loan</fullName>
        <isActive>false</isActive>
        <label>Tractor Loan</label>
    </customValue>
    <customValue>
        <fullName>Three Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Three Wheeler Loan</label>
    </customValue>
    <customValue>
        <fullName>Car Loan</fullName>
        <isActive>false</isActive>
        <label>Car Loan</label>
    </customValue>
    <customValue>
        <fullName>Office Equipment</fullName>
        <isActive>false</isActive>
        <label>Office Equipment</label>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
        <isActive>false</isActive>
        <label>Medical Equipment</label>
    </customValue>
    <customValue>
        <fullName>Two Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Two Wheeler Loan</label>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_VehiclesSelector.cls
/**
* @File Name          : UB_VehiclesSelector.cls
* @Description        : This class used to fetch/query Vehicl records based on conditions.
* @Author             : Deepak Joshi
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         24-4-2024              Deepak Joshi                 Initial Version
*/
public  with sharing class  UB_VehiclesSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Vehicle__c.Id,
                Vehicle__c.Name,
                Vehicle__c.Vehicle_Cost__c,
                Vehicle__c.Number_Of_Vehicles__c,
                Vehicle__c.Tenure__c,
                Vehicle__c.ROI__c,
                Vehicle__c.Asset_Insurance_Premium__c,
                Vehicle__c.Margin_Money__c,
                Vehicle__c.Loan_Application__c,
                Vehicle__c.Registration_Number__c,
                Vehicle__c.Vehicle_Type__c,
                Vehicle__c.Body_Type__c,
                Vehicle__c.Number_of_Asset_Unit__c,
                Vehicle__c.Model__c,
                Vehicle__c.RTO_Value__c,
                Vehicle__c.EMI__c,
                Vehicle__c.ROI__c,
                Vehicle__c.Make__c,
                Vehicle__c.Owner_Name__c,
                Vehicle__c.Chassis_Number__c,
                Vehicle__c.Engine_Number__c,
                Vehicle__c.Manufactured_Month_Year__c,
                Vehicle__c.Owner_Serial_Number__c,
                Vehicle__c.Fitness_Validity__c,
                Vehicle__c.Subvention__c,
                Vehicle__c.Plough_Black_Amount__c,
                Vehicle__c.Plough_Back__c,
                Vehicle__c.Eligible_LTV__c,
                Vehicle__c.Actual_LTV__c,
                Vehicle__c.IDV__c,
                Vehicle__c.Funding_Limit__c,
                Vehicle__c.Credit_Facility_Amount__c,
                Vehicle__c.Variant__c,
                Vehicle__c.Insurance_Expiry_Date__c,
                Vehicle__c.Advance_EMI__c
                };
                    }
    
    public Schema.SObjectType getSObjectType(){
        return Vehicle__c.sObjectType;
    }
    
    public List<Vehicle__c> selectById(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN : recordIds');
        return (List<Vehicle__c>) Database.query(query.toSOQL());
    }
    //added by Mansur Alam
    public List<Vehicle__c> selectByLoanApplicationId(Set<Id> applicationId){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Application__c IN : applicationId' );
        query.selectField('Dealer__r.IFSC_Code__c');
        return (List<Vehicle__c>) Database.query(query.toSOQL());
    }
    
    public List<Vehicle__c> selectByIdsWithProductInfo(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Product__c');
        query.selectField('Product__r.Product_Category__c');
        query.setCondition('Id IN : recordIds' );
        return (List<Vehicle__c>) Database.query(query.toSOQL());
    }

    //added by Mohd Musab 13-07-2024
    public List<Vehicle__c> selectByLoanApplicationIdforVehicle(String applicationId, String recordTypeName){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Application__c =: applicationId AND recordType.Name =: recordTypeName' );
        query.selectField('Dealer__r.IFSC_Code__c');
        query.selectField('Vehicle_Master__r.Registrable__c');
        query.selectField('Vehicle_Master__r.Vehicle_Type__c');
        query.selectField('Vehicle_Master__r.Vehicle_Classification__c');
        query.selectField('Vehicle_Master__r.Vehicle_Category__c');
        query.selectField('Dealer__r.Name');
        query.selectField('Dealer__r.Dealer_Code__c');
        return (List<Vehicle__c>) Database.query(query.toSOQL());
    }
}