force-app/main/default/objects/Bank_Details__c/Bank_Details__c.object-meta.xml
<CustomObject>
    <label>Bank Details</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Bank Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Details__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <label>Account Number</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Saving</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>CC/OD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Active_Since__c.field-meta.xml
<CustomField>
    <fullName>Active_Since__c</fullName>
    <label>Active Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Bank_Name__c.field-meta.xml
<CustomField>
    <fullName>Bank_Name__c</fullName>
    <formula>IFSC_Code__r.Bank_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bank Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <formula>IFSC_Code__r.Branch__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>Disbursement__c</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/IFSC_Code__c.field-meta.xml
<CustomField>
    <fullName>IFSC_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IFSC Code</label>
    <referenceTo>IFSC_Master__c</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Institution_Id__c.field-meta.xml
<CustomField>
    <fullName>Institution_Id__c</fullName>
    <label>Institution Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Is_Primary_Repayment_Account__c.field-meta.xml
<CustomField>
    <fullName>Is_Primary_Repayment_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Primary Repayment Account?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RTGS</fullName>
            </value>
            <value>
                <fullName>NEFT</fullName>
            </value>
            <value>
                <fullName>DD</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Disbursement__c/Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Disbursement__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Disbursements</relationshipLabel>
    <relationshipName>Disbursements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UB_BankSelector.cls
/**
* @File Name          : UB_BankSelector.cls
* @Description        : This class used to fetch/query Reference records based on conditions.
* @Author             : Mansur
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         30-07-2024               Mansur                 Initial Version
*/
public class UB_BankSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Bank_Details__c.Id,
                Bank_Details__c.Account_Holder_Name__c,
                Bank_Details__c.Account_Number__c,
                Bank_Details__c.Account_Type__c,
                Bank_Details__c.Active_Since__c,
                Bank_Details__c.Bank_Name__c,
                Bank_Details__c.Branch_Name__c,
                Bank_Details__c.Is_Primary_Repayment_Account__c,
                Bank_Details__c.Institution_Id__c,
                Bank_Details__c.IFSC_Code__c,
                Bank_Details__c.Disbursement__c,
                Bank_Details__c.Loan_Application__c,
                Bank_Details__c.Name,
                Bank_Details__c.Payment_Mode__c,
                Bank_Details__c.RecordType.Name ,
                Bank_Details__c.Record_Type_Name__c
                };
                    }
    
    public Schema.SObjectType getSObjectType(){
        return Bank_Details__c.sObjectType;
    }
    
    public List<Bank_Details__c> selectById(Set<Id> recordIds){
        return (List<Bank_Details__c>) selectSObjectsById(recordIds);
    }
    public List<Bank_Details__c > selectByLoanApplicationId(Set<Id> loanApplication){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Application__c  IN : loanApplication AND Is_Primary_Repayment_Account__c = true' );
        query.selectField('RecordType.Name'); 
        query.selectField('RecordType.DeveloperName');
        return (List<Bank_Details__c >) Database.query(query.toSOQL());
    }
    
}