force-app/main/default/objects/Bank_Details__c/Bank_Details__c.object-meta.xml
<CustomObject>
    <label>Bank Details</label>
    <nameField>
        <displayFormat>BA-{000000}</displayFormat>
        <label>Bank Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Details__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>Disbursement__c</referenceTo>
    <relationshipLabel>Bank Details</relationshipLabel>
    <relationshipName>Bank_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bank_Details__c/recordTypes/Disbursement.recordType-meta.xml
<RecordType>
    <fullName>Disbursement</fullName>
    <active>true</active>
    <label>Disbursement</label>
</RecordType>

force-app/main/default/objects/Bank_Details__c/recordTypes/Repayment.recordType-meta.xml
<RecordType>
    <fullName>Repayment</fullName>
    <active>true</active>
    <label>Repayment</label>
</RecordType>

force-app/main/default/objects/Disbursement__c/Disbursement__c.object-meta.xml
<CustomObject>
    <label>Disbursement</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Disbursements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Disbursement__c/recordTypes/BL.recordType-meta.xml
<RecordType>
    <fullName>BL</fullName>
    <active>true</active>
    <label>BL</label>
</RecordType>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/recordTypes/BL_Individual.recordType-meta.xml
<RecordType>
    <fullName>BL_Individual</fullName>
    <active>true</active>
    <label>BL Individual</label>
</RecordType>

force-app/main/default/objects/Loan_Applicant__c/recordTypes/BL_Non_Individual.recordType-meta.xml
<RecordType>
    <fullName>BL_Non_Individual</fullName>
    <active>true</active>
    <label>BL Non Individual</label>
</RecordType>

force-app/main/default/objects/Loan_Applicant__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Valuation__c/Valuation__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Valuation__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>Disbursement__c</referenceTo>
    <relationshipLabel>Activity</relationshipLabel>
    <relationshipName>Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/recordTypes/Office_FI.recordType-meta.xml
<RecordType>
    <fullName>Office_FI</fullName>
    <active>true</active>
    <label>Office FI</label>
</RecordType>

force-app/main/default/objects/Valuation__c/recordTypes/Permanent_FI.recordType-meta.xml
<RecordType>
    <fullName>Permanent_FI</fullName>
    <active>true</active>
    <label>Permanent FI</label>
</RecordType>

force-app/main/default/objects/Valuation__c/recordTypes/RCU.recordType-meta.xml
<RecordType>
    <fullName>RCU</fullName>
    <active>true</active>
    <label>RCU</label>
</RecordType>

force-app/main/default/objects/Valuation__c/recordTypes/Residence_FI.recordType-meta.xml
<RecordType>
    <fullName>Residence_FI</fullName>
    <active>true</active>
    <label>Residence FI</label>
</RecordType>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Disbursement__c.field-meta.xml
<CustomField>
    <fullName>Disbursement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Disbursement</label>
    <referenceTo>Disbursement__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification_Line_Item__c/Verification_Line_Item__c.object-meta.xml
<CustomObject>
    <description>Verification Line Item</description>
    <label>Verification Line Item</label>
    <nameField>
        <displayFormat>VLI-{0000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verification Line Items</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification_Line_Item__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verification Line Items</relationshipLabel>
    <relationshipName>Verification_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification_Line_Item__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Verification Line Items</relationshipLabel>
    <relationshipName>Verification_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BL_ConstantsUtil.cls
/**
* @File Name          : BL_ConstantsUtil.cls
* @Description        : This class will have all the constants defined to be used in various other classes
* @Author             : Mohit
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         04-07-2024            Mohit Saxena             Initial Version
**/
public class BL_ConstantsUtil {
    public static final String LOB_BL = 'BL';
    public static final String FLOATING_INTEREST_TYPE = 'Floating';
    public static final String PORTAL_PROFILE_NAME_BL = 'USFB BL - Partner Community User';
    public static final String BL_LEMS_LEAD_RECORDTYPE = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('BL LeMS Lead').getRecordTypeId();
    public static final String BL_Partner_Portal_Lead_RecordType = Schema.SObjectType.Lead__c.getRecordTypeInfosByName().get('BL Partner Portal Lead').getRecordTypeId();
    public static final String BL_DISBURSEMENT_RECORD_TYPE = Schema.SObjectType.Disbursement__c.getRecordTypeInfosByDeveloperName().get('BL').getRecordTypeId();
    public static final String BL_PRODUCT_CATEGORY = 'Business Loan';
    public static final String BUSINESS_LOAN_PLUS_CATEGORY = 'Business Loan Plus';
    public static final String SOLE_PROPRIETORSHIP_CONSTITUTION = 'Sole Proprietorship';
    public static final String INDIVIDUAL_CONSTITUTION = 'Individual';
    public static final String APPLICANT = 'Applicant';
    public static final String BL_CO_APPLICANT = 'Co-Applicant';
    public static final String BL_GAURANTOR = 'Guarantor';
    public static final String BL_INDIVIDUAL = 'BL Individual';
    public static final String BL_NON_INDIVIDUAL = 'BL Non Individual';
    public static final String BL_INDIVIDUAL_APPICANT_RECORD_TYPE = Schema.SObjectType.Loan_Applicant__c.getRecordTypeInfosByName().get('BL Individual').getRecordTypeId();
    public static final String BL_NON_INDIVIDUAL_APPICANT_RECORD_TYPE = Schema.SObjectType.Loan_Applicant__c.getRecordTypeInfosByName().get('BL Non Individual').getRecordTypeId();
    public static final String MCA_DOCUMENTS_VERIFICATION_RECORD_TYPE = Schema.SObjectType.Verification__c.getRecordTypeInfosByName().get('MCA-Documents').getRecordTypeId();
    public static final String CIBIL_OBLIGATION_VERIFY_LINE_ITEM_RECORD_TYPE = Schema.SObjectType.Verification_Line_Item__c.getRecordTypeInfosByName().get('CIBIL Obligation').getRecordTypeId();
    public static final String REPAYMENT_BANKING_DETAILS_RECORD_TYPE = Schema.SObjectType.Bank_Details__c.getRecordTypeInfosByName().get('Repayment').getRecordTypeId();
    
    public static final String COMPLETEDSTATUS = 'Completed';
    public static final String FAILED_STATUS = 'Failed';
    public static final String REST_API_TYPE = 'REST';
    public static final List<String> CATEGORYREQUIRED = new List<String>{'ARBE', 'CRGD', 'INC', 'CDRD', 'CETF', 'OTRE','LLPF','OTRA'};
        public static final String REJECTION_TYPE = 'Hard'; 
    public static final String LOGIN = 'Login';
    public static final String REJECTION_LETTER = 'Rejection_Letter_BL';
    public static final String MCA_API = 'MCA_API';
    public static final String OFFICE_ADDRESS = 'Office Address';
    public static final String RESIDENCE_ADDRESS = 'Residence Address';
    public static final String PERMANENT_ADDRESS = 'Permanent Address';
    public static final Set<String> ACTIVITY_RECORDTYPE_NAME_LIST = new Set<String>{'Office FI', 'Residence FI'};
        public static final String VERIFIED_ERROR = 'Acknowledge/Verify all required documents in Document Checklist';
    
    public static final String PERMANENT_FI_APP_VALLIDATION  = 'Please kindly Initiate Permanent FI for Primary Applicant.'; 
    public static final String RESIDENCE_FI_APP_VALLIDATION  = 'Please kindly Initiate Residence FI for Primary Applicant.'; 
    public static final String OFFICE_FI_APP_VALLIDATION  = 'Please kindly Initiate Office FI for Primary Applicant.'; 
    
    public static final String PERMANENT_FI_CO_APP_VALLIDATION  = 'Please kindly Initiate Permanent FI for Co Applicant.'; 
    public static final String RESIDENCE_FI_CO_APP_VALLIDATION  = 'Please kindly Initiate Residence FI for Co Applicant.'; 
    public static final String OFFICE_FI_CO_APP_VALLIDATION  = 'Please kindly Initiate Office FI for Co Applicant.'; 
    
    public static final String PERMANENT_FI_GUARANT_VALLIDATION  = 'Please kindly Initiate Permanent FI for Guarantor.'; 
    public static final String RESIDENCE_FI_GUARANT_VALLIDATION  = 'Please kindly Initiate Residence FI for Guarantor.'; 
    public static final String OFFICE_FI_GUARANT_VALLIDATION  = 'Please kindly Initiate Office FI for Guarantor.'; 
    
    public static final String RESIDENCE_FI  = 'Residence FI'; 
    public static final String OFFICE_FI  = 'Office FI'; 
    public static final String AADHAAR_IDENTITY_PROOF = 'UID (Aadhaar)';
    public static final String PERMANENT_FI  = 'Permanent FI'; 
    public static final String RCU  = 'RCU'; 
    public static final String AUTHORISED_SIGNATORY_TYPE = 'Authorised Signatory'; 
    public static final String RCU_VENDOR_RECORDTYPE = Schema.SObjectType.Valuation__c.getRecordTypeInfosByName().get('RCU Vendor').getRecordTypeId();
    public static final String REFERENCE_ERROR  = 'Please add at least 2 references for this application'; 
    public static final String BANK_ERROR  = 'Please add Repayment & Disbursement Bank Details'; 
    public static final String DISBURSEMENT  = 'Disbursement'; 
    public static final String REPAYMENT  = 'Repayment'; 
    public static final String RCU_ACTIVITY_MSG  = 'Please initiate RCU Activity.'; 
    public static final String BANKING_ANALYSIS_ERROR  = 'Please initiate the banking analysis for <b>'; 
    public static final String IS_COMM_YES  = ': Is Communication must be Yes for any one address.'; 
}