force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Rejected_By__c.field-meta.xml
<CustomField>
    <fullName>Rejected_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rejected By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Status__c</fullName>
    <label>Loan Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
            <value>
                <fullName>Revoke</fullName>
            </value>
            <value>
                <fullName>Query Raised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Rejected_By__c.field-meta.xml
<CustomField>
    <fullName>Rejected_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rejected By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Loan_Applications5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UB_RelookController.cls
/**
* @File Name          : UB_RelookController.cls
* @Description        : This class use to relook rejected records.
* @Author             : Kamal Hussain
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         02-04-2024            Kamal Hussain           Initial Version           
**/
public class UB_RelookController {

    // rellok lead functionality
    @AuraEnabled
    public static void relookLead(string leadId, string comment) {
            system.debug(leadId);
            system.debug(comment);
            lead__c leadRec = [SELECT Id, Rejected_By__c,Comment__c, Lead_Status__c, ownerId FROM lead__c WHERE Id =:leadId];
            leadRec.Lead_Status__c = 'Active';
            leadRec.ownerId = leadRec.Rejected_By__c;
            leadRec.Rejected_By__c = null;
            leadRec.Comment__c = comment;
            update leadRec;
    }

    // rellok loan application functionality
    @AuraEnabled
    public static void relookApplication(string applicationId, string comment) {
            try{
                system.debug('==================');
                Loan_Application__c appliRec = [SELECT Id, Rejected_By__c,Comment__c, ownerId, Loan_Application_Status__c FROM Loan_Application__c WHERE Id =:applicationId];
                appliRec.Loan_Application_Status__c = 'Active';
                appliRec.Comment__c = comment;
                appliRec.ownerId = appliRec.Rejected_By__c;
                appliRec.Rejected_By__c = null;
                update appliRec;
            }catch(Exception e){
                String customMessge = e.getMessage();
                Integer startIndex = customMessge.indexOf('FIELD_CUSTOM_VALIDATION_EXCEPTION');
                if (startIndex != -1) {
                        startIndex += 'FIELD_CUSTOM_VALIDATION_EXCEPTION'.length() + 2;
                        customMessge =  'ERROR: '+customMessge.substring(startIndex);
                }else{
                        Integer startIndex1 = customMessge.indexOf('INVALID_CROSS_REFERENCE_KEY');
                        if(startIndex1 != -1){
                                startIndex1 += 'INVALID_CROSS_REFERENCE_KEY'.length() + 2;
                                customMessge =  'ERROR: '+customMessge.substring(startIndex1);
                        }
                }
                //return customMessge;
                throw new AuraHandledException(customMessge);
            }
            
    }
}