force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LeMS_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>LeMS_Lead_ID__c</fullName>
    <description>This will be auto-populated by the UB_SyncLeadService API class.</description>
    <label>LeMS Lead ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Duplicate_LAF_Id__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_LAF_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dedupe Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Status__c</fullName>
    <label>Loan Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
            <value>
                <fullName>Revoke</fullName>
            </value>
            <value>
                <fullName>Query Raised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Messages_Config__mdt/Messages_Config__mdt.object-meta.xml
<CustomObject>
    <label>Messages Config</label>
    <pluralLabel>Messages Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Messages_Config__mdt/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UB_GetLoanDetailsService.cls
/**
* @File Name          : UB_GetLoanDetailsService.cls
* @Description        : Api to get loan Application / Lead  Details.
* @Author             : Zafaruddin
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         26-03-2024           Zafaruddin         Initial Version
*/

@RestResource(urlMapping='/LoanStatus/*')
global with sharing class UB_GetLoanDetailsService {
    
    
    /**
    * @description function will get Lead/Loan Status .
    * @author Zafaruddin | 04-15-2024 
    **/
    @HttpGet
    global static void getLoanStatus() {
        Savepoint sp = Database.setSavepoint();
        Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('LoanGetDetailsService');
        try {
            RestRequest req = RestContext.request;
            System.debug('AAAAAAAA2222  '+req.params.get('leadId'));
            if(req.params.get('leadId') == null) {
                RestContext.response.statusCode = 400;
                RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('LeMS_LeadId_is_not_Passed_in_WebService').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('LeMS_LeadId_is_not_Passed_in_WebService').Message__c + '") }');
                return ;
            }
            List<Lead__c> leadList = [SELECT Id,Lead_Status__c, (SELECT Id,Loan_Application_Status__c FROM Loan_Applications__r) FROM Lead__c WHERE LeMS_Lead_ID__c =:req.params.get('leadId')];
            System.debug('leadList   '+leadList);
            if(leadList.isEmpty()) {
                RestContext.response.statusCode = 404;
                RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('Lead_Record_Not_Found').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('Lead_Record_Not_Found').Message__c + '") }');
                return ;
            }
            String status;
            if(!leadList[0].Loan_Applications__r.isEmpty() && leadList[0].Loan_Applications__r[0].Id !=  NULL) {
                status = String.valueOf(leadList[0].Loan_Applications__r[0].Loan_Application_Status__c);
            } else {
                status = String.valueOf(leadList[0].Lead_Status__c);
            }
            RestContext.response.statusCode = 200;
            RestContext.response.responseBody = Blob.valueOf('{ "status":"success", "loanStatus":"' + status + '" ,  "responseType": "' + messageConfigMap.get('Loan_Status_Return').Message_Type__c + '" , "Messages": "' + messageConfigMap.get('Loan_Status_Return').Message__c + '") }');
        	} catch(Exception e) {
            Database.rollback(sp);
            System.debug('Exception--->'+e.getMessage());
            System.debug('ERROR LINE NUMBER--->'+e.getLineNumber());
            // call method to create ExceptionLogRecord
            UB_CommonUtil.createExceptionLogRecord(e, UB_ConstantsUtil.LOB_CV);
            RestContext.response.statusCode = 406;
            RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('DevelopmentError_LoanGetDetailsService').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('DevelopmentError_LoanGetDetailsService').Message__c + '  : ' + e.getMessage() +   '") }');
        }
    }
     
   public class LoanDetails {
       public String LoanStatus;

   }
    
   global class ModelClass {
        public String status;
        public String responseMessage;
        public String loanStatus;
        public String responseType;

        public ModelClass() {
            status = '';
            responseMessage = '';
            loanStatus = NULL;
            responseType = '';
        }
    }
    
    
    public static ModelClass checkValidation(String Status , String Message, String responseType) {
        ModelClass modCls = new ModelClass();
        modCls.Status = Status;
        modcls.responseMessage = Message;
        modcls.responseType = responseType;
        return modCls;    
    }
        


}