force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New CV</fullName>
            </value>
            <value>
                <fullName>Used CV</fullName>
            </value>
            <value>
                <fullName>New CE</fullName>
            </value>
            <value>
                <fullName>Used CE</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Derogatory CIBIL</fullName>
            </value>
            <value>
                <fullName>Policy Norms not met</fullName>
            </value>
            <value>
                <fullName>Customer not Interested</fullName>
            </value>
            <value>
                <fullName>RCU Negative</fullName>
            </value>
            <value>
                <fullName>FI Negative by Agency</fullName>
            </value>
            <value>
                <fullName>Any Other Reasons</fullName>
            </value>
            <value>
                <fullName>System Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Reject_Sub_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Sub_Reason__c</fullName>
    <label>Reject Sub Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reject_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recent OD and High DPD in the current running accounts.</fullName>
            </value>
            <value>
                <fullName>SUB / SMA / High DPD / account in the closed loan of CV / CE</fullName>
            </value>
            <value>
                <fullName>Fleet Expansion Not As Per Norms</fullName>
            </value>
            <value>
                <fullName>FFR Norms not met</fullName>
            </value>
            <value>
                <fullName>Experience norms not met</fullName>
            </value>
            <value>
                <fullName>Insufficient Credit History</fullName>
            </value>
            <value>
                <fullName>Credit PD Negative</fullName>
            </value>
            <value>
                <fullName>Poor Repayment</fullName>
            </value>
            <value>
                <fullName>Out of GEO Limit</fullName>
            </value>
            <value>
                <fullName>Age norms not met</fullName>
            </value>
            <value>
                <fullName>Financial norms not met (Captive Profile)</fullName>
            </value>
            <value>
                <fullName>Asking for lower Roi</fullName>
            </value>
            <value>
                <fullName>Asking for Higher funding - Ltv / Loan amount</fullName>
            </value>
            <value>
                <fullName>Client withdrawal due to change in the plan</fullName>
            </value>
            <value>
                <fullName>Document does not complete by client</fullName>
            </value>
            <value>
                <fullName>Profile Decline</fullName>
            </value>
            <value>
                <fullName>Document Decline</fullName>
            </value>
            <value>
                <fullName>FI Negative</fullName>
            </value>
            <value>
                <fullName>Any other reasons</fullName>
            </value>
            <value>
                <fullName>Customer denied the consent</fullName>
            </value>
            <value>
                <fullName>Duplicate Record</fullName>
            </value>
            <value>
                <fullName>Sanction Letter Expired</fullName>
            </value>
            <value>
                <fullName>CIBIL score below acceptable range</fullName>
            </value>
            <value>
                <fullName>Complete Documents not provided by the client</fullName>
            </value>
            <value>
                <fullName>Any other reasons not define above will update in this remarks column.</fullName>
                <isActive>false</isActive>
                <label>Any other reasons not define above will update in this remarks column.</label>
            </value>
            <value>
                <fullName>Client Withdrawal currently change the plan.</fullName>
                <isActive>false</isActive>
                <label>Client Withdrawal currently change the plan.</label>
            </value>
            <value>
                <fullName>Insufficient credit cistory</fullName>
                <isActive>false</isActive>
                <label>Insufficient credit cistory</label>
            </value>
            <value>
                <fullName>Negative credit PD</fullName>
                <isActive>false</isActive>
                <label>Negative credit PD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Name__c</fullName>
    <formula>IF( NOT(ISBLANK(First_Name__c)) , First_Name__c, &apos;&apos;) + &apos; &apos; + IF( NOT(ISBLANK(Middle_Name__c)) , Middle_Name__c, &apos;&apos;) + &apos; &apos; + IF( NOT(ISBLANK(Last_Name__c)) , Last_Name__c, &apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Co-Applicant</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/BL_Product_Category__c.field-meta.xml
<CustomField>
    <fullName>BL_Product_Category__c</fullName>
    <formula>TEXT(Lead__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Derogatory CIBIL</fullName>
            </value>
            <value>
                <fullName>Policy Norms not met</fullName>
            </value>
            <value>
                <fullName>Customer not Interested</fullName>
            </value>
            <value>
                <fullName>RCU Negative</fullName>
            </value>
            <value>
                <fullName>FI Negative by Agency</fullName>
            </value>
            <value>
                <fullName>Any Other Reasons</fullName>
            </value>
            <value>
                <fullName>System Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Reject_Sub_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Sub_Reason__c</fullName>
    <label>Reject Sub Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reject_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Recent OD and High DPD in the current running accounts.</fullName>
            </value>
            <value>
                <fullName>SUB / SMA / High DPD / account in the closed loan of CV / CE</fullName>
            </value>
            <value>
                <fullName>Fleet Expansion Not As Per Norms</fullName>
            </value>
            <value>
                <fullName>FFR Norms not met</fullName>
            </value>
            <value>
                <fullName>Experience norms not met</fullName>
            </value>
            <value>
                <fullName>Insufficient Credit History</fullName>
            </value>
            <value>
                <fullName>Credit PD Negative</fullName>
            </value>
            <value>
                <fullName>Poor Repayment</fullName>
            </value>
            <value>
                <fullName>Out of GEO Limit</fullName>
            </value>
            <value>
                <fullName>Age norms not met</fullName>
            </value>
            <value>
                <fullName>Financial norms not met (Captive Profile)</fullName>
            </value>
            <value>
                <fullName>Asking for lower Roi</fullName>
            </value>
            <value>
                <fullName>Asking for Higher funding - Ltv / Loan amount</fullName>
            </value>
            <value>
                <fullName>Client withdrawal due to change in the plan</fullName>
            </value>
            <value>
                <fullName>Document does not complete by client</fullName>
            </value>
            <value>
                <fullName>Profile Decline</fullName>
            </value>
            <value>
                <fullName>Document Decline</fullName>
            </value>
            <value>
                <fullName>FI Negative</fullName>
            </value>
            <value>
                <fullName>Any other reasons</fullName>
            </value>
            <value>
                <fullName>Customer denied the consent</fullName>
            </value>
            <value>
                <fullName>Duplicate Record</fullName>
            </value>
            <value>
                <fullName>Sanction Letter Expired</fullName>
            </value>
            <value>
                <fullName>CIBIL score below acceptable range</fullName>
            </value>
            <value>
                <fullName>Complete Documents not provided by the client</fullName>
            </value>
            <value>
                <fullName>Duplicate record rejected within 60 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BL_RejectionLetterCltr.cls
/**
* @File Name          : BL_RejectionLetterCltr.cls
* @Description        : This class use to map sanction lettee .
* @Author             : Lakshya Verma
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         01-08-2024            Lakshya Verma         Initial Version           
**/
public class BL_RejectionLetterCltr {
    public String plainHTML { get; set; }
    public String loanId{get;set;}   
    public List<Loan_Application__c> loanAppObj { get; set; }
    public String todayDate { get; set; }
    //public BL_RejectionLetterCltr(ApexPages.StandardController controller) {
        //loanId = apexpages.currentPage().getParameters().get('Id');
    //}
    //
    
    public List<Loan_Application__c> getLoanDetails() {
        if (this.loanId != null && String.isNotEmpty(this.loanId)){
            loanAppObj = [SELECT Id, Name,Lead__r.CreatedDate,Reject_Sub_Reason__c,Reject_Reason__c, BL_Product_Category__c,
                                      (SELECT Id, Name,Applicant_Name__c,Applicant_Type__c FROM Loan_Applicants__r WHERE Applicant_Type__c = 'Applicant' ), 
                                      (SELECT Id, Product_Category__c FROM Products__r LIMIT 1) 
                                      FROM Loan_Application__c 
                                      WHERE Id =: this.loanId];
            System.debug('**loanAppObj->   '+loanAppObj );
            if(!loanAppObj.isEmpty()){
                todayDate = String.valueOf(Date.today().day()).leftPad(2, '0') + '/' +
                    String.valueOf(Date.today().month()).leftPad(2, '0') + '/' +
                    String.valueOf(Date.today().year());
                System.debug('>>>>>> ' + !loanAppObj[0].Loan_Applicants__r.isEmpty());
                
                EmailTemplate tempID = [SELECT Id,Name,Body,HTMLValue FROM EmailTemplate WHERE DeveloperName  =: BL_ConstantsUtil.REJECTION_LETTER];
                String emailBody = tempID.Body;
                //mapping vehicle details
                
                emailBody = emailBody.replace('{rec.Name}', loanAppObj[0].name);
                emailBody = emailBody.replace('{rec1.Name}', loanAppObj[0].name  );
                emailBody = emailBody.replace('{dated}', todayDate);
                emailBody = emailBody.replace('{Date}', todayDate);
                emailBody = emailBody.replace('{product.Product_Category__c}', loanAppObj[0].BL_Product_Category__c);
                System.debug('emailBody after change>   '+ emailBody );
                return loanAppObj;
            } 
        }
        RETURN null;
    }
    
    public void getPDF(){
        try {
            loanId = apexpages.currentPage().getParameters().get('Id');
            System.debug('VALUEEEEEEEEEEEEE  '+loanId);
            plainHTML = createEmailBody(loanId);
        }catch(Exception e) {
            System.debug('ERRORRRRRRRRRR    '+e.getMessage());
            System.debug('Line   No'+e.getLineNumber());
        }
    }
    
    public static String createEmailBody(String loanApplicationId){
        String productCat = '';
        String ApplicantId= '';
        datetime d = system.today();
        String todayDate = String.valueOf(Date.today().day()).leftPad(2, '0') + '/' +
            String.valueOf(Date.today().month()).leftPad(2, '0') + '/' +
            String.valueOf(Date.today().year());
        system.debug('todayDate >  ' + todayDate);
        List<Loan_Application__c>  loanAppObj = new UB_LoanApplicationsSelector().selectById(new Set<Id>{loanApplicationId});
        
        System.debug('**loanAppObj->   '+loanAppObj );
        if(!loanAppObj.isEmpty()){
            System.debug('>>>>>> ' + !loanAppObj[0].Loan_Applicants__r.isEmpty());
           
            EmailTemplate tempID = [SELECT Id,Name,Body,HTMLValue FROM EmailTemplate WHERE DeveloperName  =: BL_ConstantsUtil.REJECTION_LETTER];
            String emailBody = tempID.Body;
            //mapping vehicle details
            
            emailBody = emailBody.replace('{rec.Name}', loanAppObj[0].name);
            emailBody = emailBody.replace('{rec1.Name}', loanAppObj[0].name  );
            emailBody = emailBody.replace('{dated}', todayDate);
            emailBody = emailBody.replace('{Date}', todayDate);
            emailBody = emailBody.replace('{product.Product_Category__c}', loanAppObj[0].BL_Product_Category__c);
            System.debug('emailBody after change>   '+ emailBody );
            return emailBody;
        } 
        return null;
    }
}