force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <label>GUID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Derogatory CIBIL</fullName>
            </value>
            <value>
                <fullName>Policy Norms not met</fullName>
            </value>
            <value>
                <fullName>Customer not Interested</fullName>
            </value>
            <value>
                <fullName>RCU Negative</fullName>
            </value>
            <value>
                <fullName>FI Negative by Agency</fullName>
            </value>
            <value>
                <fullName>Any Other Reasons</fullName>
            </value>
            <value>
                <fullName>System Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Reject_Sub_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Sub_Reason__c</fullName>
    <label>Reject Sub Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reject_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recent OD and High DPD in the current running accounts.</fullName>
            </value>
            <value>
                <fullName>SUB / SMA / High DPD / account in the closed loan of CV / CE</fullName>
            </value>
            <value>
                <fullName>Fleet Expansion Not As Per Norms</fullName>
            </value>
            <value>
                <fullName>FFR Norms not met</fullName>
            </value>
            <value>
                <fullName>Experience norms not met</fullName>
            </value>
            <value>
                <fullName>Insufficient Credit History</fullName>
            </value>
            <value>
                <fullName>Credit PD Negative</fullName>
            </value>
            <value>
                <fullName>Poor Repayment</fullName>
            </value>
            <value>
                <fullName>Out of GEO Limit</fullName>
            </value>
            <value>
                <fullName>Age norms not met</fullName>
            </value>
            <value>
                <fullName>Financial norms not met (Captive Profile)</fullName>
            </value>
            <value>
                <fullName>Asking for lower Roi</fullName>
            </value>
            <value>
                <fullName>Asking for Higher funding - Ltv / Loan amount</fullName>
            </value>
            <value>
                <fullName>Client withdrawal due to change in the plan</fullName>
            </value>
            <value>
                <fullName>Document does not complete by client</fullName>
            </value>
            <value>
                <fullName>Profile Decline</fullName>
            </value>
            <value>
                <fullName>Document Decline</fullName>
            </value>
            <value>
                <fullName>FI Negative</fullName>
            </value>
            <value>
                <fullName>Any other reasons</fullName>
            </value>
            <value>
                <fullName>Customer denied the consent</fullName>
            </value>
            <value>
                <fullName>Duplicate Record</fullName>
            </value>
            <value>
                <fullName>Sanction Letter Expired</fullName>
            </value>
            <value>
                <fullName>CIBIL score below acceptable range</fullName>
            </value>
            <value>
                <fullName>Complete Documents not provided by the client</fullName>
            </value>
            <value>
                <fullName>Any other reasons not define above will update in this remarks column.</fullName>
                <isActive>false</isActive>
                <label>Any other reasons not define above will update in this remarks column.</label>
            </value>
            <value>
                <fullName>Client Withdrawal currently change the plan.</fullName>
                <isActive>false</isActive>
                <label>Client Withdrawal currently change the plan.</label>
            </value>
            <value>
                <fullName>Insufficient credit cistory</fullName>
                <isActive>false</isActive>
                <label>Insufficient credit cistory</label>
            </value>
            <value>
                <fullName>Negative credit PD</fullName>
                <isActive>false</isActive>
                <label>Negative credit PD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>IF(ISBLANK(Entity_Name__c ), First_Name__c +&apos; &apos;+ Middle_Name__c +&apos; &apos;+ Last_Name__c , Entity_Name__c )</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Derogatory CIBIL</fullName>
            </value>
            <value>
                <fullName>Policy Norms not met</fullName>
            </value>
            <value>
                <fullName>Customer not Interested</fullName>
            </value>
            <value>
                <fullName>RCU Negative</fullName>
            </value>
            <value>
                <fullName>FI Negative by Agency</fullName>
            </value>
            <value>
                <fullName>Any Other Reasons</fullName>
            </value>
            <value>
                <fullName>System Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Reject_Sub_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Sub_Reason__c</fullName>
    <label>Reject Sub Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reject_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Recent OD and High DPD in the current running accounts.</fullName>
            </value>
            <value>
                <fullName>SUB / SMA / High DPD / account in the closed loan of CV / CE</fullName>
            </value>
            <value>
                <fullName>Fleet Expansion Not As Per Norms</fullName>
            </value>
            <value>
                <fullName>FFR Norms not met</fullName>
            </value>
            <value>
                <fullName>Experience norms not met</fullName>
            </value>
            <value>
                <fullName>Insufficient Credit History</fullName>
            </value>
            <value>
                <fullName>Credit PD Negative</fullName>
            </value>
            <value>
                <fullName>Poor Repayment</fullName>
            </value>
            <value>
                <fullName>Out of GEO Limit</fullName>
            </value>
            <value>
                <fullName>Age norms not met</fullName>
            </value>
            <value>
                <fullName>Financial norms not met (Captive Profile)</fullName>
            </value>
            <value>
                <fullName>Asking for lower Roi</fullName>
            </value>
            <value>
                <fullName>Asking for Higher funding - Ltv / Loan amount</fullName>
            </value>
            <value>
                <fullName>Client withdrawal due to change in the plan</fullName>
            </value>
            <value>
                <fullName>Document does not complete by client</fullName>
            </value>
            <value>
                <fullName>Profile Decline</fullName>
            </value>
            <value>
                <fullName>Document Decline</fullName>
            </value>
            <value>
                <fullName>FI Negative</fullName>
            </value>
            <value>
                <fullName>Any other reasons</fullName>
            </value>
            <value>
                <fullName>Customer denied the consent</fullName>
            </value>
            <value>
                <fullName>Duplicate Record</fullName>
            </value>
            <value>
                <fullName>Sanction Letter Expired</fullName>
            </value>
            <value>
                <fullName>CIBIL score below acceptable range</fullName>
            </value>
            <value>
                <fullName>Complete Documents not provided by the client</fullName>
            </value>
            <value>
                <fullName>Duplicate record rejected within 60 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Consent__c.field-meta.xml
<CustomField>
    <fullName>Consent__c</fullName>
    <label>Consent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Verification__c/fields/GUID__c.field-meta.xml
<CustomField>
    <fullName>GUID__c</fullName>
    <label>GUID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>OTP Sent</fullName>
            </value>
            <value>
                <fullName>OTP Attempt Failed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UB_ConsentService.cls
/**
* @File Name          : UB_ConsentService.cls
* @Description        : Api to update customer consent on verification log.
* @Author             : Zafaruddin
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         22-05-2024           Zafaruddin         Initial Version
*/

@RestResource(urlMapping='/consent/*')
global with sharing class UB_ConsentService {

    /**
    * @description  : Methid will post leMS lead into Salesforce.
    * @author Zafaruddin | 04-15-2024 
    **/
    @HttpPOST
    global static void getCustomerConsent() {
        Savepoint sp = Database.setSavepoint();
        try {
            RestRequest req = RestContext.request;
            Map<String,Object> RequestMap = (Map<String,Object>)JSON.deserializeUntyped(req.requestBody.tostring());
            System.debug('GUIDDDD  '+RequestMap.get('guid'));
            System.debug('GUIDDDD  '+String.valueOf(RequestMap.get('guid')).length());

            if(String.valueOf(RequestMap.get('guid')).length() == 0 ) {
                RestContext.response.statusCode = 404;
                RestContext.response.responseBody = Blob.valueOf('{ "status":"fail" , "Messages": " GUI is Blank." }');
                return ;
            }
            String guid =  RequestMap.get('guid') != NULL? String.valueOf(RequestMap.get('guid')) : null;
            List<Verification__c> VerificationList = [SELECT Id, Status__c,Consent__c,OwnerId,Lead__c,Loan_Applicant__c,Loan_Applicant__r.Account_Name__c,Loan_Applicant__r.Loan_Application__r.Name,Loan_Applicant__r.Loan_Application__r.Id,Loan_Applicant__r.Loan_Application__r.OwnerId FROM Verification__c  WHERE GUID__c=:guid Order By Name DESC];
            String profileName=[Select Id,profile.name from user where Id=:VerificationList[0].OwnerId].profile.name; 
            if(!VerificationList.isEmpty()){
                if(VerificationList[0].Lead__c != NULL && RequestMap.get('consent') == 'No') {
                    Lead__c lead = new Lead__c();
                    lead.Id = VerificationList[0].Lead__c;
                    lead.Lead_Status__c = UB_ConstantsUtil.REJECT_LOAN_STATUS;
                    lead.Reject_Reason__c = UB_ConstantsUtil.SYSTEM_REJECT ;
                    lead.Reject_Sub_Reason__c = UB_ConstantsUtil.LEAD_SUB_REJECT;
                    lead.Rejected_By__c = VerificationList[0].OwnerId;
                    lead.Consent_Received__c = true;
                    // code for portal user
                    System.debug('PROFILE NAME   '+profileName);
                    if(profileName == UB_ConstantsUtil.PORTAL_PROFILE_NAME) {
                        lead.OwnerId = [SELECT Id, ManagerId FROm USER WHERE Id=:VerificationList[0].OwnerId].ManagerId; 
                        System.debug('DSA MANAGER '+lead.OwnerId );
                    }
                    update lead ;
                } else if(VerificationList[0].Lead__c != NULL && RequestMap.get('consent') == 'Yes') {
                    Lead__c lead = new Lead__c();
                    lead.Id = VerificationList[0].Lead__c;
                    lead.Consent_Received__c = true;
                    update lead ;
                } else if(VerificationList[0].Loan_Applicant__c != NULL && RequestMap.get('consent') == 'Yes') {
                    Loan_Applicant__c applicant = new Loan_Applicant__c();
                    applicant.Id = VerificationList[0].Loan_Applicant__c;
                    applicant.Consent_Received__c = true;
                    update applicant ;
                } else if (VerificationList[0].Loan_Applicant__c != NULL && RequestMap.get('consent') == 'No'){
                    system.debug('Notification Condition');
                    UB_CommonUtil.sendNotification('Consent is Failed  for ' + VerificationList[0].Loan_Applicant__r.Account_Name__c + ' on Application ' + VerificationList[0].Loan_Applicant__r.Loan_Application__r.Name  ,'Consent Failed','Lead_Owner_Change',VerificationList[0].Loan_Applicant__r.Loan_Application__r.Id,VerificationList[0].Loan_Applicant__r.Loan_Application__r.OwnerId);
                }
                //update consent on verification record. 
                VerificationList[0].Consent__c = String.valueOf(RequestMap.get('consent'));
                VerificationList[0].Status__c = UB_ConstantsUtil.COMPLETEDSTATUS;
                update VerificationList;

                RestContext.response.statusCode = 200;
                RestContext.response.responseBody = Blob.valueOf('{ "status":"success" , "Messages": " Consent Update Successfully. " }');
               
                
            }
            System.debug('Request Body  '+req.requestBody.tostring());
            System.debug('RequestMap   '+RequestMap);

        }catch(Exception e) {
            //Database.rollback(sp);
            System.debug('Exception--->'+e.getMessage());
            System.debug('ERROR LINE NUMBER--->'+e.getLineNumber());
            // call method to create ExceptionLogRecord
            UB_CommonUtil.createExceptionLogRecord(e, UB_ConstantsUtil.LOB_CV);
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf('{ "status":"fail",   "errorMessages": "' + e.getMessage() +  '" }');
        } 
}



   
}