force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Derogatory CIBIL</fullName>
            </value>
            <value>
                <fullName>Policy Norms not met</fullName>
            </value>
            <value>
                <fullName>Customer not Interested</fullName>
            </value>
            <value>
                <fullName>RCU Negative</fullName>
            </value>
            <value>
                <fullName>FI Negative by Agency</fullName>
            </value>
            <value>
                <fullName>Any Other Reasons</fullName>
            </value>
            <value>
                <fullName>System Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Reject_Sub_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Sub_Reason__c</fullName>
    <label>Reject Sub Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reject_Reason__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recent OD and High DPD in the current running accounts.</fullName>
            </value>
            <value>
                <fullName>SUB / SMA / High DPD / account in the closed loan of CV / CE</fullName>
            </value>
            <value>
                <fullName>Fleet Expansion Not As Per Norms</fullName>
            </value>
            <value>
                <fullName>FFR Norms not met</fullName>
            </value>
            <value>
                <fullName>Experience norms not met</fullName>
            </value>
            <value>
                <fullName>Insufficient Credit History</fullName>
            </value>
            <value>
                <fullName>Credit PD Negative</fullName>
            </value>
            <value>
                <fullName>Poor Repayment</fullName>
            </value>
            <value>
                <fullName>Out of GEO Limit</fullName>
            </value>
            <value>
                <fullName>Age norms not met</fullName>
            </value>
            <value>
                <fullName>Financial norms not met (Captive Profile)</fullName>
            </value>
            <value>
                <fullName>Asking for lower Roi</fullName>
            </value>
            <value>
                <fullName>Asking for Higher funding - Ltv / Loan amount</fullName>
            </value>
            <value>
                <fullName>Client withdrawal due to change in the plan</fullName>
            </value>
            <value>
                <fullName>Document does not complete by client</fullName>
            </value>
            <value>
                <fullName>Profile Decline</fullName>
            </value>
            <value>
                <fullName>Document Decline</fullName>
            </value>
            <value>
                <fullName>FI Negative</fullName>
            </value>
            <value>
                <fullName>Any other reasons</fullName>
            </value>
            <value>
                <fullName>Customer denied the consent</fullName>
            </value>
            <value>
                <fullName>Duplicate Record</fullName>
            </value>
            <value>
                <fullName>Sanction Letter Expired</fullName>
            </value>
            <value>
                <fullName>CIBIL score below acceptable range</fullName>
            </value>
            <value>
                <fullName>Complete Documents not provided by the client</fullName>
            </value>
            <value>
                <fullName>Any other reasons not define above will update in this remarks column.</fullName>
                <isActive>false</isActive>
                <label>Any other reasons not define above will update in this remarks column.</label>
            </value>
            <value>
                <fullName>Client Withdrawal currently change the plan.</fullName>
                <isActive>false</isActive>
                <label>Client Withdrawal currently change the plan.</label>
            </value>
            <value>
                <fullName>Insufficient credit cistory</fullName>
                <isActive>false</isActive>
                <label>Insufficient credit cistory</label>
            </value>
            <value>
                <fullName>Negative credit PD</fullName>
                <isActive>false</isActive>
                <label>Negative credit PD</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Rejected_By__c.field-meta.xml
<CustomField>
    <fullName>Rejected_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rejected By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UB_RejectController.cls
/**
* @File Name          : UB_RejectController.cls
* @Description        : This class use to rejectLead stages.
* @Author             : Kamal Hussain
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         02-04-2024            Kamal Hussain           Initial Version           
**/
public class UB_RejectController {
     @AuraEnabled
    public static string rejectLead(string leadId, string reason, string subReason) {
            system.debug(leadId);
            system.debug(reason);
            system.debug(subReason);

            try{
            user userRec = [SELECT id, contact.account.Relationship_Manager__c FROM user WHERE id =:userInfo.getUserId()];
            string managerId = null;
            if(userRec.contact.account.Relationship_Manager__c !=null) {
                managerId = userRec.contact.account.Relationship_Manager__c;
            }    
            system.debug('managerId=='+managerId);
            lead__c leadRec = new lead__c();
            leadRec.id = leadId;
            leadRec.Lead_Status__c = 'Rejected';
            leadRec.Rejected_By__c = userInfo.getUserId();
            leadRec.Reject_Reason__c = reason;
            leadRec.Reject_Sub_Reason__c = subReason;
            if(managerId !=null)
                leadRec.OwnerId = managerId;
            
            update leadRec;

            }catch(exception e ) {
               system.debug('====='+e.getMessage());
               return e.getMessage();
            }

            return 'success';
            
           
    }
}