force-app/main/default/objects/Deviation_Master__c/Deviation_Master__c.object-meta.xml
<CustomObject>
    <label>Deviation Master</label>
    <nameField>
        <displayFormat>DEV-{00000000}</displayFormat>
        <label>Deviations Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deviation Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Deviation_Master__c/fields/Approving_Authority__c.field-meta.xml
<CustomField>
    <fullName>Approving_Authority__c</fullName>
    <label>Approving Authority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RCM</fullName>
            </value>
            <value>
                <fullName>ZCM</fullName>
            </value>
            <value>
                <fullName>NCM</fullName>
            </value>
            <value>
                <fullName>Credit Head</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation_Master__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation_Master__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CV-New</fullName>
            </value>
            <value>
                <fullName>CE-New</fullName>
            </value>
            <value>
                <fullName>CV-Used</fullName>
            </value>
            <value>
                <fullName>CE-Used</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation_Master__c/fields/Product_Schemes__c.field-meta.xml
<CustomField>
    <fullName>Product_Schemes__c</fullName>
    <label>Product Schemes</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTU &amp; FTB</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Institutional Strategic</fullName>
            </value>
            <value>
                <fullName>Captive Retail</fullName>
            </value>
            <value>
                <fullName>Captive Strategic</fullName>
            </value>
            <value>
                <fullName>Banking Surrogate</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>GPR</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation_Master__c/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <label>Product Sub Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transporter</fullName>
            </value>
            <value>
                <fullName>Bus Operator</fullName>
            </value>
            <value>
                <fullName>Captive</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Hirer</fullName>
            </value>
            <value>
                <fullName>Mine Owner</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/Deviation_Sanction_Condition__c.object-meta.xml
<CustomObject>
    <label>Deviation/Sanction Condition</label>
    <nameField>
        <displayFormat>DSC-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deviation/Sanction Conditions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Approving_Authority__c.field-meta.xml
<CustomField>
    <fullName>Approving_Authority__c</fullName>
    <label>Approving Authority</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Authority_Role__c.field-meta.xml
<CustomField>
    <fullName>Authority_Role__c</fullName>
    <label>Authority Role</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Decision__c.field-meta.xml
<CustomField>
    <fullName>Decision__c</fullName>
    <label>Decision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Sent for Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Deviations__c.field-meta.xml
<CustomField>
    <fullName>Deviations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deviations</label>
    <referenceTo>Deviation_Master__c</referenceTo>
    <relationshipLabel>Deviation/Sanction Conditions</relationshipLabel>
    <relationshipName>Deviation_Sanction_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Deviation_Sanction_Condition__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Deviation/Sanction Conditions</relationshipLabel>
    <relationshipName>Deviation_Sanction_Conditions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Master__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Schemes__c.field-meta.xml
<CustomField>
    <fullName>Product_Schemes__c</fullName>
    <formula>TEXT( Product__r.Product_Schemes__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Schemes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <formula>TEXT( Product__r.Product_Sub_Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Sub Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Master__c/Product_Master__c.object-meta.xml
<CustomObject>
    <label>Product Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Master__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CV-New</fullName>
            </value>
            <value>
                <fullName>CE-New</fullName>
            </value>
            <value>
                <fullName>CV-Used</fullName>
            </value>
            <value>
                <fullName>CE-Used</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Schemes__c.field-meta.xml
<CustomField>
    <fullName>Product_Schemes__c</fullName>
    <label>Product Schemes</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTU &amp; FTB</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Institutional Strategic</fullName>
            </value>
            <value>
                <fullName>Captive Retail</fullName>
            </value>
            <value>
                <fullName>Captive Strategic</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>GPR</fullName>
            </value>
            <value>
                <fullName>Banking Surrogate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <label>Product Sub Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transporter</fullName>
            </value>
            <value>
                <fullName>Bus Operator</fullName>
            </value>
            <value>
                <fullName>Captive</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Hirer</fullName>
            </value>
            <value>
                <fullName>Mine Owner</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial Vehicle Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Construction Equipment Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Tractor Loan</fullName>
        <isActive>false</isActive>
        <label>Tractor Loan</label>
    </customValue>
    <customValue>
        <fullName>Three Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Three Wheeler Loan</label>
    </customValue>
    <customValue>
        <fullName>Car Loan</fullName>
        <isActive>false</isActive>
        <label>Car Loan</label>
    </customValue>
    <customValue>
        <fullName>Office Equipment</fullName>
        <isActive>false</isActive>
        <label>Office Equipment</label>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
        <isActive>false</isActive>
        <label>Medical Equipment</label>
    </customValue>
    <customValue>
        <fullName>Two Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Two Wheeler Loan</label>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_ManualDeviationController.cls
public class UB_ManualDeviationController {
    public class FlowInputs{
        @InvocableVariable
        public String recordId;         
    }
    
    public class FlowReturns{
        @InvocableVariable
        public List<String> devRecordIds;         
    }
    
    @AuraEnabled
    public static ResponseWrapper recommendDeviations(String authorityName, String loanApplicationId){
        ResponseWrapper response = new ResponseWrapper();
        
        try{
            if(String.isNotBlank(authorityName) && String.isNotBlank(loanApplicationId)){
                List<Loan_Application__c> listApplication = [SELECT Id, OwnerId FROM Loan_Application__c WHERE Id =: loanApplicationId];
                if(listApplication != null && listApplication.size() > 0){
                    String userId = [SELECT Id, Userrole.name FROM User WHERE userrole.name =: authorityName LIMIT 1].Id;
                    listApplication[0].OwnerId = String.isNotBlank(userId) ? userId : null;
                    UPDATE listApplication;
                    response.isSuccess = true;
                    response.responseBody = 'Recommended Successfully!!';
                }else{
                    response.isSuccess = false;
                    response.responseBody = 'Something Went Wrong!!';
                }
            }
        }catch(Exception ex){
            system.debug('error' + ex.getLineNumber());
            system.debug('error' + ex.getMessage());
            response.isSuccess = false;
            response.responseBody =  JSON.serialize(ex.getMessage() + ex.getLineNumber() + ex.getStackTraceString() );
            return response;
        }
        RETURN response;
    }
        
    @AuraEnabled
    public static string getPendingDeviations(String loanApplicationId){
        String userRole = [SELECT Id, Userrole.name FROM User WHERE Id =: UserInfo.getUserId() LIMIT 1].Userrole.name;
        system.debug('userRole-> ' + userRole);
        String message = '';
        List<Deviation_Sanction_Condition__c> deviationConditionList = [select id, Loan_Application__c, Decision__c, Authority_Role__c, Approving_Authority__c 
                                                                        FROM Deviation_Sanction_Condition__c WHERE Loan_Application__c =: loanApplicationId 
                                                                        AND Authority_Role__c =: userRole
                                                                        AND Decision__c NOT IN ('Approved','Rejected') // (Decision__c != 'Approved' AND Decision__c != 'Rejected')
                                                                       ];
        if(deviationConditionList != null && deviationConditionList.size() > 0){
            message = 'Please submit decision for deviations which are owned by you or your subordinates.';
        }else{
            message = 'Success';
        }
        RETURN message;
    }
    @InvocableMethod(label='Get Manual Deviations')
    public static List<FlowReturns> getManualDeviations(List<FlowInputs> request){
        if(request.size() != null && request.size() > 0){
            String productScheme = '';
            String productCategory = '';
            String productSubCategory = '';
            //List<Deviations__c> deviationList = new List<Deviations__c>();
            List<String> deviationIds = new List<String>();
            List<FlowReturns> objFlowReturnsList = new List<FlowReturns>();
            FlowReturns objFlowReturns = new FlowReturns();
            if(String.isNotBlank(request[0].recordId)){
                List<Product__c> productList = [select id, Product_Schemes__c, Product_Category__c, 
                                                Product_Sub_Category__c, Product__r.LOB__c  
                                                FROM Product__c WHERE 
                                                Loan_Application__c =: request[0].recordId];
               /* for(Product__c productObj : [select id, Product_Schemes__c, Product_Category__c, 
                                             Product_Sub_Category__c, Product__r.LOB__c  
                                             FROM Product__c WHERE 
                                             Loan_Application__c =: request[0].recordId]){
                                                 productScheme += productObj.Product_Schemes__c +';';
                                                 productCategory += productObj.Product_Category__c +';';
                                                 productSubCategory += productObj.Product_Sub_Category__c +';';
                                             }*/
                
                //system.debug('productScheme-> ' + productScheme);
                //system.debug('productCategory-> ' + productCategory);
                //system.debug('productSubCategory-> ' + productSubCategory);
                if(productList != null && productList.size() > 0){
                    if(productList.size() == 1){
                        for(Deviation_Master__c devObj : [select id , Product_Schemes__c, Product_Category__c, Product_Sub_Category__c, LOB__c from Deviation_Master__c  
                                                          WHERE  Product_Schemes__c includes (:productList[0].Product_Schemes__c) 
                                                          AND Product_Category__c includes ( :productList[0].Product_Category__c) 
                                                          AND Product_Sub_Category__c includes (:productList[0].Product_Sub_Category__c) AND Active__c = true]){
                                                              deviationIds.add(devObj.Id);
                                                          }
                    }if(productList.size() == 2){
                        for(Deviation_Master__c devObj : [select id , Product_Schemes__c, Product_Category__c, Product_Sub_Category__c, LOB__c from Deviation_Master__c  
                                                          WHERE  (Product_Schemes__c includes (:productList[0].Product_Schemes__c) OR Product_Schemes__c includes (:productList[1].Product_Schemes__c))
                                                          AND (Product_Category__c includes ( :productList[0].Product_Category__c) OR Product_Category__c includes ( :productList[1].Product_Category__c))
                                                          AND (Product_Sub_Category__c includes (:productList[0].Product_Sub_Category__c) OR Product_Sub_Category__c includes (:productList[1].Product_Sub_Category__c)) AND Active__c = true]){
                                                              deviationIds.add(devObj.Id);
                                                          }
                    }
                }
                
                objFlowReturns.devRecordIds = deviationIds;
                objFlowReturnsList.add(objFlowReturns);
                system.debug('objFlowReturnsList-> ' + objFlowReturnsList.size());
                RETURn objFlowReturnsList;
            }
        }
        RETURN null;
    }
    
    public class ResponseWrapper{
        @AuraEnabled public Boolean isSuccess;
        @AuraEnabled public String responseBody;
    }
}