force-app/main/default/objects/Collateral__c/Collateral__c.object-meta.xml
<CustomObject>
    <label>Collateral</label>
    <nameField>
        <displayFormat>Col-{0000}</displayFormat>
        <label>Collateral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Collateral__c/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Loan_Applicant__c.Applicant_Type__c</field>
            <operation>notContain</operation>
            <value>Guarantor</value>
        </filterItems>
        <filterItems>
            <field>Loan_Applicant__c.Loan_Application__c</field>
            <operation>equals</operation>
            <valueField>$Source.Loan_Application__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Collateral</relationshipLabel>
    <relationshipName>Collateral</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Collateral__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Collateral</relationshipLabel>
    <relationshipName>Collateral</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{00000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Uploaded</fullName>
                <default>true</default>
                <label>Not Uploaded</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Submitted to CPA</fullName>
            </value>
            <value>
                <fullName>CPA Acknowledged</fullName>
            </value>
            <value>
                <fullName>CM Acknowledged</fullName>
            </value>
            <value>
                <fullName>RCU Acknowledged</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Not Received</fullName>
                <isActive>false</isActive>
                <label>Not Received</label>
            </value>
            <value>
                <fullName>OTC</fullName>
                <isActive>false</isActive>
                <label>OTC</label>
            </value>
            <value>
                <fullName>PDD</fullName>
                <isActive>false</isActive>
                <label>PDD</label>
            </value>
            <value>
                <fullName>Query Raised</fullName>
                <isActive>false</isActive>
                <label>Query Raised</label>
            </value>
            <value>
                <fullName>RCU Verified</fullName>
                <isActive>false</isActive>
                <label>RCU Verified</label>
            </value>
            <value>
                <fullName>Verified</fullName>
                <isActive>false</isActive>
                <label>Verified</label>
            </value>
            <value>
                <fullName>Waived Off</fullName>
                <isActive>false</isActive>
                <label>Waived Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Valuation__c.field-meta.xml
<CustomField>
    <fullName>Valuation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Valuation</label>
    <referenceTo>Valuation__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Current_Owner__c.field-meta.xml
<CustomField>
    <fullName>Current_Owner__c</fullName>
    <formula>IF( 
  ISBLANK(Owner:Queue.Id),
  Owner:User.FirstName &amp; &quot; &quot; &amp; Owner:User.LastName,
  Owner:Queue.QueueName
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/Valuation__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Valuation__c/fields/Collateral__c.field-meta.xml
<CustomField>
    <fullName>Collateral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral</label>
    <referenceTo>Collateral__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Comment__c.field-meta.xml
<CustomField>
    <fullName>Comment__c</fullName>
    <label>Manager Comments</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Current_Owner__c.field-meta.xml
<CustomField>
    <fullName>Current_Owner__c</fullName>
    <formula>IF(
ISBLANK(Owner:Queue.Id),
Owner:User.FirstName &amp; &quot; &quot; &amp; Owner:User.LastName,
Owner:Queue.QueueName
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Owner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Positive</fullName>
            </value>
            <value>
                <fullName>Refer to credit</fullName>
            </value>
            <value>
                <fullName>Refer to business</fullName>
            </value>
            <value>
                <fullName>Profile decline</fullName>
            </value>
            <value>
                <fullName>Document decline</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>RCU Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Query Raised</fullName>
            </value>
            <value>
                <fullName>Screened</fullName>
            </value>
            <value>
                <fullName>Sampled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Vendor_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Vendor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UB_ActivitySelector.cls
/**
* @File Name          : UB_ActivitySelector.cls
* @Description        : This class used to fetch/query Valuation/Activity based on conditions.
* @Author             : Mansur Alam
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         27-05-2024             Mansur alam                 Initial Version
*/
public class UB_ActivitySelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Valuation__c.Id,
            Valuation__c.Collateral__c,
            Valuation__c.Current_Owner__c,
            Valuation__c.Document__c,
            
            Valuation__c.Loan_Application__c,
            Valuation__c.Loan_Applicant__c,
            Valuation__c.RecordType_Name__c,
            Valuation__c.Status__c,
            Valuation__c.Vehicle__c,
            Valuation__c.Vendor_Status__c,
            Valuation__c.Name,
            Valuation__c.Result__c,
            Valuation__c.Comment__c,
            Valuation__c.Loan_Applicant__c

           
        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Valuation__c.sObjectType;
    }

    public List<Valuation__c > selectById(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN : recordIds');
        return (List<Valuation__c >) Database.query(query.toSOQL());
    }
    
    public List<Valuation__c > selectByLoanApplicationId(Set<Id> loanApplicationId){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Applicant__r.Loan_Application__c IN : loanApplicationId OR Vehicle__r.Loan_Application__c IN : loanApplicationId OR Collateral__r.Loan_Application__c IN : loanApplicationId');
        query.selectField('RecordType.Name');
        query.selectField('RecordType.DeveloperName');
        query.selectField('LastModifiedDate');
        query.selectField('Loan_Applicant__c');
        query.selectField('Loan_Applicant__r.Name');
        query.selectField('Vehicle__c');
        query.selectField('Vehicle__r.Name');
        query.selectField('Collateral__c');
        query.selectField('Collateral__r.Name');
        query.addOrdering('CreatedDate', fflib_QueryFactory.SortOrder.DESCENDING);
        return (List<Valuation__c >) Database.query(query.toSOQL());
    }
   	
    public List<Valuation__c > selectByAppId_RecType_Status(Set<Id> loanApplicationIds, Set<String> recordTypeIds, Set<String> status){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN : loanApplicationIds AND RecordTypeId IN : recordTypeIds AND Status__c IN : status');
        return (List<Valuation__c >) Database.query(query.toSOQL());
    }

    //Added by Musab || 13-07-2024
    public List<Valuation__c> selectByApplicantId(String loanApplicantId, String recordTypeName){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Applicant__c =: loanApplicantId AND recordType.Name =: recordTypeName' );
        query.setOrdering('createddate',fflib_QueryFactory.SortOrder.DESCENDING);
        query.setLimit(1);
        return (List<Valuation__c >) Database.query(query.toSOQL());
    }
}