force-app/main/default/objects/Collateral__c/Collateral__c.object-meta.xml
<CustomObject>
    <label>Collateral</label>
    <nameField>
        <displayFormat>Col-{0000}</displayFormat>
        <label>Collateral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Valuation__c/Valuation__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Valuation__c/fields/Collateral__c.field-meta.xml
<CustomField>
    <fullName>Collateral__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collateral</label>
    <referenceTo>Collateral__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/recordTypes/Legal.recordType-meta.xml
<RecordType>
    <fullName>Legal</fullName>
    <active>true</active>
    <label>Legal</label>
</RecordType>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/UB_Valuationdetails.cls
public class UB_Valuationdetails {
     @AuraEnabled
    public static String getValuationDetail(String parentId, String valuationType){
         List<Valuation__c > valustionList = new List<Valuation__c>();
        try{
        
        if(parentId != null && valuationType == 'Residence FI' || valuationType == 'Office FI'  || valuationType == 'Permanent FI'){
             valustionList = [SELECT Id FROM Valuation__c where Loan_Applicant__c = :parentId Order By CreatedDate Desc LIMIT 1 ];
           system.debug('valustionList1> ' + valustionList );
            
        } else if(parentId != null && valuationType == 'Property Valuation' || valuationType == 'Legal'){
             valustionList = [SELECT Id FROM Valuation__c where Collateral__c = :parentId Order By CreatedDate Desc LIMIT 1 ];
            system.debug('valustionList2> ' + valustionList );
           
        }else if(parentId != null && valuationType == 'Vehicle Valuation'){
            valustionList = [SELECT Id FROM Valuation__c where Vehicle__c = :parentId Order By CreatedDate Desc LIMIT 1 ];
           system.debug('valustionList3> ' + valustionList );
           
        }
        if(!valustionList.isEmpty()){
            return  valustionList[0].Id;
        }
      return null; 
    }
    
    Catch(Exception error){
        String errors =  JSON.serialize(error.getMessage() + error.getLineNumber() + error.getStackTraceString() );
        return errors;
    }
      
    }
}