force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Api_Logger__c/Api_Logger__c.object-meta.xml
<CustomObject>
    <label>Api Logger</label>
    <nameField>
        <displayFormat>APIL-{0000000000}</displayFormat>
        <label>Api Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Logger</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/lob__c.field-meta.xml
<CustomField>
    <fullName>lob__c</fullName>
    <label>LOB</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Parent_Branch__c.field-meta.xml
<CustomField>
    <fullName>Parent_Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Branch</relationshipLabel>
    <relationshipName>Branch</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Applied Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <defaultValue>&apos;Non-applicable&apos;</defaultValue>
    <label>Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <defaultValue>&apos;Assets&apos;</defaultValue>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Liabilities</fullName>
            </value>
            <value>
                <fullName>Assets</fullName>
                <default>true</default>
                <label>Assets</label>
            </value>
            <value>
                <fullName>Micro Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Nature__c.field-meta.xml
<CustomField>
    <fullName>Lead_Nature__c</fullName>
    <label>Lead Nature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOT</fullName>
            </value>
            <value>
                <fullName>WARM</fullName>
            </value>
            <value>
                <fullName>COLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Branch Walk-in</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>ATM</fullName>
            </value>
            <value>
                <fullName>Cross-Sell</fullName>
            </value>
            <value>
                <fullName>Outbound Activity-Branch</fullName>
            </value>
            <value>
                <fullName>Home Market</fullName>
            </value>
            <value>
                <fullName>DSA</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Marketing Activity- BTL</fullName>
            </value>
            <value>
                <fullName>Marketing Channel- ATL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LeMS_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>LeMS_Lead_ID__c</fullName>
    <description>This will be auto-populated by the UB_SyncLeadService API class.</description>
    <label>LeMS Lead ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Loan_Period__c.field-meta.xml
<CustomField>
    <fullName>Loan_Period__c</fullName>
    <label>Loan Tenure(in months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&apos;Other Sources&apos;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other Sources</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New CV</fullName>
            </value>
            <value>
                <fullName>Used CV</fullName>
            </value>
            <value>
                <fullName>New CE</fullName>
            </value>
            <value>
                <fullName>Used CE</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <defaultValue>&apos;WHE999&apos;</defaultValue>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WHE999</fullName>
                <default>true</default>
                <label>CV/CE(WHE999)</label>
            </value>
            <value>
                <fullName>266</fullName>
                <label>Business Loan Plus</label>
            </value>
            <value>
                <fullName>129</fullName>
                <label>Business Loan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Product_Vertical__c</fullName>
    <label>Product Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wheels</fullName>
            </value>
            <value>
                <fullName>Retail Assets</fullName>
            </value>
            <value>
                <fullName>MSME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_SyncLeadService.cls
/**
* @File Name          : UB_SyncLeadService.cls
* @Description        : API to create Lead to the external system.
* @Author             : Mohit
* @Test CLass         : UB_SyncLeadServiceTest
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         21-03-2024               Mohit                 Initial Version
*/
public class UB_SyncLeadService {
    UB_HTTPCalloutService service;
    
    @future(callout=true)
    public static void doExternalCallout(Set<Id> leadIdSet) {
        //Savepoint sp = Database.setSavepoint();
        UB_SyncLeadService syncLeadAPI = new UB_SyncLeadService();
        syncLeadAPI.service = new UB_HTTPCalloutService('External_Lead_Creation_API');
        List<Lead__c> leadRecords = new UB_LeadsSelector().selectById(leadIdSet);

        try{
            if(syncLeadAPI.service.calloutMetadata != null){
                List<Lead__c> updateLeadList = new List<Lead__c>(); 
                List<API_Logger__c> createLogList = new List<API_Logger__c>(); 
                List<UB_CreateLeadService.LeadDetails> wrapperList = new List<UB_CreateLeadService.LeadDetails>();
                
                for(Lead__c ldObj : leadRecords){
                    UB_CreateLeadService.LeadDetails ldWrapper = new UB_CreateLeadService.LeadDetails();
                    ldWrapper.Customer_Type    = String.isNotBlank(ldObj.Customer_Type__c) ? ldObj.Customer_Type__c : '';
                    ldWrapper.Customer_Name    = String.isNotBlank(ldObj.First_Name__c) ? ldObj.First_Name__c : '';
                    ldWrapper.Customer_Name   += String.isNotBlank(ldObj.Middle_Name__c) ? ldObj.Middle_Name__c : '';
                    ldWrapper.Customer_Name   += String.isNotBlank(ldObj.Last_Name__c) ? ldObj.Last_Name__c : '';
                    ldWrapper.Mobile_Number    = String.isNotBlank(ldObj.Mobile_Number__c) ? ldObj.Mobile_Number__c : '';
                    ldWrapper.Lead_Source      = String.isNotBlank(ldObj.Lead_Source__c) ? ldObj.Lead_Source__c : '';
                    ldWrapper.Campaign_Type    = String.isNotBlank(ldObj.Campaign_Type__c) ? ldObj.Campaign_Type__c : '';
                    ldWrapper.Lead_Nature      = String.isNotBlank(ldObj.Lead_Nature__c) ? ldObj.Lead_Nature__c : '';
                    ldWrapper.Lead_Status      = String.isNotBlank(ldObj.Lead_Status__c) ? ldObj.Lead_Status__c : '';
                    ldWrapper.Department       = String.isNotBlank(ldObj.Department__c) ? ldObj.Department__c : '';
                    ldWrapper.Product_Vertical = String.isNotBlank(ldObj.Product_Vertical__c) ? ldObj.Product_Vertical__c : '';
                    ldWrapper.Product_Category = String.isNotBlank(ldObj.Product_Category__c) ? ldObj.Product_Category__c : '';
                    ldWrapper.Product_Name     = String.isNotBlank(ldObj.Product_Name__c) ? ldObj.Product_Name__c : '';
                    //ldWrapper.Product_Code     = String.isNotBlank(ldObj.Product_Code__c) ? ldObj.Product_Code__c : '';
                    ldWrapper.Branch           = String.isNotBlank(ldObj.Branch__c) ? ldObj.Branch__r.Name : '';
                    ldWrapper.Gender           = String.isNotBlank(ldObj.Gender__c) ? ldObj.Gender__c : '';
                    ldWrapper.Amount           = ldObj.Amount__c != null && ldObj.Amount__c > 0 ? String.valueOf(ldObj.Amount__c) : '';
                    ldWrapper.Loan_Period      = ldObj.Loan_Period__c != null && ldObj.Loan_Period__c > 0 ? String.valueOf(ldObj.Loan_Period__c) : '';
                    ldWrapper.PAN              = String.isNotBlank(ldObj.PAN__c) ? ldObj.PAN__c : '';
                    if(ldObj.Addresses__r.size() > 0){
                        //ldWrapper.City             = String.isNotBlank(ldObj.Addresses__r) ?  : '';	
                        //ldWrapper.State            = String.isNotBlank() ?  : '';
                        //ldWrapper.Pin_Code         = String.isNotBlank() ?  : '';
                    }
                    ldWrapper.Platform         = String.isNotBlank(ldObj.Platform__c) ? ldObj.Platform__c : '';
                    wrapperList.add(ldWrapper);
                }
                
                if(!wrapperList.isEmpty() && wrapperList.size() > 0){
                    syncLeadAPI.service.setRequestBody(JSON.serialize(wrapperList));
                    HttpResponse response = syncLeadAPI.service.sendRequest(); 
                    Map<String,Object> mapResponseResult = (Map<String,Object>) JSON.deserializeUntyped(response.getBody());
                    if(response.getStatusCode() == 200){
                        if(mapResponseResult.keySet().size() > 0 && mapResponseResult.containsKey('data')){
                            Map<String,Object> mapResponseBody = (Map<String,Object>) (mapResponseResult.get('data'));
                            if(mapResponseBody != null && mapResponseBody.keySet().size() > 0 && mapResponseBody.containsKey('leadId')){
                                for(String leadId : leadIdSet){
                                    updateLeadList.add(new Lead__c(Id = leadId,LeMS_Lead_ID__c = (String) String.valueOf(mapResponseBody.get('leadId'))));
                                }
                                
                                if(!updateLeadList.isEmpty() && updateLeadList.size() > 0){
                                    UB_LeadUtility.updateRecords(updateLeadList);
                                }
                            }
                        }
                    }
                    API_Logger__c apiLogger = UB_HTTPCalloutService.createAPILogRecord(
                        syncLeadAPI.service.getEndpointURL(), 
                        String.valueOf(syncLeadAPI.service.getHeaderParameters()), 
                        syncLeadAPI.service.getRequestMethod(), 
                        JSON.serialize(wrapperList), 
                        response.getBody(), 
                        response.getStatusCode(), 
                        UB_SyncLeadService.class.getName(), 
                        String.valueOf(new List<Id>(leadIdSet)[0]), 
                        Id.valueOf(new List<Id>(leadIdSet)[0]).getSObjectType().getDescribe().getName(), 
                        UB_ConstantsUtil.REST_API_TYPE,
                        'SyncLeadExternalAPI',
                        leadRecords[0].LOB__c
                    );
                    if(mapResponseResult.containsKey('status')){
                        apiLogger.Status__c = (String) String.valueOf(mapResponseResult.get('status'));
                    }
                    createLogList.add(apiLogger);
                    if(!createLogList.isEmpty() && createLogList.size() > 0){
                        UB_API_LoggerUtility.insertRecords(createLogList);
                    }
                }
            }
        }catch(Exception e) {
            //Database.rollback(sp);
            System.debug('Exception@@'+e.getMessage());
            UB_CommonUtil.createExceptionLogRecord(e, leadRecords[0].LOB__c);
        }
    }
    
    @InvocableMethod
    public static void syncLeadToExternalSystem(List<Id> leadIdSet){
        System.debug('Invocable- '+leadIdSet);
        UB_SyncLeadService.doExternalCallout(new Set<Id>(leadIdSet));
    }
}