force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/BL_PermanentAddressSameAsResidence__c.field-meta.xml
<CustomField>
    <fullName>BL_PermanentAddressSameAsResidence__c</fullName>
    <label>Permanent Address Same as Residence?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Pincode__r.City__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>&apos;India&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Pincode__r.City__r.District__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Is_Communication__c.field-meta.xml
<CustomField>
    <fullName>Is_Communication__c</fullName>
    <label>Is Communication</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pincode</label>
    <referenceTo>Pincode__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Pincode__r.City__r.District__r.State__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>City</relationshipLabel>
    <relationshipName>City</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>City</relationshipLabel>
    <relationshipName>City</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>District</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>District</relationshipLabel>
    <relationshipName>District</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Current_Residential_Address__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/recordTypes/Individual.recordType-meta.xml
<RecordType>
    <fullName>Individual</fullName>
    <active>true</active>
    <label>Individual</label>
</RecordType>

force-app/main/default/objects/Pincode__c/Pincode__c.object-meta.xml
<CustomObject>
    <label>Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pincode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pincode__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pincode__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pincode__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UB_AddressComponentController.cls
/**
*   Name        :   UB_AddressComponentController
*   @author     :   Lakshya Verma
*   @description:   It is used to Address Component.
*   @date       :   20 March 2024
*   Test Class  :   
*   Jira        :  
*/
public class UB_AddressComponentController {

    public static Id BL_LeMSLeadRecordType = BL_ConstantsUtil.BL_LEMS_LEAD_RECORDTYPE;
    public static Id BL_PartnerPortalLeadRecordType = BL_ConstantsUtil.BL_Partner_Portal_Lead_RecordType;

    @AuraEnabled
    public static Pincode__c getPinCodeDetails(String pinCodeId){
        try{
             if (Schema.sObjectType.Pincode__c.isAccessible() && Schema.sObjectType.Pincode__c.isQueryable()) {
            List<Pincode__c> pinCodeList = [ SELECT Id, Name, City__c, City__r.Name, City__r.District__c, 
                                            City__r.District__r.Name, City__r.District__r.State__c, City__r.District__r.State__r.Name
                                            , City__r.District__r.State__r.Country__c  
                                            FROM Pincode__c WHERE Id =: pinCodeId LIMIT 1  ];
            if(pinCodeList != null && pinCodeList.size() > 0){
                return pinCodeList[0];
            }
             }
        }catch(Exception e){
            //System.debug(LoggingLevel.ERROR, 'getPinCodeDetails=> ' + e.getMessage());
            throw newMessageException(e.getMessage());
        }
        return new Pincode__c();
    }

    /**
    * @author Lakshya
    * @date 10-Apr-2024
    * @description This method is created to get Count Of Communition Address.
    * @param objectName
    * @param recordId
    * @param addressId
    * @return String
    */
    @AuraEnabled
    public static Integer isCommunicationAddressExist(String objectName, String recordId, String addressId){
        String query = 'SELECT Count() FROM Address__c WHERE Is_Communication__c = \'Yes\' AND Id !=: addressId ';
        Integer count = 0;
        if(objectName == 'Lead__c'){
            count = Database.countQuery(query + ' AND Lead__c =: recordId');
        }else if(objectName == 'Loan_Applicant__c'){
            count = Database.countQuery(query + ' AND Loan_Applicant__c =: recordId');
        }
        return count;
    }

    @AuraEnabled
    public static Integer isPermanentAddressIsSameAsResidence(String objectName, String recordId, String addressId){
        String query = 'SELECT Count() FROM Address__c WHERE BL_PermanentAddressSameAsResidence__c = \'Yes\' AND Id !=: addressId ';
        Integer count = 0;
        if(objectName == 'Lead__c'){
            count = Database.countQuery(query + ' AND Lead__c =: recordId');
        }else if(objectName == 'Loan_Applicant__c'){
            count = Database.countQuery(query + ' AND Loan_Applicant__c =: recordId');
        }
        return count;
    }

    //Addedd  by umair 22-08-24
    @AuraEnabled
    public static String isAddressSameBL(String applicantORLeadId){
        UB_AddressesSelector addSelector = new UB_AddressesSelector();
        String sameAddressCheck;
        system.debug('applicantORLeadId>> '+applicantORLeadId);

        if(applicantORLeadId != Null){
            List<Address__c> addList = addSelector.getAddressByParent(new Set<Id>{applicantORLeadId});
            system.debug('addList>> '+addList);

            if(!addList.isEmpty()){
                sameAddressCheck = addList[0].BL_PermanentAddressSameAsResidence__c;                
            }else{
                sameAddressCheck = '';
            }
        }else{
            sameAddressCheck = '';
        }
        system.debug('sameAddressCheck>> '+sameAddressCheck);
        return sameAddressCheck;
    }

    @testVisible private static AuraHandledException newMessageException(String message) {
        AuraHandledException e = new AuraHandledException(message);
        e.setMessage(message);
        return e;
    }
    /**
    * @author Manjeet
    * @date 03-July-2024
    * @description This method is created to get the lead RecordTypeId.
    * @param parentObjectId
    * @return Wrapper
    */
    @AuraEnabled
    public static boolean getParentRecordType(Id parentObjectId, String sObjectName) {
        try {
            // Query the parent object to get the RecordTypeId and RecordType.Name
            if(sObjectName  == 'Lead__c'){
                Lead__c parentRecord = [SELECT RecordTypeId, RecordType.Name FROM Lead__c WHERE Id = :parentObjectId LIMIT 1];
                if (parentRecord != null && (parentRecord.RecordTypeId == BL_LeMSLeadRecordType || parentRecord.RecordTypeId == BL_PartnerPortalLeadRecordType)) {
                    return true;
                }
            }else if(sObjectName  == 'Loan_Applicant__c'){
                Loan_Applicant__c parentRecord = [SELECT RecordTypeId, RecordType.Name FROM Loan_Applicant__c WHERE Id = :parentObjectId LIMIT 1];
                if (parentRecord != null && (parentRecord.RecordType.Name == 'BL Non Individual' || parentRecord.RecordType.Name == 'BL Individual')) {
                    return true;
                }
            }
            return null;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}