force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/lob__c.field-meta.xml
<CustomField>
    <fullName>lob__c</fullName>
    <label>LOB</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Applied Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/BL_Repayment_Mode__c.field-meta.xml
<CustomField>
    <fullName>BL_Repayment_Mode__c</fullName>
    <label>Repayment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NACH</fullName>
            </value>
            <value>
                <fullName>SI from USFB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <defaultValue>&apos;Non-applicable&apos;</defaultValue>
    <label>Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Consent_Received__c.field-meta.xml
<CustomField>
    <fullName>Consent_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent Received?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Constitution__c.field-meta.xml
<CustomField>
    <fullName>Constitution__c</fullName>
    <label>Constitution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Constitution</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Date_of_Birth_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth_Incorporation__c</fullName>
    <label>Date of Birth/ Incorporation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Date_Of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Incorporation__c</fullName>
    <label>Date Of Incorporation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <defaultValue>&apos;Assets&apos;</defaultValue>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Liabilities</fullName>
            </value>
            <value>
                <fullName>Assets</fullName>
                <default>true</default>
                <label>Assets</label>
            </value>
            <value>
                <fullName>Micro Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/DSA__c.field-meta.xml
<CustomField>
    <fullName>DSA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DSA</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <label>Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Nature__c.field-meta.xml
<CustomField>
    <fullName>Lead_Nature__c</fullName>
    <label>Lead Nature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOT</fullName>
            </value>
            <value>
                <fullName>WARM</fullName>
            </value>
            <value>
                <fullName>COLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Branch Walk-in</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>ATM</fullName>
            </value>
            <value>
                <fullName>Cross-Sell</fullName>
            </value>
            <value>
                <fullName>Outbound Activity-Branch</fullName>
            </value>
            <value>
                <fullName>Home Market</fullName>
            </value>
            <value>
                <fullName>DSA</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Marketing Activity- BTL</fullName>
            </value>
            <value>
                <fullName>Marketing Channel- ATL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Consent Pending</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Loan_Period__c.field-meta.xml
<CustomField>
    <fullName>Loan_Period__c</fullName>
    <label>Loan Tenure(in months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Manager_IDs__c.field-meta.xml
<CustomField>
    <fullName>Manager_IDs__c</fullName>
    <description>This field is used to determine direct &amp; indirect manager Ids to show records.</description>
    <inlineHelpText>USE FOR BACKEND ONLY</inlineHelpText>
    <label>Manager IDs</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <formula>IF( ISBLANK( Entity_Name__c ), IF(ISBLANK(Middle_Name__c),

UPPER(LEFT(First_Name__c,1))&amp;LOWER(Mid(First_Name__c, 2, Len(First_Name__c)-1))

+&quot; &quot;+

UPPER(LEFT(Last_Name__c,1))&amp;LOWER(Mid(Last_Name__c, 2, Len(Last_Name__c)-1))

,

UPPER(LEFT(First_Name__c,1))&amp;LOWER(Mid(First_Name__c, 2, Len(First_Name__c)-1))

+&quot; &quot;+

UPPER(LEFT(Middle_Name__c,1))&amp;LOWER(Mid(Middle_Name__c, 2, Len(Middle_Name__c)-1))

+&quot; &quot;+

UPPER(LEFT(Last_Name__c,1))&amp;LOWER(Mid(Last_Name__c, 2, Len(Last_Name__c)-1))

), Entity_Name__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Platform__c.field-meta.xml
<CustomField>
    <fullName>Platform__c</fullName>
    <defaultValue>&apos;Other Sources&apos;</defaultValue>
    <label>Platform</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Other Sources</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New CV</fullName>
            </value>
            <value>
                <fullName>Used CV</fullName>
            </value>
            <value>
                <fullName>New CE</fullName>
            </value>
            <value>
                <fullName>Used CE</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <defaultValue>&apos;WHE999&apos;</defaultValue>
    <label>Product Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WHE999</fullName>
                <default>true</default>
                <label>CV/CE(WHE999)</label>
            </value>
            <value>
                <fullName>266</fullName>
                <label>Business Loan Plus</label>
            </value>
            <value>
                <fullName>129</fullName>
                <label>Business Loan</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Product_Vertical__c</fullName>
    <label>Product Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wheels</fullName>
            </value>
            <value>
                <fullName>Retail Assets</fullName>
            </value>
            <value>
                <fullName>MSME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Constitution__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Salutation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Constitution.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Individual</fullName>
    </customValue>
    <customValue>
        <fullName>Sole Proprietorship</fullName>
    </customValue>
    <customValue>
        <fullName>Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Public Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>Trust</fullName>
    </customValue>
    <customValue>
        <fullName>Society</fullName>
    </customValue>
    <customValue>
        <fullName>HUF</fullName>
    </customValue>
    <customValue>
        <fullName>Section 25 Company</fullName>
    </customValue>
    <customValue>
        <fullName>Govt Body/Statutory Body</fullName>
    </customValue>
    <customValue>
        <fullName>Limited Liability Partnership</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Private Ltd</fullName>
    </customValue>
    <customValue>
        <fullName>LLP</fullName>
        <isActive>false</isActive>
        <label>LLP</label>
    </customValue>
    <customValue>
        <fullName>Proprietor</fullName>
        <isActive>false</isActive>
        <label>Proprietor</label>
    </customValue>
    <customValue>
        <fullName>Private Ltd/Ltd</fullName>
        <isActive>false</isActive>
        <label>Private Ltd/Ltd</label>
    </customValue>
    <masterLabel>Constitution</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Salutation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mr.</fullName>
    </customValue>
    <customValue>
        <fullName>Ms.</fullName>
    </customValue>
    <customValue>
        <fullName>Mrs.</fullName>
    </customValue>
    <customValue>
        <fullName>Dr.</fullName>
    </customValue>
    <customValue>
        <fullName>Prof.</fullName>
    </customValue>
    <customValue>
        <fullName>M/s.</fullName>
    </customValue>
    <masterLabel>Salutation</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_LeadsSelector.cls
/**
* @File Name          : UB_LeadsSelector.cls
* @Description        : This class used to fetch/query Lead records based on conditions.
* @Author             : Mohit
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         26-03-2024               Mohit                 Initial Version
*/
public class UB_LeadsSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Lead__c.Id,
            Lead__c.Name,
            Lead__c.Customer_Type__c,
            Lead__c.Last_Name__c,
            Lead__c.First_Name__c,
            Lead__c.Middle_Name__c,
            Lead__c.Mobile_Number__c,
            Lead__c.Lead_Source__c,
            Lead__c.Campaign_Type__c,
            Lead__c.Lead_Nature__c,
            Lead__c.Lead_Status__c,
            Lead__c.Department__c,
            Lead__c.Product_Vertical__c,
            Lead__c.Product_Category__c,
            Lead__c.Product_Name__c,
            //Lead__c.Product_Code__c, 
            Lead__c.Product_Name__c,
            Lead__c.PAN__c,
            Lead__c.Platform__c,
            Lead__c.Amount__c,
            Lead__c.Loan_Period__c,
            Lead__c.Gender__c,
            Lead__c.Constitution__c,
           // Lead__c.Date_Of_Incorporation__c,
            Lead__c.OwnerId,
            Lead__c.Consent_Received__c,
            Lead__c.Lead_Stage__c,
            Lead__c.Date_of_Birth_Incorporation__c,
            Lead__c.Name__c,
            Lead__c.Salutation__c,
            Lead__c.DSA__c,
            Lead__c.LOB__c,
            Lead__c.Email__c,
            Lead__c.Entity_Name__c,
            Lead__c.BL_Repayment_Mode__c,
            Lead__c.Manager_IDs__c    
        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Lead__c.sObjectType;
    }
   
    public List<Lead__c> selectById(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        fflib_SObjectSelector productsSelector = new UB_ProductsSelector();
        //productsSelector.configureQueryFactoryFields(query, 'Product__r');
        fflib_SObjectSelector branchSelector = new UB_BranchSelector();
        branchSelector.configureQueryFactoryFields(query, 'Branch__r');
        query.setCondition('Id IN : recordIds');
        new UB_AddressesSelector().addQueryFactorySubselect(query,'Addresses__r');
        System.debug(query.toSOQL());
        return (List<Lead__c>) Database.query(query.toSOQL());
    }
}