force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Pincode__r.City__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>&apos;India&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Pincode__r.City__r.District__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pincode</label>
    <referenceTo>Pincode__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Pincode__r.City__r.District__r.State__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>City</relationshipLabel>
    <relationshipName>City</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>City</relationshipLabel>
    <relationshipName>City</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>District</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>District</relationshipLabel>
    <relationshipName>District</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>IF(ISBLANK(Entity_Name__c ), First_Name__c +&apos; &apos;+ Middle_Name__c +&apos; &apos;+ Last_Name__c , Entity_Name__c )</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Current_Residential_Address__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Co-Applicant</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Current_Residential_Address__c.field-meta.xml
<CustomField>
    <fullName>Current_Residential_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Residential Address</label>
    <referenceTo>Address__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Period__c.field-meta.xml
<CustomField>
    <fullName>Loan_Period__c</fullName>
    <label>Loan Tenure (in Months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Pincode__c/Pincode__c.object-meta.xml
<CustomObject>
    <label>Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pincode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pincode__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pincode__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pincode__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Number_Of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Vehicles__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Number Of Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Margin_Money__c.field-meta.xml
<CustomField>
    <fullName>Margin_Money__c</fullName>
    <label>Margin Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Number_Of_Vehicles__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Vehicles__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number of Existing Vehicles</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/ROI__c.field-meta.xml
<CustomField>
    <fullName>ROI__c</fullName>
    <label>ROI (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Cost__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Cost__c</fullName>
    <label>Vehicle Cost (Per Vehicle)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Ub_Sanction_Letter_Template_Controller.cls
/**
* @File Name          : Ub_Sanction_Letter_Template_Controller.cls
* @Description        : This class use to map sanction lettee .
* @Author             : Mansur
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         17-06-2024            Mansur         Initial Version           
**/
public class Ub_Sanction_Letter_Template_Controller{
    
    public String plainHTML { get; set; }
    public String loanId{get;set;}   
    public Ub_Sanction_Letter_Template_Controller(ApexPages.StandardController controller) {
        //loanId = apexpages.currentPage().getParameters().get('Id');
    }
    public void getPDF(){
        try {
            loanId = apexpages.currentPage().getParameters().get('Id');
            System.debug('VALUEEEEEEEEEEEEE  '+loanId);
            plainHTML = createEmailBody(loanId);
        }catch(Exception e) {
            System.debug('ERRORRRRRRRRRR    '+e.getMessage());
            System.debug('Line   No'+e.getLineNumber());
        }
    }
    public static String createEmailBody(String loanApplicationId){
        List<String> coApp = new list<String>();
        String productCat = '';
        Decimal TOTAL_VEHICLE = 0;
        Decimal TOTAL_VEHICLE_COST = 0;
        Decimal TOATL_MARGIN_MONEY = 0;
        String add1 = '';
        String add2 = '';
        String add3 = '';
        String COAPP1 = '';
        String COAPP2 = '';
        String GUARTNTOR = '';
        Map<String,Loan_Applicant__c> applicantMap = new Map<String,Loan_Applicant__c>();
        List<Loan_Application__c>  loanAppObj = new UB_LoanApplicationsSelector().selectById(new Set<Id>{loanApplicationId});
        
        System.debug('**loanAppObj->   '+loanAppObj );
        System.debug('Loan Applicant >   '+loanAppObj[0].Loan_Applicants__r);
        if(!loanAppObj.isEmpty()){
            
            System.debug('>>>>>> ' + !loanAppObj[0].Loan_Applicants__r.isEmpty());
            if(!loanAppObj[0].Loan_Applicants__r.isEmpty()){
                for(Loan_Applicant__c app : loanAppObj[0].Loan_Applicants__r){
                    if(app.Applicant_Type__c == UB_ConstantsUtil.CO_APPLICANT){
                        coApp.add(app.Account_Name__c);
                    }else{
                        applicantMap.put(app.Applicant_Type__c, app);
                    }
                }
            }
            if(!loanAppObj[0].Products__r.isEmpty()){
                String[] sp = loanAppObj[0].Products__r[0].Product_Category__c.split('-');
                productCat= sp[0];
                System.debug('productCat->   '+ productCat );
            }
            List<Address__c>  addressObj = new UB_AddressesSelector().getApplicantAddress(new Set<Id>{applicantMap.get(UB_ConstantsUtil.APPLICANT).id});
            System.debug('addressObj->   '+addressObj );
            if(!addressObj.isEmpty() && addressObj.size()> 0 ){
                add1 = addressObj[0].Name +' '+ (addressObj[0].Address_Line_2__c!=null ? addressObj[0].Address_Line_2__c : '');
                add2= (addressObj[0].Address_Line_3__c != null ? addressObj[0].Address_Line_3__c : '' ) +' '+ addressObj[0].City__c+' '+ addressObj[0].District__c;
                add3 = addressObj[0].State__c +' '+  addressObj[0].Pincode__r.Name +' '+ addressObj[0].Country__c;
            }
            List<Vehicle__c >  vehicleObj = new UB_VehiclesSelector().selectByLoanApplicationId(new Set<Id>{loanApplicationId});
            System.debug('applicantMap->   '+applicantMap );
            EmailTemplate tempID = [SELECT Id,Name,Body,HTMLValue FROM EmailTemplate WHERE DeveloperName  =: UB_ConstantsUtil.SANCTION_LETTER_EMAIL_TEMPLATE_NAME];
            String emailBody = tempID.Body;
            if(vehicleObj.size() > 0){
                System.debug('vehicleObj>>>> ' + vehicleObj);
                for(Vehicle__c  vehicle :vehicleObj ){
                    TOATL_MARGIN_MONEY = TOATL_MARGIN_MONEY + (vehicle.Margin_Money__c != null ? vehicle.Margin_Money__c : 0);
                    TOTAL_VEHICLE = TOTAL_VEHICLE + (vehicle.Number_Of_Vehicles__c != null ? vehicle.Number_Of_Vehicles__c : 0);
                    TOTAL_VEHICLE_COST = TOTAL_VEHICLE_COST + ((vehicle.Number_Of_Vehicles__c != null ? vehicle.Number_Of_Vehicles__c : 0) * (vehicle.Vehicle_Cost__c != null ? vehicle.Vehicle_Cost__c : 0));
                }
            }
            if(coApp.size()==1){
                COAPP1 = coApp[0];
            }
            else if(coApp.size() > 1){
                 COAPP1 = coApp[0];
                COAPP2 = coApp[1];
            }
            if(applicantMap.containsKey(UB_ConstantsUtil.GUATANTOR)){
                GUARTNTOR = applicantMap.get(UB_ConstantsUtil.GUATANTOR).Account_Name__c;
            }
             emailBody = emailBody.replace('co_Applicant_Name1',COAPP1);
              emailBody = emailBody.replace('co_Applicant_Name2',COAPP2);
            emailBody = emailBody.replace('applicant_Name',applicantMap.get(UB_ConstantsUtil.APPLICANT).Account_Name__c);
            emailBody = emailBody.replace('guarantor_Name', GUARTNTOR);
            emailBody = emailBody.replace('Address1', add1  );
            emailBody = emailBody.replace('Address2', add2);
            emailBody = emailBody.replace('Address3', add3);
            emailBody = emailBody.replace('productCategory',productCat);
            emailBody = emailBody.replace('application_Number',loanAppObj[0].Name);
            emailBody = emailBody.replace('today_Date',String.valueOf(System.today()));
            emailBody = emailBody.replace('marginMoney',String.valueOf(TOATL_MARGIN_MONEY));
            emailBody = emailBody.replace('creditInsuranceAmount','0');
            emailBody = emailBody.replace('loan_Amount', String.valueOf(loanAppObj[0].Amount__c) != null ? String.valueOf(loanAppObj[0].Amount__c) : '0');
            emailBody = emailBody.replace('ROI',String.valueOf(loanAppObj[0].ROI__c) != null ? String.valueOf(loanAppObj[0].ROI__c) : '0');
            emailBody = emailBody.replace('maximumTenor',String.valueOf(loanAppObj[0].Loan_Period__c) != null ? String.valueOf(loanAppObj[0].Loan_Period__c):'0');
            System.debug(' TOTAL_VEHICLE >   '+ TOTAL_VEHICLE + 'TOTAL_VEHICLE_COST>> '+ TOTAL_VEHICLE_COST );
            emailBody = emailBody.replace('total_Vehicles',String.valueOf(TOTAL_VEHICLE));
            emailBody = emailBody.replace('total_Vehicle_Cost',String.valueOf(TOTAL_VEHICLE_COST));
            System.debug('emailBody after change>   '+ emailBody );
            return emailBody;
        } 
        return null;
    }
}