force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Line 1</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Address_Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent Address</fullName>
            </value>
            <value>
                <fullName>Residence Address</fullName>
            </value>
            <value>
                <fullName>Office Address</fullName>
            </value>
            <value>
                <fullName>Branch / Regional Office</fullName>
                <isActive>false</isActive>
                <label>Branch / Regional Office</label>
            </value>
            <value>
                <fullName>Corporate Office</fullName>
                <isActive>false</isActive>
                <label>Corporate Office</label>
            </value>
            <value>
                <fullName>Not Categorized</fullName>
                <isActive>false</isActive>
                <label>Not Categorized</label>
            </value>
            <value>
                <fullName>Others</fullName>
                <isActive>false</isActive>
                <label>Others</label>
            </value>
            <value>
                <fullName>Plant / Factory Address</fullName>
                <isActive>false</isActive>
                <label>Plant / Factory Address</label>
            </value>
            <value>
                <fullName>Registered Office</fullName>
                <isActive>false</isActive>
                <label>Registered Office</label>
            </value>
            <value>
                <fullName>Warehouse</fullName>
                <isActive>false</isActive>
                <label>Warehouse</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/BL_PermanentAddressSameAsResidence__c.field-meta.xml
<CustomField>
    <fullName>BL_PermanentAddressSameAsResidence__c</fullName>
    <label>Permanent Address Same as Residence?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <formula>Pincode__r.City__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <formula>&apos;India&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <formula>Pincode__r.City__r.District__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>District</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/ICICI_State_Code__c.field-meta.xml
<CustomField>
    <fullName>ICICI_State_Code__c</fullName>
    <formula>Pincode__r.District__r.State__r.ICICI_State_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ICICI State Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Is_Communication__c.field-meta.xml
<CustomField>
    <fullName>Is_Communication__c</fullName>
    <label>Is Communication</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/Pincode__c.field-meta.xml
<CustomField>
    <fullName>Pincode__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pincode</label>
    <referenceTo>Pincode__c</referenceTo>
    <relationshipLabel>Addresses</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <formula>Pincode__r.City__r.District__r.State__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>City Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>City</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>City</relationshipLabel>
    <relationshipName>City</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/City__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>City</relationshipLabel>
    <relationshipName>City</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/District__c/District__c.object-meta.xml
<CustomObject>
    <label>District</label>
    <nameField>
        <label>District Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>District</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/District__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>District</relationshipLabel>
    <relationshipName>District</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <formula>Current_Residential_Address__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Address_Type__c.field-meta.xml
<CustomField>
    <fullName>Address_Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent Address</fullName>
            </value>
            <value>
                <fullName>Residence Address</fullName>
            </value>
            <value>
                <fullName>Office Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pincode__c/Pincode__c.object-meta.xml
<CustomObject>
    <label>Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pincode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pincode__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pincode__c/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>District</label>
    <referenceTo>District__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pincode__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>State</label>
    <referenceTo>State__c</referenceTo>
    <relationshipLabel>Pincode</relationshipLabel>
    <relationshipName>Pincode</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State__c/State__c.object-meta.xml
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State__c/fields/ICICI_State_Code__c.field-meta.xml
<CustomField>
    <fullName>ICICI_State_Code__c</fullName>
    <label>ICICI State Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UB_AddressesSelector.cls
/**
* @File Name          : UB_AddressesSelector.cls
* @Description        : This class used to fetch/query Address records based on conditions.
* @Author             : Mohit
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         26-03-2024               Mohit                 Initial Version
*/
public class UB_AddressesSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Address__c.Id,
                Address__c.City__c,
                Address__c.State__c,
                Address__c.Pincode__c,
                Address__c.CreatedDate,
                Address__c.Loan_Applicant__c,
                Address__c.Is_Communication__c,
                Address__c.Name,
                Address__c.Address_Line_2__c,
                Address__c.Address_Line_3__c,
                Address__c.Country__c,
                Address__c.District__c,
                Address__c.BL_PermanentAddressSameAsResidence__c,
                Address__c.Address_Type__c,
                Address__c.ICICI_State_Code__c

                };
                    }
    
    public Schema.SObjectType getSObjectType(){
        return Address__c.sObjectType;
    }
    
    public List<Address__c> selectById(Set<Id> recordIds){
        return (List<Address__c>) selectSObjectsById(recordIds);
    }
    //Added By Deepak Joshi 10/04/2024
    public List<Address__c> selectByLeasId(Set<Id> leadIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Lead__c IN : leadIds');
        return (List<Address__c>) Database.query(query.toSOQL());
    }
    //added by Mansur Alam
    public List<Address__c> getApplicantAddress(Set<Id> applicantId){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Pincode__c');
        query.selectField('Pincode__r.Name');
        String var = UB_ConstantsUtil.YES;
        query.setCondition('Loan_Applicant__c IN : applicantId AND Is_Communication__c = :var' );
        return (List<Address__c>) Database.query(query.toSOQL());
    }
    
    
    /**
* @description 
* @author Zafaruddin | 07-19-2024 
* @param applicantId 
* @return List<Address__c> 
**/
    public List<Address__c> getApplicantResidenceAddress(Set<Id> applicantId){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Pincode__c');
        query.selectField('Pincode__r.Name');
        String addressType = 'Residence Address';
        query.setCondition('Loan_Applicant__c IN : applicantId AND Address_Type__c= :addressType' );
        return (List<Address__c>) Database.query(query.toSOQL());
    }
    
    /**
* @description 
* @author Zafaruddin | 07-19-2024 
* @param applicantId 
* @return List<Address__c> 
**/
    public List<Address__c> getApplicantPermanentAddress(Set<Id> applicantId){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Pincode__c');
        query.selectField('Pincode__r.Name');
        String addressType = 'Permanent Address';
        
        query.setCondition('Loan_Applicant__c IN : applicantId AND Address_Type__c= :addressType' );
        return (List<Address__c>) Database.query(query.toSOQL());
    }
    
    /**
* @description 
* @author Zafaruddin | 07-19-2024 
* @param applicantId 
* @return List<Address__c> 
**/
    public List<Address__c> getApplicantOfficeAddress(Set<Id> applicantId){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Pincode__c');
        query.selectField('Pincode__r.Name');
        String addressType = 'Office Address';
        
        query.setCondition('Loan_Applicant__c IN : applicantId AND Address_Type__c= :addressType' );
        return (List<Address__c>) Database.query(query.toSOQL());
    }
    
    /**
* @description 
* @author Umair | 08-21-2024 
* @param applicantId 
* @return List<Address__c> 
**/
    public List<Address__c> getAddressByParent(Set<Id> applicantORLeadId){
        fflib_QueryFactory query = newQueryFactory();
        String addressType = 'Office Address';
        query.selectField('BL_PermanentAddressSameAsResidence__c');
        query.setCondition('(Loan_Applicant__c IN : applicantORLeadId OR Lead__c IN: applicantORLeadId) AND Address_Type__c != :addressType');
        system.debug('query>>> '+query);
        system.debug('result>>> '+(List<Address__c>) Database.query(query.toSOQL()));
        return (List<Address__c>) Database.query(query.toSOQL());
    }
    
    
    /**
* @description 
* @author Umair | 26-08-2024 
* @param applicantId 
* @return List<Address__c> 
**/
    public List<Address__c> getApplicantAddressByType(Set<Id> applicantId, String addressType){
        fflib_QueryFactory query = newQueryFactory();
        query.selectField('Pincode__c');
        query.selectField('Pincode__r.Name');
        query.setCondition('Loan_Applicant__c IN : applicantId AND Address_Type__c= :addressType' );
        return (List<Address__c>) Database.query(query.toSOQL());
    }
    /*public override String getOrderBy(){
return 'CreatedDate DESC';
}*/
    
    public List<Address__c> getAllAddressOfApplicant(Set<Id> applicantId){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Applicant__c IN : applicantId' );
        return (List<Address__c>) Database.query(query.toSOQL());
    }
}