force-app/main/default/objects/Approval_Matrix__mdt/fields/Range_Max__c.field-meta.xml
<CustomField>
    <fullName>Range_Max__c</fullName>
    <label>Range Max</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Approval_Matrix__mdt/fields/Range_Min__c.field-meta.xml
<CustomField>
    <fullName>Range_Min__c</fullName>
    <label>Range Min</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Collateral__c/Collateral__c.object-meta.xml
<CustomObject>
    <label>Collateral</label>
    <nameField>
        <displayFormat>Col-{0000}</displayFormat>
        <label>Collateral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collateral</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Collateral__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Collateral</relationshipLabel>
    <relationshipName>Collateral</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{00000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Uploaded</fullName>
                <default>true</default>
                <label>Not Uploaded</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Submitted to CPA</fullName>
            </value>
            <value>
                <fullName>CPA Acknowledged</fullName>
            </value>
            <value>
                <fullName>CM Acknowledged</fullName>
            </value>
            <value>
                <fullName>RCU Acknowledged</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Not Received</fullName>
                <isActive>false</isActive>
                <label>Not Received</label>
            </value>
            <value>
                <fullName>OTC</fullName>
                <isActive>false</isActive>
                <label>OTC</label>
            </value>
            <value>
                <fullName>PDD</fullName>
                <isActive>false</isActive>
                <label>PDD</label>
            </value>
            <value>
                <fullName>Query Raised</fullName>
                <isActive>false</isActive>
                <label>Query Raised</label>
            </value>
            <value>
                <fullName>RCU Verified</fullName>
                <isActive>false</isActive>
                <label>RCU Verified</label>
            </value>
            <value>
                <fullName>Verified</fullName>
                <isActive>false</isActive>
                <label>Verified</label>
            </value>
            <value>
                <fullName>Waived Off</fullName>
                <isActive>false</isActive>
                <label>Waived Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Valuation__c.field-meta.xml
<CustomField>
    <fullName>Valuation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Valuation</label>
    <referenceTo>Valuation__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Verification__c.field-meta.xml
<CustomField>
    <fullName>Verification__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Verification</label>
    <referenceTo>Verification__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>IF(ISBLANK(Entity_Name__c ), First_Name__c +&apos; &apos;+ Middle_Name__c +&apos; &apos;+ Last_Name__c , Entity_Name__c )</formula>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/Valuation__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Valuation__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current Title Deed</fullName>
            </value>
            <value>
                <fullName>Prior Title Deed</fullName>
            </value>
            <value>
                <fullName>Title Search Report/ No Encumbrance Certificate</fullName>
            </value>
            <value>
                <fullName>Draft Agreement Copy</fullName>
            </value>
            <value>
                <fullName>Revenue Records</fullName>
            </value>
            <value>
                <fullName>Permissions And Approvals</fullName>
            </value>
            <value>
                <fullName>Other Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>RCU Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Query Raised</fullName>
            </value>
            <value>
                <fullName>Screened</fullName>
            </value>
            <value>
                <fullName>Sampled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Vendor_Status__c.field-meta.xml
<CustomField>
    <fullName>Vendor_Status__c</fullName>
    <defaultValue>&apos;Pending&apos;</defaultValue>
    <label>Vendor Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/Verification__c.object-meta.xml
<CustomObject>
    <label>Verification</label>
    <nameField>
        <displayFormat>VER-{0000}</displayFormat>
        <label>Verification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Verifications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Verification__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Verifications</relationshipLabel>
    <relationshipName>Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;+Loan_Applicant__r.Loan_Application__c, Loan_Applicant__r.Loan_Application__r.Name,
&quot;_self&quot;)</formula>
    <label>Loan Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Verification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>OTP Sent</fullName>
            </value>
            <value>
                <fullName>OTP Attempt Failed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UB_LoanApplicationApprovalValidations.cls
/**
* @File Name          : UB_LoanApplicationApprovalValidations.cls
* @Description        : Check and validate validation errors while approving Loan Application
* @Author             : Mohit
* @Test Class         : 
* @Dependencies       : UB_LoanApplicationMoveToNextController
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         09-06-2024               Mohit                 Initial Version
*/
public without sharing class UB_LoanApplicationApprovalValidations {
    public static String approvingAuthorityThreshold(User usrObj, Loan_Application__c loanAppObj, Map<String,Messages_Config__mdt> messageConfigMap){
        String validationMsg = '';
        Approval_Matrix__mdt customMetadata = Approval_Matrix__mdt.getInstance(usrObj.Userrole.DeveloperName);
        if(customMetadata != null){
            if(loanAppObj.Amount__c != null && loanAppObj.Amount__c > 0){
                if(customMetadata.Active__c){
                    if(customMetadata.Range_Min__c != null && customMetadata.Range_Min__c >= 0 && 
                       customMetadata.Range_Max__c != null && customMetadata.Range_Max__c > 0){
                           if(loanAppObj.Amount__c < customMetadata.Range_Min__c || loanAppObj.Amount__c > customMetadata.Range_Max__c){
                               validationMsg += '<li>'+messageConfigMap.get('No_Approval_Authorization').Message__c+'</li>';
                           } 
                           Approval_Matrix__mdt thresholdLimit = Approval_Matrix__mdt.getInstance('Committee');
                           if(thresholdLimit.Range_Min__c != null && thresholdLimit.Range_Min__c > 0){
                               if(loanAppObj.Amount__c >= thresholdLimit.Range_Min__c){
                                   String condition = 'Loan_Application__c = \''+loanAppObj.Id+'\' AND ';
                                   condition += ' Document_Type__c = \''+UB_ConstantsUtil.COMMITTEE_APPROVAL_NOTES_DOC_TYPE+'\' AND ';
                                   condition += ' Status__c != \''+UB_ConstantsUtil.UPLOADED+'\' ';
                                   List<Document__c> docList = new UB_DocumentsSelector().selectByConditions(condition);
                                   if(!docList.isEmpty() && docList.size() > 0){
                                       validationMsg += '<li>'+messageConfigMap.get('Upload_Committee_Approval_Notes_Doc').Message__c+'</li>';
                                   }
                               }
                           }else{
                               validationMsg += '<li>'+messageConfigMap.get('No_Approval_Authorization').Message__c+'</li>';
                           }
                       }else{
                           validationMsg += '<li>'+messageConfigMap.get('No_Range_Found').Message__c+'</li>';
                       }
                }else{
                    validationMsg += '<li>'+messageConfigMap.get('No_Approval_Authorization').Message__c+'</li>';
                }
            }else{
                validationMsg += '<li>'+messageConfigMap.get('No_Loan_Amount_Found').Message__c+'</li>';
            }
        }else{
            validationMsg += '<li>'+messageConfigMap.get('No_Approval_Authorization').Message__c+'</li>';
        }
        return validationMsg;
    } 
    
    public static String integrationsActivityValidity(String loanApplicationId, Map<String,Messages_Config__mdt> messageConfigMap){
        Map<String, Activities_Config__mdt> customMetadata = Activities_Config__mdt.getAll();        
        //List<Valuation__c> valuationList = new UB_ActivitySelector().selectByLoanApplicationId(new Set<Id>{loanApplicationId});
        //List<Verification__c> verifyList = new UB_VerificationsSelector().selectByIdLoanApplicationId(new Set<Id>{loanApplicationId});
        List<Valuation__c> valuationList = [SELECT Id, Vendor_Status__c, RecordType.DeveloperName, Loan_Applicant__c,
                                            LastModifiedDate, CreatedDate, Loan_Applicant__r.Account_Name__c, Vehicle__c,
                                            Vehicle__r.Name, Collateral__c, Collateral__r.Name, RecordType.Name
                                            FROM Valuation__c 
                                            WHERE Loan_Applicant__r.Loan_Application__c =: loanApplicationId OR
                                            Vehicle__r.Loan_Application__c =: loanApplicationId OR 
                                            Collateral__r.Loan_Application__c =: loanApplicationId
                                            ORDER BY CreatedDate DESC];
        List<Verification__c> verifyList = [SELECT Id, Status__c, RecordType.DeveloperName, Loan_Applicant__c,
                                            Loan_Applicant__r.Account_Name__c, Loan_Applicant__r.Proof_of_Address__c,
                                            LastModifiedDate, CreatedDate, RecordType.Name
                                            FROM Verification__c 
                                            WHERE Loan_Applicant__r.Loan_Application__c =: loanApplicationId
                                            ORDER BY CreatedDate DESC];
        Set<String> recTypeWithIdSet = new Set<String>();
        Map<String,Set<String>> mapStrWithSetValues = new Map<String,Set<String>>();
        String validationMsg = '';
        
        if(!valuationList.isEmpty() && valuationList.size() > 0 && customMetadata.keySet().size() > 0){
            for(Valuation__c obj : valuationList){
                if(customMetadata.containsKey(obj.RecordType.DeveloperName) && customMetadata.get(obj.RecordType.DeveloperName).Active__c){
                    if(obj.Vehicle__c != null && obj.RecordTypeId == UB_ConstantsUtil.VEHICLE_VALUATION_RECORD_TYPE){
                        String str = obj.RecordType.DeveloperName+'#'+obj.Vehicle__c;
                        if(!recTypeWithIdSet.contains(str)){
                            recTypeWithIdSet.add(str);
                            if(obj.Vendor_Status__c == UB_ConstantsUtil.COMPLETEDSTATUS){
                                Decimal expiryDays = customMetadata.get(obj.RecordType.DeveloperName).Expiry_Days__c != null ? customMetadata.get(obj.RecordType.DeveloperName).Expiry_Days__c : 0;
                                Date expiryDate = expiryDays > 0 ? System.today().addDays(-Integer.valueOf(expiryDays)) : System.today();
                                if(obj.CreatedDate < expiryDate){
                                    String mapKey = obj.RecordType.Name+'#'+UB_ConstantsUtil.COMPLETEDSTATUS;
                                    Set<String> vehicleNameSet = mapStrWithSetValues.containsKey(mapKey) ? mapStrWithSetValues.get(mapKey) : new Set<String>();
                                    vehicleNameSet.add(obj.Vehicle__r.Name);
                                    mapStrWithSetValues.put(mapKey, vehicleNameSet);
                                }
                            }else{
                                String mapKey = obj.RecordType.Name+'#'+UB_ConstantsUtil.PENDING_STATUS;
                                Set<String> vehicleNameSet = mapStrWithSetValues.containsKey(mapKey) ? mapStrWithSetValues.get(mapKey) : new Set<String>();
                                vehicleNameSet.add(obj.Vehicle__r.Name);
                                mapStrWithSetValues.put(mapKey, vehicleNameSet);
                            }
                        }
                    }else if(obj.Collateral__c != null && (obj.RecordTypeId == UB_ConstantsUtil.PROPERTY_VALUATION_RECORD_TYPE || obj.RecordTypeId == UB_ConstantsUtil.LEGAL_RECORD_TYPE)){
                        String str = obj.RecordType.DeveloperName+'#'+obj.Collateral__c;
                        if(!recTypeWithIdSet.contains(str)){
                            recTypeWithIdSet.add(str);
                            if(obj.Vendor_Status__c == UB_ConstantsUtil.COMPLETEDSTATUS){
                                Decimal expiryDays = customMetadata.get(obj.RecordType.DeveloperName).Expiry_Days__c != null ? customMetadata.get(obj.RecordType.DeveloperName).Expiry_Days__c : 0;
                                Date expiryDate = expiryDays > 0 ? System.today().addDays(-Integer.valueOf(expiryDays)) : System.today();
                                if(obj.CreatedDate < expiryDate){
                                    String mapKey = obj.RecordType.Name+'#'+UB_ConstantsUtil.COMPLETEDSTATUS;
                                    Set<String> collateralNameSet = mapStrWithSetValues.containsKey(mapKey) ? mapStrWithSetValues.get(mapKey) : new Set<String>();
                                    collateralNameSet.add(obj.Collateral__r.Name);
                                    mapStrWithSetValues.put(mapKey, collateralNameSet);
                                }
                            }else{
                                String mapKey = obj.RecordType.Name+'#'+UB_ConstantsUtil.PENDING_STATUS;
                                Set<String> collateralNameSet = mapStrWithSetValues.containsKey(mapKey) ? mapStrWithSetValues.get(mapKey) : new Set<String>();
                                collateralNameSet.add(obj.Collateral__r.Name);
                                mapStrWithSetValues.put(mapKey, collateralNameSet);
                            }
                        }
                    }else if(obj.Loan_Applicant__c != null && (obj.RecordTypeId == UB_ConstantsUtil.OFFICE_FI_RECORD_TYPE || obj.RecordTypeId == UB_ConstantsUtil.RESIDENCE_FI_VALUATION_RECORD_TYPE)){
                        String str = obj.RecordType.DeveloperName+'#'+obj.Loan_Applicant__c;
                        if(!recTypeWithIdSet.contains(str)){
                            recTypeWithIdSet.add(str);
                            if(obj.Vendor_Status__c == UB_ConstantsUtil.COMPLETEDSTATUS){
                                Decimal expiryDays = customMetadata.get(obj.RecordType.DeveloperName).Expiry_Days__c != null ? customMetadata.get(obj.RecordType.DeveloperName).Expiry_Days__c : 0;
                                Date expiryDate = expiryDays > 0 ? System.today().addDays(-Integer.valueOf(expiryDays)) : System.today();
                                if(obj.CreatedDate < expiryDate){
                                    String mapKey = obj.RecordType.Name+'#'+UB_ConstantsUtil.COMPLETEDSTATUS;
                                    Set<String> applicantNameSet = mapStrWithSetValues.containsKey(mapKey) ? mapStrWithSetValues.get(mapKey) : new Set<String>();
                                    applicantNameSet.add(obj.Loan_Applicant__r.Account_Name__c);
                                    mapStrWithSetValues.put(mapKey, applicantNameSet);
                                }
                            }else{
                                String mapKey = obj.RecordType.Name+'#'+UB_ConstantsUtil.PENDING_STATUS;
                                Set<String> applicantNameSet = mapStrWithSetValues.containsKey(mapKey) ? mapStrWithSetValues.get(mapKey) : new Set<String>();
                                applicantNameSet.add(obj.Loan_Applicant__r.Account_Name__c);
                                mapStrWithSetValues.put(mapKey, applicantNameSet);
                            }
                        }
                    }
                }
            }
        }
        
        if(!verifyList.isEmpty() && verifyList.size() > 0 && customMetadata.keySet().size() > 0){
            for(Verification__c obj : verifyList){
                if((String.isNotBlank(obj.Loan_Applicant__r.Proof_of_Address__c) &&
                    obj.Loan_Applicant__r.Proof_of_Address__c == UB_ConstantsUtil.AADHAAR_ADDRESS_PROOF &&
                    obj.RecordTypeId == UB_ConstantsUtil.AADHAR_VERIFICATION_RECORD_TYPE) || 
                   obj.RecordTypeId != UB_ConstantsUtil.AADHAR_VERIFICATION_RECORD_TYPE){
                       if(customMetadata.containsKey(obj.RecordType.DeveloperName) && customMetadata.get(obj.RecordType.DeveloperName).Active__c){
                           String str = obj.RecordType.DeveloperName+'#'+obj.Loan_Applicant__c;
                           if(!recTypeWithIdSet.contains(str)){
                               recTypeWithIdSet.add(str);
                               if(obj.Status__c == UB_ConstantsUtil.COMPLETEDSTATUS){
                                   Decimal expiryDays = customMetadata.get(obj.RecordType.DeveloperName).Expiry_Days__c != null ? customMetadata.get(obj.RecordType.DeveloperName).Expiry_Days__c : 0;
                                   Date expiryDate = expiryDays > 0 ? System.today().addDays(-Integer.valueOf(expiryDays)) : System.today();
                                   if(obj.createdDate < expiryDate){
                                       String mapKey = obj.RecordType.Name+'#'+UB_ConstantsUtil.COMPLETEDSTATUS;
                                       Set<String> applicantNameSet = mapStrWithSetValues.containsKey(mapKey) ? mapStrWithSetValues.get(mapKey) : new Set<String>();
                                       applicantNameSet.add(obj.Loan_Applicant__r.Account_Name__c);
                                       mapStrWithSetValues.put(mapKey, applicantNameSet);
                                   }
                               }else{
                                   String mapKey = obj.RecordType.Name+'#'+UB_ConstantsUtil.PENDING_STATUS;
                                   Set<String> applicantNameSet = mapStrWithSetValues.containsKey(mapKey) ? mapStrWithSetValues.get(mapKey) : new Set<String>();
                                   applicantNameSet.add(obj.Loan_Applicant__r.Account_Name__c);
                                   mapStrWithSetValues.put(mapKey, applicantNameSet);
                               }
                           }
                       }
                   }
            }
        }
        if(mapStrWithSetValues.keySet().Size() > 0){
            for(String str : mapStrWithSetValues.keySet()){
                String values = String.valueOf(mapStrWithSetValues.get(str)).remove('{').remove('}');
                if(str.contains(UB_ConstantsUtil.COMPLETEDSTATUS)){
                    validationMsg += '<li>'+'The '+'<b>'+str.split('#')[0]+'</b>'+' '+messageConfigMap.get('Activity_Expired').Message__c+' for '+'<b>'+values+'</b>'+'.'+'</li>';
                }else{
                    validationMsg += '<li>'+'The '+'<b>'+str.split('#')[0]+'</b>'+' '+messageConfigMap.get('Activity_Pending').Message__c+' for '+'<b>'+values+'</b>'+'.'+'</li>';
                } 
            }
        }
        return validationMsg;
    }
}