force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{00000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Acknowledge_Status__c.field-meta.xml
<CustomField>
    <fullName>Acknowledge_Status__c</fullName>
    <label>Acknowledge Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Query Raised</fullName>
            </value>
            <value>
                <fullName>Not Received</fullName>
            </value>
            <value>
                <fullName>Received</fullName>
            </value>
            <value>
                <fullName>OTC</fullName>
            </value>
            <value>
                <fullName>PDD</fullName>
            </value>
            <value>
                <fullName>Waived Off</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
                <isActive>false</isActive>
                <label>Not Verified</label>
            </value>
            <value>
                <fullName>OTT</fullName>
                <isActive>false</isActive>
                <label>OTT</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Checklist__c.field-meta.xml
<CustomField>
    <fullName>Document_Checklist__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document Checklist</label>
    <referenceTo>Document_Checklist__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Document_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Sub_Type__c</fullName>
    <label>Document Sub Type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Uploaded</fullName>
                <default>true</default>
                <label>Not Uploaded</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Submitted to CPA</fullName>
            </value>
            <value>
                <fullName>CPA Acknowledged</fullName>
            </value>
            <value>
                <fullName>CM Acknowledged</fullName>
            </value>
            <value>
                <fullName>RCU Acknowledged</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Not Received</fullName>
                <isActive>false</isActive>
                <label>Not Received</label>
            </value>
            <value>
                <fullName>OTC</fullName>
                <isActive>false</isActive>
                <label>OTC</label>
            </value>
            <value>
                <fullName>PDD</fullName>
                <isActive>false</isActive>
                <label>PDD</label>
            </value>
            <value>
                <fullName>Query Raised</fullName>
                <isActive>false</isActive>
                <label>Query Raised</label>
            </value>
            <value>
                <fullName>RCU Verified</fullName>
                <isActive>false</isActive>
                <label>RCU Verified</label>
            </value>
            <value>
                <fullName>Verified</fullName>
                <isActive>false</isActive>
                <label>Verified</label>
            </value>
            <value>
                <fullName>Waived Off</fullName>
                <isActive>false</isActive>
                <label>Waived Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/Document_Checklist__c.object-meta.xml
<CustomObject>
    <label>Document Checklist</label>
    <nameField>
        <displayFormat>Doc-{00000}</displayFormat>
        <label>Doc Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Document Checklist</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document_Checklist__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Document_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document_Checklist__c/fields/Is_Required__c.field-meta.xml
<CustomField>
    <fullName>Is_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/Loan_Applicant__c.object-meta.xml
<CustomObject>
    <label>Loan Applicant</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Applicant__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <label>Is Deleted</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Applicant__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Loan Applicants</relationshipLabel>
    <relationshipName>Loan_Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Loan_Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Applicant</label>
    <referenceTo>Loan_Applicant__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Document_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Collateral Details If Any</fullName>
    </customValue>
    <customValue>
        <fullName>Preliminary Credit Application Form</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Information Sheet</fullName>
    </customValue>
    <customValue>
        <fullName>Consent</fullName>
    </customValue>
    <customValue>
        <fullName>Others</fullName>
    </customValue>
    <customValue>
        <fullName>Banking</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance</fullName>
    </customValue>
    <customValue>
        <fullName>Photo</fullName>
    </customValue>
    <customValue>
        <fullName>ID Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Address Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Relationship Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Stability Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Signature Verification Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Experience Proof</fullName>
    </customValue>
    <customValue>
        <fullName>Owned House Proof</fullName>
    </customValue>
    <customValue>
        <fullName>GST Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>Partnership Deed</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Incorporation [Pvt Ltd &amp; LTD]</fullName>
    </customValue>
    <customValue>
        <fullName>Registration Certificate</fullName>
    </customValue>
    <customValue>
        <fullName>MOA, AOA, COI [Pvt. Ltd./Ltd.]</fullName>
    </customValue>
    <customValue>
        <fullName>Form 32 [Pvt. Ltd./Ltd.]</fullName>
    </customValue>
    <customValue>
        <fullName>List of Directors [Pvt Ltd &amp; LTD]</fullName>
    </customValue>
    <customValue>
        <fullName>Certificate of Commencement of Business [Ltd]</fullName>
    </customValue>
    <customValue>
        <fullName>HUF Deed Of Declaration [HUF]</fullName>
    </customValue>
    <customValue>
        <fullName>Quotation with USFBL HPA</fullName>
    </customValue>
    <customValue>
        <fullName>RC of Proposed Asset in Used Case</fullName>
    </customValue>
    <customValue>
        <fullName>Insurance of Proposed Asset in Used Case</fullName>
    </customValue>
    <customValue>
        <fullName>Loan Calculation Sheet</fullName>
    </customValue>
    <customValue>
        <fullName>IRR Sheet</fullName>
    </customValue>
    <customValue>
        <fullName>Six Month Latest Banking</fullName>
    </customValue>
    <masterLabel>Document Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_DocumentsSelector.cls
/**
* @File Name          : UB_DocumentsSelector.cls
* @Description        : This class used to fetch/query document based on conditions.
* @Author             : Deepak Joshi
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         03-04-2024               Deepak Joshi                 Initial Version
*/
public class UB_DocumentsSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
            Document__c.Id,
            Document__c.Loan_Application__c,
            Document__c.Lead__c,
            Document__c.Is_Required__c,
            Document__c.Document_URL__c,
            Document__c.Loan_Applicant__c,
            Document__c.Document_Type__c,
            Document__c.Document_Sub_Type__c,
            Document__c.Status__c,
            Document__c.Acknowledge_Status__c
        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Document__c.sObjectType;
    }

    public List<Document__c> selectById(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Id IN : recordIds');
        return (List<Document__c>) Database.query(query.toSOQL());
    }
    public List<Document__c> selectByLeasId(Set<Id> leadIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Lead__c IN : leadIds');
        fflib_SObjectSelector documentChecklistsSelector = new UB_DocumentChecklistsSelector();
        documentChecklistsSelector.configureQueryFactoryFields(query, 'Document_Checklist__r');
        return (List<Document__c>) Database.query(query.toSOQL());
    }
    public List<Document__c> selectByLoanApplicationIdAndIsRequired(Set<Id> loanApplicationId ){
        fflib_QueryFactory query = newQueryFactory();
        String NotUploaded =UB_ConstantsUtil.NOT_UPLOADED;
        String NO = 'No';
        query.setCondition('Loan_Application__c IN : loanApplicationId AND Is_Required__c = true AND Status__c =:NotUploaded AND Loan_Applicant__r.Is_Deleted__c =: NO ' );
        return (List<Document__c>) Database.query(query.toSOQL());
    }
    
    public List<Document__c> selectByConditions(String condition){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition(condition);
        return (List<Document__c>) Database.query(query.toSOQL());
    }
}