force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{00000000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Uploaded</fullName>
                <default>true</default>
                <label>Not Uploaded</label>
            </value>
            <value>
                <fullName>Uploaded</fullName>
            </value>
            <value>
                <fullName>Submitted to CPA</fullName>
            </value>
            <value>
                <fullName>CPA Acknowledged</fullName>
            </value>
            <value>
                <fullName>CM Acknowledged</fullName>
            </value>
            <value>
                <fullName>RCU Acknowledged</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <isActive>false</isActive>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Not Received</fullName>
                <isActive>false</isActive>
                <label>Not Received</label>
            </value>
            <value>
                <fullName>OTC</fullName>
                <isActive>false</isActive>
                <label>OTC</label>
            </value>
            <value>
                <fullName>PDD</fullName>
                <isActive>false</isActive>
                <label>PDD</label>
            </value>
            <value>
                <fullName>Query Raised</fullName>
                <isActive>false</isActive>
                <label>Query Raised</label>
            </value>
            <value>
                <fullName>RCU Verified</fullName>
                <isActive>false</isActive>
                <label>RCU Verified</label>
            </value>
            <value>
                <fullName>Verified</fullName>
                <isActive>false</isActive>
                <label>Verified</label>
            </value>
            <value>
                <fullName>Waived Off</fullName>
                <isActive>false</isActive>
                <label>Waived Off</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Valuation__c.field-meta.xml
<CustomField>
    <fullName>Valuation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Valuation</label>
    <referenceTo>Valuation__c</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Loan Applications</relationshipLabel>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/Valuation__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <displayFormat>ACT-{000000}</displayFormat>
        <label>Activity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Valuation__c/fields/BL_Vendor_Activity__c.field-meta.xml
<CustomField>
    <fullName>BL_Vendor_Activity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendor Activity</label>
    <referenceTo>Valuation__c</referenceTo>
    <relationshipLabel>Activity</relationshipLabel>
    <relationshipName>Activity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Document</label>
    <referenceTo>Document__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipName>Valuation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>RCU Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Query Raised</fullName>
            </value>
            <value>
                <fullName>Screened</fullName>
            </value>
            <value>
                <fullName>Sampled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Valuation__c/fields/Suspicious_Triggers__c.field-meta.xml
<CustomField>
    <fullName>Suspicious_Triggers__c</fullName>
    <label>Suspicious Triggers</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Valuation__c/recordTypes/RCU.recordType-meta.xml
<RecordType>
    <fullName>RCU</fullName>
    <active>true</active>
    <label>RCU</label>
</RecordType>

force-app/main/default/objects/Vendor_Branch_Mapping__c/Vendor_Branch_Mapping__c.object-meta.xml
<CustomObject>
    <label>Vendor Branch Mapping</label>
    <nameField>
        <displayFormat>VBM -{0000}</displayFormat>
        <label>Vendor Branch Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendor Branch Mapping</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vendor_Branch_Mapping__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vendor Branch Mapping</relationshipLabel>
    <relationshipName>Vendor_Branch_Mapping</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vendor_Branch_Mapping__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Vendor Branch Mapping</relationshipLabel>
    <relationshipName>Vendor_Branch_Mapping</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/BL_RCUController.cls
/**
* @File Name          : BL_RCUController.cls
* @Description        : This class use to rcu changes related managers & vendors for BL specific changes.
* @Author             : Lakshya Verma
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0        14th-Aug-2024            Lakshya                  Initial version
**/
public class BL_RCUController {
    @AuraEnabled
    public static List<User> getRCUVendors(String loanApplicationId){
        try{
            if(String.isNotBlank(loanApplicationId) ){
               List<Loan_Application__c> loanApplicationList = [SELECT Id, Name, Branch__c FROM Loan_Application__c WHERE Id =: loanApplicationId 
                                                                AND Branch__c != null];
                if(!loanApplicationList.isEmpty()){
                    Set<Id> accountIds = new Set<Id>();
                    for(vendor_branch_mapping__c vendor : [SELECT Id, Name, Branch__c,Account__c, Account__r.Type_of_Valuer__c
                                                           FROM vendor_branch_mapping__c 
                                                           WHERE Branch__c != null  AND Branch__c =: loanApplicationList[0].Branch__c
                                                           AND Account__c != null AND Account__r.Type_of_Valuer__c != null 
                                                           AND Account__r.Type_of_Valuer__c = 'RCU Vendor' ]){
                                                               accountIds.add(vendor.Account__c);
                                                           }
                    if(!accountIds.isEmpty()){
                        Set<Id> contactIds = new Set<Id>();
                        for(Contact conObj : [SELECT Id, Name, AccountId from Contact WHERE AccountId != null 
                                                      AND AccountId =: accountIds]){
                            contactIds.add(conObj.Id);
                        }
                        
                        if(!contactIds.isEmpty()){
                            LisT<User> rcuVendorsList = [SELECT Id, contactId, Name FROM User WHERE contactId != null AND contactId =: contactIds ];
                            system.debug('rcuVendorsList-> ' + rcuVendorsList);
                            if(!rcuVendorsList.isEmpty()){
                                RETURN rcuVendorsList;
                            }
                        }
                    }
                }
            }
        }catch(Exception e){
            system.debug( e.getMessage());
        }
        return null;
    }
    
    @AuraEnabled
    public static ResponseWrapper initiateRCUtoVendor(List<String> docIds, String selectedVendorId, String applicationId, String susTrigger){
        ResponseWrapper resWrap = new ResponseWrapper();
        try{
            if(!docIds.isEmpty() && String.isNotBlank(selectedVendorId) && String.isNotBlank(applicationId) && String.isNotBlank(susTrigger)){
                List<Valuation__c> rcuManagerActivity = [SELECT Id, name, loan_application__c,BL_Vendor_Activity__c , 
                                                         RecordType_Name__c, Owner.name from Valuation__c  WHERE
                                                         loan_application__c  =: applicationId AND 
                                                         RecordType_Name__c =: BL_ConstantsUtil.RCU AND
                                                          ( Status__c = '' OR Status__c = 'Sampled')];
                if(!rcuManagerActivity.isEmpty()){
                    Valuation__c rcuVendorActivity = new Valuation__c();
                    rcuVendorActivity.recordtypeId = BL_ConstantsUtil.RCU_VENDOR_RECORDTYPE;
                    rcuVendorActivity.loan_application__c = applicationId;
                    rcuVendorActivity.OwnerId = selectedVendorId;
                    rcuVendorActivity.Suspicious_Triggers__c = susTrigger;
                    rcuVendorActivity.BL_Vendor_Activity__c = rcuManagerActivity[0].Id;
                    INSERT rcuVendorActivity;
                    
                    //rcuManagerActivity[0].BL_Vendor_Activity__c = rcuVendorActivity.Id;
                    //UPDATE rcuManagerActivity;
                    
                    List<Document__c> documentList = [SELECT Id, Name,Valuation__c  FROM Document__c WHERE Id IN : docIds];
                    for(Document__c doc : documentList){
                        doc.Valuation__c = rcuVendorActivity.Id;
                    }
                    UPDATE documentList;
                    
                    SYSTEM.debug('rcuVendorActivity-> ' + rcuVendorActivity);
                    SYSTEM.debug('documentList-> ' + documentList);
                    resWrap.isSuccess = true;
                    resWrap.responseBody = 'Successfully Initiated to RCU Vendor';
                }else{
                    resWrap.isSuccess = false;
                    resWrap.responseBody = 'Something went wrong';
                }
            }
            return resWrap;
        }catch(Exception error){
            String exError = JSON.serialize(error.getMessage() + error.getLineNumber() + error.getStackTraceString() );
            resWrap.isSuccess = false;
            resWrap.responseBody = exError;
            return resWrap;
        }
    }
    
     @AuraEnabled
    public static ResponseWrapper rcuWaiveActivityByManager(String loanApplicationId){
        ResponseWrapper resWrap = new ResponseWrapper();
        try{
            List<Valuation__c> rcuActvity = [SELECT Id from Valuation__c 
                                             WHERE loan_application__c =: loanApplicationId AND (RecordType_Name__c =: BL_ConstantsUtil.RCU)
                                             /*AND (Status__c != 'Screened' OR Status__c ='' )*/ ];
            if(!rcuActvity.isEmpty()){
                resWrap.isSuccess = true;
                resWrap.responseBody = 'RCU Activity is already initiated.';
            }else{
                resWrap.rcuWaive = true;
            }
            RETURN resWrap;
        }catch(Exception error){
            String exError = JSON.serialize(error.getMessage() + error.getLineNumber() + error.getStackTraceString() );
            resWrap.isSuccess = false;
            resWrap.responseBody = exError;
            return resWrap;
        }
    }
    
    @AuraEnabled
    public static List<Valuation__c> getRCUActivityStatus(String loanApplicationId){
        ResponseWrapper resWrap = new ResponseWrapper();
        try{
            List<Valuation__c> rcuActvity = [SELECT Id, Status__c from Valuation__c 
                                             WHERE loan_application__c =: loanApplicationId AND (RecordType_Name__c =: BL_ConstantsUtil.RCU) 
                                             AND (RecordType_Name__c = 'RCU') 
                                             AND (Status__c != 'Screened' OR Status__c = '' ) ];
            if(!rcuActvity.isEmpty()){
                resWrap.isSuccess = true;
                resWrap.responseBody = JSON.serialize(rcuActvity[0].Status__c);
                 RETURN rcuActvity;
            }else{
                resWrap.isSuccess = false;
                RETURN null;
            }
        }catch(Exception error){
            String exError = JSON.serialize(error.getMessage() + error.getLineNumber() + error.getStackTraceString() );
            resWrap.isSuccess = false;
            resWrap.responseBody = exError;
            return null;
        }
    }
    
    public class ResponseWrapper{
        @AuraEnabled public Boolean isSuccess;
        @AuraEnabled public String responseBody;
        @AuraEnabled public Boolean rcuWaive;
    }
}