force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <label>Branch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Branch</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/lob__c.field-meta.xml
<CustomField>
    <fullName>lob__c</fullName>
    <label>LOB</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BL</fullName>
            </value>
            <value>
                <fullName>CV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Lead</label>
    <nameField>
        <displayFormat>Lead-{0000000000}</displayFormat>
        <label>Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leads</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Applied Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Campaign_Type__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Type__c</fullName>
    <defaultValue>&apos;Non-applicable&apos;</defaultValue>
    <label>Campaign Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Existing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Date_of_Birth_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Birth_Incorporation__c</fullName>
    <label>Date of Birth/ Incorporation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Date_Of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Incorporation__c</fullName>
    <label>Date Of Incorporation</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <defaultValue>&apos;Assets&apos;</defaultValue>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Liabilities</fullName>
            </value>
            <value>
                <fullName>Assets</fullName>
                <default>true</default>
                <label>Assets</label>
            </value>
            <value>
                <fullName>Micro Banking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/DOB__c.field-meta.xml
<CustomField>
    <fullName>DOB__c</fullName>
    <label>Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Entity_Name__c.field-meta.xml
<CustomField>
    <fullName>Entity_Name__c</fullName>
    <label>Entity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Nature__c.field-meta.xml
<CustomField>
    <fullName>Lead_Nature__c</fullName>
    <label>Lead Nature</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOT</fullName>
            </value>
            <value>
                <fullName>WARM</fullName>
            </value>
            <value>
                <fullName>COLD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <label>Lead Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Branch Walk-in</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>Whatsapp</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>ATM</fullName>
            </value>
            <value>
                <fullName>Cross-Sell</fullName>
            </value>
            <value>
                <fullName>Outbound Activity-Branch</fullName>
            </value>
            <value>
                <fullName>Home Market</fullName>
            </value>
            <value>
                <fullName>DSA</fullName>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Marketing Activity- BTL</fullName>
            </value>
            <value>
                <fullName>Marketing Channel- ATL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Stage__c.field-meta.xml
<CustomField>
    <fullName>Lead_Stage__c</fullName>
    <label>Lead Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Consent Pending</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Lead_Status__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status__c</fullName>
    <defaultValue>&apos;Active&apos;</defaultValue>
    <label>Lead Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LeMS_Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>LeMS_Lead_ID__c</fullName>
    <description>This will be auto-populated by the UB_SyncLeadService API class.</description>
    <label>LeMS Lead ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Loan_Period__c.field-meta.xml
<CustomField>
    <fullName>Loan_Period__c</fullName>
    <label>Loan Tenure(in months)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/PAN__c.field-meta.xml
<CustomField>
    <fullName>PAN__c</fullName>
    <label>PAN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New CV</fullName>
            </value>
            <value>
                <fullName>Used CV</fullName>
            </value>
            <value>
                <fullName>New CE</fullName>
            </value>
            <value>
                <fullName>Used CE</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Product_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Product_Vertical__c</fullName>
    <label>Product Vertical</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wheels</fullName>
            </value>
            <value>
                <fullName>Retail Assets</fullName>
            </value>
            <value>
                <fullName>MSME</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/RO_RM_Name__c.field-meta.xml
<CustomField>
    <fullName>RO_RM_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RO/RM Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Messages_Config__mdt/Messages_Config__mdt.object-meta.xml
<CustomObject>
    <label>Messages Config</label>
    <pluralLabel>Messages Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Messages_Config__mdt/fields/Message_Type__c.field-meta.xml
<CustomField>
    <fullName>Message_Type__c</fullName>
    <label>Message Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
                <default>true</default>
                <label>Error</label>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pincode__c/Pincode__c.object-meta.xml
<CustomObject>
    <label>Pincode</label>
    <nameField>
        <label>Pincode</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pincode</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_CreateLeadService.cls
/**
* @File Name          : UB_CreateLeadService.cls
* @Description        : Api to insert Lead into system.
* @Author             : Zafaruddin
* @Test CLass         : UB_CreateLeadServiceTest
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================

* 2.0         26-03-2024           Zafaruddin         
*/

@RestResource(urlMapping='/LeadCreation/*')
global with sharing class UB_CreateLeadService {
    
    
    /**
    * @description  : Methid will post leMS lead into Salesforce.
    * @author Zafaruddin | 04-15-2024 
    **/
    @HttpPOST
    global static void doLeadPost() {
        Savepoint sp = Database.setSavepoint();
        String lob = '';
        Map<String,Messages_Config__mdt> messageConfigMap = UB_CommonUtil.getMessageRecord('LeadWebService');
        RestRequest req = RestContext.request;
        try {
            SYstem.debug('req   '+req);
            LeadDetails leadDet = (LeadDetails)Json.deserialize(req.requestBody.tostring(),LeadDetails.class);
            if(leadDet.PAN == NULL) {
                RestContext.response.statusCode = 404;
                RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('Pan_LeadWebService').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('Pan_LeadWebService').Message__c + '" }');
                UB_CommonUtil.createCallBackApiLog(req.requestBody.tostring(),messageConfigMap.get('Pan_LeadWebService').Message__c,404,'UB_CreateLeadService','LeadCallBackService',UB_ConstantsUtil.WBESERVICE_API_TYPE);
                return ;
            } if (leadDet.employeeId == NULL) {
                RestContext.response.statusCode = 404;
                RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('EmployeeCode_LeadWebService').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('EmployeeCode_LeadWebService').Message__c + '" }');
                UB_CommonUtil.createCallBackApiLog(req.requestBody.tostring(),messageConfigMap.get('EmployeeCode_LeadWebService').Message__c,404,'UB_CreateLeadService','LeadCallBackService',UB_ConstantsUtil.WBESERVICE_API_TYPE);
                return ;
            } if (leadDet.LeadId == NULL) {
                RestContext.response.statusCode = 404;
                RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('LeMS_LeadId_is_not_Available').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('LeMS_LeadId_is_not_Available').Message__c + '" }');
                UB_CommonUtil.createCallBackApiLog(req.requestBody.tostring(),messageConfigMap.get('LeMS_LeadId_is_not_Available').Message__c,404,'UB_CreateLeadService','LeadCallBackService',UB_ConstantsUtil.WBESERVICE_API_TYPE);
                return ;
            }  else {
                Lead__c leadRecord = new Lead__c();
                if(leadDet.Product_Category == BL_ConstantsUtil.BL_PRODUCT_CATEGORY) {
                    leadRecord.RecordTypeId = BL_ConstantsUtil.BL_LEMS_LEAD_RECORDTYPE ;
                    lob = UB_ConstantsUtil.LOB_BL;
                    leadRecord.Account_Type__c = leadDet.AccountType ;
                    if(leadDet.AccountType == UB_ConstantsUtil.INDIVIDUAL){
                        leadRecord.Last_Name__c = leadDet.Customer_Name;
                    }else{
                        leadRecord.Entity_Name__c = leadDet.Customer_Name;
                    }
                } else {
                    leadRecord.RecordTypeId = UB_ConstantsUtil.LEMS_RECORD_TYPE ;
                    lob = UB_ConstantsUtil.LOB_CV;
                    leadRecord.Account_Type__c = leadDet.AccountType ;
                    leadRecord.Last_Name__c = leadDet.Customer_Name ;
                }
                
                leadRecord.LOB__c =  lob ;
                leadRecord.Product_Category__c = leadDet.Product_Category ;
                leadRecord.Customer_Type__c = leadDet.Customer_Type ;
                leadRecord.Lead_Stage__c = UB_ConstantsUtil.LEAD_STAGE;
                leadRecord.Lead_Status__c = 'Active';
                leadRecord.Mobile_Number__c = leadDet.Mobile_Number ;
                leadRecord.Lead_Source__c = leadDet.Lead_Source ;
                leadRecord.Campaign_Type__c = leadDet.Campaign_Type ;
                leadRecord.Lead_Nature__c = leadDet.Lead_Nature ;
                leadRecord.Product_Vertical__c   = leadDet.Product_Vertical ;
                leadRecord.Department__c = UB_ConstantsUtil.DEPARTMENT ;
                if(leadDet.employeeId != NULL) {
                   List<User> users = [SELECT Id FROM User WHERE EmployeeNumber  = :leadDet.employeeId  ];
                    if(!users.isEmpty()) {
                        leadRecord.OwnerId = users[0].Id ;
                        leadRecord.RO_RM_Name__c  = users[0].Id ;
                    }else{
                        RestContext.response.statusCode = 404;
                        RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('EmployeeCodeMatch_LeadWebService').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('EmployeeCodeMatch_LeadWebService').Message__c + '" }');
                        UB_CommonUtil.createCallBackApiLog(req.requestBody.tostring(),messageConfigMap.get('EmployeeCodeMatch_LeadWebService').Message__c,404,'UB_CreateLeadService','LeadCallBackService',UB_ConstantsUtil.WBESERVICE_API_TYPE);
                        return ;
                    }
                }
                LIST<Branch__c> branchList = new LIST<Branch__c>();
                if(leadDet.Branch != NULL) {
                    branchList = [SELECT Id,Branch_Code__c FROM Branch__c WHERE Branch_Code__c =:leadDet.Branch];
                }
                if(!branchList.isEmpty()) {
                    leadRecord.Branch__c = branchList[0].Id ;
                }
                leadRecord.Gender__c = leadDet.Gender ;
               /* if(leadDet.AccountType == 'Individual') {
                    leadRecord.DOB__c =  Date.valueOf( leadDet.dob) ;
                } else {
                    leadRecord.Date_Of_Incorporation__c =  Date.valueOf( leadDet.dob) ;
                }*/
                System.debug('leadDet.dob  '+leadDet.dob);
                if(leadDet.dob != NULL &&  String.isNotBlank(leadDet.dob) && String.isNotEmpty(leadDet.dob) ) {
                    leadRecord.Date_of_Birth_Incorporation__c=  Date.valueOf( leadDet.dob) ;
                }
                leadRecord.Amount__c =  Integer.valueOf(leadDet.Amount) ;
                //leadRecord.Loan_Period__c = Integer.valueOf(leadDet.Loan_Period)   ;
                leadRecord.PAN__c = leadDet.PAN ;
                leadRecord.LeMS_Lead_ID__c = leadDet.LeadId ;
                List<Pincode__c> pincodeList = new List<Pincode__c>();
                if(Integer.valueOf(leadDet.Amount) != 0 ){
                    insert leadRecord;
                    RestContext.response.statusCode = 201;
                    RestContext.response.responseBody = Blob.valueOf('{ "status":"success", "leadId": "' +leadRecord.Id + '" ,  "responseType": "' + messageConfigMap.get('leadCreate_LeadWebService').Message_Type__c + '" , "Messages": "' + messageConfigMap.get('leadCreate_LeadWebService').Message__c + '" }');
                    UB_CommonUtil.createCallBackApiLog(req.requestBody.tostring(),messageConfigMap.get('leadCreate_LeadWebService').Message__c,201,'UB_CreateLeadService','LeadCallBackService',UB_ConstantsUtil.WBESERVICE_API_TYPE);
                }else{
                    RestContext.response.statusCode = 400;
                    RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('DevelopmentError_LeadWebService').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('DevelopmentError_LeadWebService').Message__c + ' :  ' + 'Please enter Loan amount.' +  '" }');
                    UB_CommonUtil.createCallBackApiLog(req.requestBody.tostring(),messageConfigMap.get('DevelopmentError_LeadWebService').Message__c + ' :  ' + 'Please enter Loan amount.',400,'LeadCallBackService','LeadCallBAckService',UB_ConstantsUtil.WBESERVICE_API_TYPE);
                }
            }
        }catch(Exception e) {
            Database.rollback(sp);
            System.debug('Exception--->'+e.getMessage());
            System.debug('ERROR LINE NUMBER--->'+e.getLineNumber());
            // call method to create ExceptionLogRecord
            UB_CommonUtil.createExceptionLogRecord(e, lob);
            RestContext.response.statusCode = 400;
            RestContext.response.responseBody = Blob.valueOf('{ "status":"fail", "responseType": "' + messageConfigMap.get('DevelopmentError_LeadWebService').Message_Type__c + '" , "errorMessages": "' + messageConfigMap.get('DevelopmentError_LeadWebService').Message__c + ' :  ' + e.getMessage() +  '" }');
            UB_CommonUtil.createCallBackApiLog(req.requestBody.tostring(),messageConfigMap.get('DevelopmentError_LeadWebService').Message__c + ' :  ' + e.getMessage(),400,'LeadCallBackService','LeadCallBAckService',UB_ConstantsUtil.WBESERVICE_API_TYPE);

        }
    }
     
   public class LeadDetails {
       public String Customer_Type;
       public String Customer_Name;
       public String Mobile_Number;
       public String Lead_Source;
       public String Campaign_Type;
       public String Lead_Nature;
       public String Lead_Status;
       public String Department;
       public String Product_Code;
       public String Branch;
       public String Gender;
       public String Amount;
       public String Loan_Period;
       public String PAN;
       public String City;
       public String State;
       public String Pin_Code;
       public String Platform;
       public String employeeId;
       public String currentResidentialAddress;
       public String AddressLine1;
       public String AddressLine2;
       public String AddressLine3;
       public String District; 
       public String Product_Vertical;  
       public String Product_Category;   
       public String Product_Name; 
       Public String LeadId ;
       public String dob;
       public String AccountType;
   }
        
   global class ModelClass {
        public String status;
        public Integer statusCode;
        public String responseMessage;
        public String leadId;
        public String responseType;

        public ModelClass() {
            status = '';
            responseMessage = '';
            leadId = '';
            responseType = '';
            statusCode = 400;
        }
    }
    
    
    public static ModelClass checkValidation(String Status , String Message, String responseType, Integer statusCode) {
        ModelClass modCls = new ModelClass();
        modCls.Status = Status;
        modcls.responseMessage = Message;
        modcls.responseType = responseType;
        modcls.statusCode = statusCode;


        return modCls;    
    }
}