force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Active_Status__c.field-meta.xml
<CustomField>
    <fullName>Active_Status__c</fullName>
    <label>Active Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Y</fullName>
            </value>
            <value>
                <fullName>N</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Master__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/UB_TestDataFactory.cls
/**
* @File Name          : UB_TestDataFactory.cls
* @Description        : Factory class to create test data
* @Author             : Karthik Chekkilla
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         14-03-2024            Karthik Chekkilla         Initial Version
*/
@isTest
public class UB_TestDataFactory {
    /**
     * @Description :
     * @Author      :
     * @Date        :
    */
    public static Lead createLead(){
        Lead objLead = new Lead();
        objLead.FirstName='test_data';
        objLead.LastName='test_purpose';
        return objLead;
    }
    
    public static Product__c createProduct(){
        Product__c prodRec = new Product__c();
        prodRec.Active_Status__c = 'Y';
        prodRec.Product_Code__c = '123456789';
        prodRec.Name = 'test Product';
        RETURN prodRec;
    }
}