force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Master__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product_Master__c/Product_Master__c.object-meta.xml
<CustomObject>
    <label>Product Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Master__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CV-New</fullName>
            </value>
            <value>
                <fullName>CE-New</fullName>
            </value>
            <value>
                <fullName>CV-Used</fullName>
            </value>
            <value>
                <fullName>CE-Used</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Master__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Master</label>
    <referenceTo>Vehicle_Master__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/Vehicle_Master__c.object-meta.xml
<CustomObject>
    <label>Vehicle Master</label>
    <nameField>
        <displayFormat>VM-{00000}</displayFormat>
        <label>Vehicle Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle_Master__c/fields/Body_Type__c.field-meta.xml
<CustomField>
    <fullName>Body_Type__c</fullName>
    <label>Body Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open Body</fullName>
            </value>
            <value>
                <fullName>Closed (Container)</fullName>
            </value>
            <value>
                <fullName>MS Tanker</fullName>
            </value>
            <value>
                <fullName>SS Tanker</fullName>
            </value>
            <value>
                <fullName>Milk Tanker</fullName>
            </value>
            <value>
                <fullName>Bulker</fullName>
            </value>
            <value>
                <fullName>Open Flat Body</fullName>
            </value>
            <value>
                <fullName>Refrigerated Container</fullName>
            </value>
            <value>
                <fullName>Tipper</fullName>
            </value>
            <value>
                <fullName>Route Bus</fullName>
            </value>
            <value>
                <fullName>Staff Bus</fullName>
            </value>
            <value>
                <fullName>Semi Luxury Bus</fullName>
            </value>
            <value>
                <fullName>Luxury Bus</fullName>
            </value>
            <value>
                <fullName>AC Sleeper</fullName>
            </value>
            <value>
                <fullName>Non-AC Sleeper</fullName>
            </value>
            <value>
                <fullName>Trailer</fullName>
            </value>
            <value>
                <fullName>Tip-Trailer</fullName>
            </value>
            <value>
                <fullName>BHL</fullName>
            </value>
            <value>
                <fullName>Excavator</fullName>
            </value>
            <value>
                <fullName>Compactor</fullName>
            </value>
            <value>
                <fullName>Generator</fullName>
            </value>
            <value>
                <fullName>Loader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/Fuel_Type__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Type__c</fullName>
    <label>Fuel Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Petrol</fullName>
            </value>
            <value>
                <fullName>Diesel</fullName>
            </value>
            <value>
                <fullName>Hybrid</fullName>
            </value>
            <value>
                <fullName>CNG</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/LOB__c.field-meta.xml
<CustomField>
    <fullName>LOB__c</fullName>
    <label>LOB</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CV/CE</fullName>
            </value>
            <value>
                <fullName>BL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tata Motors Ltd</fullName>
            </value>
            <value>
                <fullName>Ashok Leyland</fullName>
            </value>
            <value>
                <fullName>Mahindra &amp; Mahindra Ltd</fullName>
            </value>
            <value>
                <fullName>Eicher Ltd</fullName>
            </value>
            <value>
                <fullName>Body Builder</fullName>
            </value>
            <value>
                <fullName>JCB Ltd.</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wheels</fullName>
                <default>true</default>
                <label>Wheels</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/Sub_Product__c.field-meta.xml
<CustomField>
    <fullName>Sub_Product__c</fullName>
    <label>Sub-Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>LOB</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle_Master__c/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Chassis</fullName>
            </value>
            <value>
                <fullName>Cab Chassis</fullName>
            </value>
            <value>
                <fullName>Fully Built</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/LOB.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BL</fullName>
    </customValue>
    <customValue>
        <fullName>CE</fullName>
    </customValue>
    <customValue>
        <fullName>CV</fullName>
    </customValue>
    <customValue>
        <fullName>CV/CE</fullName>
        <isActive>false</isActive>
        <label>CV/CE</label>
    </customValue>
    <masterLabel>LOB</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_VehicleSelectionController.cls
/**
* @File Name          : UB_VehicleSelectionController.cls
* @Description        : This controller will help to create dynamic picklist values for different vehicle fields.
* @Author             : Mohit
* @Test CLass         : UB_VehicleSelectionController
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         24-04-2024               Mohit                 Initial Version
*/
public class UB_VehicleSelectionController {
    @AuraEnabled
    public static List<PicklistSet> fetchPicklistValues(String vehicleDetails, Id productId){
        VehicleDetails customWrapper = (VehicleDetails) JSON.deserialize(vehicleDetails, VehicleDetails.class);
        system.debug('customWrapper@@'+customWrapper);
        system.debug('productId@@'+productId);
        List<PicklistSet> picklistValues = new List<PicklistSet>();
        Set<String> picklistValueSet = new Set<String>();
        List<Product__c> productList = new UB_ProductsSelector().fetchProductMasterWithId(new Set<Id>{productId});
        system.debug('productList@@'+productList);
        List<Vehicle_Master__c> vehicleList = new List<Vehicle_Master__c>();
        String query = ' SELECT Id, Name, Make__c, Model__c, Vehicle_Type__c, Fuel_Type__c, Body_Type__c ';
        query       += ' FROM Vehicle_Master__c WHERE Active__c = true ';
        if(!productList.isEmpty() && productList.size() > 0){
            if(productList[0].Product__c != null){
                query += ' AND Sub_Product__c = \''+productList[0].Product__r.LOB__c+'\' ';
            }
        }
        if(String.isNotBlank(customWrapper.make) && String.isNotBlank(customWrapper.model)){
			query += ' AND Make__c = \''+customWrapper.make+'\' ';
            query += ' AND Model__c = \''+customWrapper.model+'\' ';
        }else if(String.isNotBlank(customWrapper.make)){
            query += ' AND Make__c = \''+customWrapper.make+'\' ';
        }
        system.debug('query'+query);
        vehicleList = Database.query(query);
        system.debug('vehicleList'+vehicleList);
        system.debug('customWrapper'+customWrapper);
        if(!vehicleList.isEmpty() && vehicleList.size() > 0 && customWrapper != null){
            system.debug('make'+customWrapper.make);
            for(Vehicle_Master__c obj : vehicleList){
                if(String.isBlank(customWrapper.make)){
                    picklistValueSet.add(obj.Make__c);
                }else if(String.isBlank(customWrapper.model)){
                    picklistValueSet.add(obj.Model__c);
                }else if(String.isBlank(customWrapper.type)){
                    if(obj.Vehicle_Type__c != null && String.isNotBlank(obj.Vehicle_Type__c) && obj.Vehicle_Type__c.contains(';')){
                        for(String str : obj.Vehicle_Type__c.split(';')){
                            picklistValueSet.add(str);
                        }
                    }else{
                        picklistValueSet.add(obj.Vehicle_Type__c);
                    }
                }else if(String.isBlank(customWrapper.fuelType)){
                    if(obj.Fuel_Type__c != null && String.isNotBlank(obj.Fuel_Type__c) && obj.Fuel_Type__c.contains(';')){
                        for(String str : obj.Fuel_Type__c.split(';')){
                            picklistValueSet.add(str);
                        }
                    }else{
                        picklistValueSet.add(obj.Fuel_Type__c);
                    }
                }else if(String.isBlank(customWrapper.bodyType)){
                    if(obj.Body_Type__c != null && String.isNotBlank(obj.Body_Type__c) && obj.Body_Type__c.contains(';')){
                        for(String str : obj.Body_Type__c.split(';')){
                            picklistValueSet.add(str);
                        }
                    }else{
                        picklistValueSet.add(obj.Body_Type__c);
                    }
                }
            }
            system.debug('picklistValueSet'+picklistValueSet);
            for(String str : picklistValueSet){
                picklistValues.add(new PicklistSet(str, str));
            }
            return picklistValues;
        }
        return picklistValues;
    }
    
    @AuraEnabled
    public static String fetchVehicleMasterId(String vehicleModel){
        List<Vehicle_Master__c> vehicleMasterList = new List<Vehicle_Master__c>();
        system.debug('vehicleModel > ' + vehicleModel);
        if(String.isNotBlank(vehicleModel)){
            vehicleMasterList = new UB_VehicleMasterSelector().selectByModel(new Set<String>{vehicleModel});
            system.debug('vehicleMasterList > ' + vehicleMasterList);
            if(!vehicleMasterList.isEmpty() && vehicleMasterList.size() > 0){
                return vehicleMasterList[0].Id;
            }
            return null;
        }
        return null;
    }
    
    @AuraEnabled
    public static VehicleDetails fetchVehicleProductInfo(String vehicleId){
        List<Vehicle__c> vehicleList = new UB_VehiclesSelector().selectByIdsWithProductInfo(new Set<Id>{vehicleId});
        if(!vehicleList.isEmpty() && vehicleList.size() > 0){
            VehicleDetails obj = new VehicleDetails();
            if(String.isBlank(obj.make)){
                obj.makeValues = fetchPicklistValues(JSON.serialize(obj), vehicleList[0].Product__c);
                obj.make = String.isNotBlank(vehicleList[0].Make__c) ? vehicleList[0].Make__c : '';
            }
            if(String.isBlank(obj.model)){
                obj.modelValues = fetchPicklistValues(JSON.serialize(obj), vehicleList[0].Product__c);
                obj.model = String.isNotBlank(vehicleList[0].Model__c) ? vehicleList[0].Model__c : '';
            }
            if(String.isBlank(obj.type)){
                obj.vehicleTypeValues = fetchPicklistValues(JSON.serialize(obj), vehicleList[0].Product__c);
                obj.type = String.isNotBlank(vehicleList[0].Vehicle_Type__c) ? vehicleList[0].Vehicle_Type__c : '';
            }
            if(String.isBlank(obj.fuelType)){
                obj.fuelTypeValues = fetchPicklistValues(JSON.serialize(obj), vehicleList[0].Product__c);
                obj.fuelType = String.isNotBlank(vehicleList[0].Fuel_Type__c) ? vehicleList[0].Fuel_Type__c : '';
            }
            if(String.isBlank(obj.bodyType)){
                obj.bodyTypeValues = fetchPicklistValues(JSON.serialize(obj), vehicleList[0].Product__c);
                obj.bodyType = String.isNotBlank(vehicleList[0].Body_Type__c) ? vehicleList[0].Body_Type__c : '';
            }
            obj.productId       = vehicleList[0].Product__c != null ? vehicleList[0].Product__c : null;
            obj.productCategory = String.isNotBlank(vehicleList[0].Product__r.Product_Category__c) ? vehicleList[0].Product__r.Product_Category__c : '';
            system.debug('VehicleObj'+obj);
            return obj;
        }
        return null;
    }
    
	public class PicklistSet {
        @AuraEnabled public String label { get; set; }
        @AuraEnabled public String value { get; set; }

        public PicklistSet(String label, String value){
            this.label = label;
            this.value = value;
        }
    }

    public class VehicleDetails {
        @AuraEnabled public String make { get; set; }
        @AuraEnabled public String model { get; set; }
        @AuraEnabled public String type { get; set; }
        @AuraEnabled public String cost { get; set; }
        @AuraEnabled public String tenure { get; set; }
        @AuraEnabled public String roi { get; set; }
        @AuraEnabled public String numberOfVehicles { get; set; }
        @AuraEnabled public String fuelType { get; set; }
        @AuraEnabled public String bodyType { get; set; }
        @AuraEnabled public String productId { get; set; }
        @AuraEnabled public String productCategory { get; set; }
        @AuraEnabled public List<PicklistSet> makeValues { get; set; }
        @AuraEnabled public List<PicklistSet> modelValues { get; set; }
        @AuraEnabled public List<PicklistSet> vehicleTypeValues { get; set; }
        @AuraEnabled public List<PicklistSet> fuelTypeValues { get; set; }
        @AuraEnabled public List<PicklistSet> bodyTypeValues { get; set; }
    }
}