force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/BL_Reject_Type__c.field-meta.xml
<CustomField>
    <fullName>BL_Reject_Type__c</fullName>
    <label>Reject Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hard</fullName>
            </value>
            <value>
                <fullName>Soft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/BL_Soft_Reject_Date__c.field-meta.xml
<CustomField>
    <fullName>BL_Soft_Reject_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Soft Reject Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/BL_Validity_End_Date__c.field-meta.xml
<CustomField>
    <fullName>BL_Validity_End_Date__c</fullName>
    <label>Validity End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Loan_Application_Status__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Status__c</fullName>
    <label>Loan Application Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Disbursed</fullName>
            </value>
            <value>
                <fullName>Revoke</fullName>
            </value>
            <value>
                <fullName>Query Raised</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Reject_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Reason__c</fullName>
    <label>Reject Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Derogatory CIBIL</fullName>
            </value>
            <value>
                <fullName>Policy Norms not met</fullName>
            </value>
            <value>
                <fullName>Customer not Interested</fullName>
            </value>
            <value>
                <fullName>RCU Negative</fullName>
            </value>
            <value>
                <fullName>FI Negative by Agency</fullName>
            </value>
            <value>
                <fullName>Any Other Reasons</fullName>
            </value>
            <value>
                <fullName>System Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Loan_Application__c/fields/Reject_Sub_Reason__c.field-meta.xml
<CustomField>
    <fullName>Reject_Sub_Reason__c</fullName>
    <label>Reject Sub Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Reject_Reason__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Recent OD and High DPD in the current running accounts.</fullName>
            </value>
            <value>
                <fullName>SUB / SMA / High DPD / account in the closed loan of CV / CE</fullName>
            </value>
            <value>
                <fullName>Fleet Expansion Not As Per Norms</fullName>
            </value>
            <value>
                <fullName>FFR Norms not met</fullName>
            </value>
            <value>
                <fullName>Experience norms not met</fullName>
            </value>
            <value>
                <fullName>Insufficient Credit History</fullName>
            </value>
            <value>
                <fullName>Credit PD Negative</fullName>
            </value>
            <value>
                <fullName>Poor Repayment</fullName>
            </value>
            <value>
                <fullName>Out of GEO Limit</fullName>
            </value>
            <value>
                <fullName>Age norms not met</fullName>
            </value>
            <value>
                <fullName>Financial norms not met (Captive Profile)</fullName>
            </value>
            <value>
                <fullName>Asking for lower Roi</fullName>
            </value>
            <value>
                <fullName>Asking for Higher funding - Ltv / Loan amount</fullName>
            </value>
            <value>
                <fullName>Client withdrawal due to change in the plan</fullName>
            </value>
            <value>
                <fullName>Document does not complete by client</fullName>
            </value>
            <value>
                <fullName>Profile Decline</fullName>
            </value>
            <value>
                <fullName>Document Decline</fullName>
            </value>
            <value>
                <fullName>FI Negative</fullName>
            </value>
            <value>
                <fullName>Any other reasons</fullName>
            </value>
            <value>
                <fullName>Customer denied the consent</fullName>
            </value>
            <value>
                <fullName>Duplicate Record</fullName>
            </value>
            <value>
                <fullName>Sanction Letter Expired</fullName>
            </value>
            <value>
                <fullName>CIBIL score below acceptable range</fullName>
            </value>
            <value>
                <fullName>Complete Documents not provided by the client</fullName>
            </value>
            <value>
                <fullName>Duplicate record rejected within 60 days</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BL_RejectionBatch.cls
/**
* @File Name          : BL_RejectionBatch
* @Description        : Batch for the rejection hard
* @Author             : Lakshya Verma
* 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0                           Initial Version
*/
global class BL_RejectionBatch implements Database.Batchable<sObject>,Database.Stateful {
	
    global Database.QueryLocator  start(Database.BatchableContext bc) {
        String qry = 'SELECT Id, BL_Reject_Type__c, BL_Soft_Reject_Date__c, BL_Validity_End_Date__c, ';
        qry += ' Reject_Reason__c, Reject_Sub_Reason__c, Loan_Application_Status__c , Comment__c ';
        qry +=   ' FROM Loan_Application__c WHERE BL_Validity_End_Date__c = today AND BL_Reject_Type__c = \'' + 'Soft' + '\'';
        qry +=   '  AND Loan_Application_Status__c  = \'' + 'Rejected' + '\'';
        return Database.getQueryLocator(qry);
    }

    global void execute(Database.BatchableContext bc, List<Loan_Application__c> rejectionScope) {
        system.debug('rejectionScope-> ' + rejectionScope);
        List<Loan_Application__c> hardRejectionList = new List<Loan_Application__c>();
        for(Loan_Application__c loanApp : rejectionScope){
            loanApp.BL_Reject_Type__c = BL_ConstantsUtil.REJECTION_TYPE;
            hardRejectionList.add(loanApp);
        }
        if(!hardRejectionList.isEmpty()){
            system.debug('hardRejectionList-> ' + hardRejectionList);
            UPDATE hardRejectionList;
        }
    }

    global void finish(Database.BatchableContext bc) {
        // execute any post-processing operations - send emails, notify clients,
        // give a call to another batch class
        // Can give to another batch class
        // Can give callout request
        system.debug('batch job id = '+bc.getJobId());
    }
	
}