force-app/main/default/objects/Financial_Assessment__c/Financial_Assessment__c.object-meta.xml
<CustomObject>
    <label>Financial Assessment</label>
    <nameField>
        <displayFormat>FA-{0000000}</displayFormat>
        <label>financial assessment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Assessment</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Financial_Assessment__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Financial Assessment</relationshipLabel>
    <relationshipName>Financial_Assessment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Assessment__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Financial Assessment</relationshipLabel>
    <relationshipName>Financial_Assessment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Financial_Assessment__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Financial Assessment</relationshipLabel>
    <relationshipName>Financial_Assessment</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Loan_Application__c/Loan_Application__c.object-meta.xml
<CustomObject>
    <label>Loan Application</label>
    <nameField>
        <displayFormat>LA-{0000}</displayFormat>
        <label>Loan Application No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Loan_Application__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/BL_Applied_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>BL_Applied_Loan_Amount__c</fullName>
    <label>Applied Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Balance_Transfer_Applicable__c.field-meta.xml
<CustomField>
    <fullName>BL_Balance_Transfer_Applicable__c</fullName>
    <label>Balance Transfer Applicable</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Loan_Tenure_months__c.field-meta.xml
<CustomField>
    <fullName>BL_Loan_Tenure_months__c</fullName>
    <label>Loan Tenure(in months)</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_Rate_of_Interest__c.field-meta.xml
<CustomField>
    <fullName>BL_Rate_of_Interest__c</fullName>
    <label>Rate of Interest(%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/BL_RCU_Required__c.field-meta.xml
<CustomField>
    <fullName>BL_RCU_Required__c</fullName>
    <formula>Product__r.BL_RCU_Required__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>RCU Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Product_Master__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Schemes__c.field-meta.xml
<CustomField>
    <fullName>Product_Schemes__c</fullName>
    <formula>TEXT( Product__r.Product_Schemes__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Schemes</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <formula>TEXT( Product__r.Product_Sub_Category__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Sub Category</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product__c/fields/Sanction_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Loan_Amount__c</fullName>
    <label>Sanction Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Master__c/Product_Master__c.object-meta.xml
<CustomObject>
    <label>Product Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Master__c/fields/BL_RCU_Required__c.field-meta.xml
<CustomField>
    <fullName>BL_RCU_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RCU Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CV-New</fullName>
            </value>
            <value>
                <fullName>CE-New</fullName>
            </value>
            <value>
                <fullName>CV-Used</fullName>
            </value>
            <value>
                <fullName>CE-Used</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Schemes__c.field-meta.xml
<CustomField>
    <fullName>Product_Schemes__c</fullName>
    <label>Product Schemes</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTU &amp; FTB</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Strategic</fullName>
            </value>
            <value>
                <fullName>Institutional Strategic</fullName>
            </value>
            <value>
                <fullName>Captive Retail</fullName>
            </value>
            <value>
                <fullName>Captive Strategic</fullName>
            </value>
            <value>
                <fullName>CPM</fullName>
            </value>
            <value>
                <fullName>GPM</fullName>
            </value>
            <value>
                <fullName>GPR</fullName>
            </value>
            <value>
                <fullName>Banking Surrogate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Master__c/fields/Product_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Sub_Category__c</fullName>
    <label>Product Sub Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transporter</fullName>
            </value>
            <value>
                <fullName>Bus Operator</fullName>
            </value>
            <value>
                <fullName>Captive</fullName>
            </value>
            <value>
                <fullName>Contractor</fullName>
            </value>
            <value>
                <fullName>Hirer</fullName>
            </value>
            <value>
                <fullName>Mine Owner</fullName>
            </value>
            <value>
                <fullName>Business Loan</fullName>
            </value>
            <value>
                <fullName>Business Loan Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Loan_Application__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Commercial Vehicle Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Construction Equipment Loan</fullName>
    </customValue>
    <customValue>
        <fullName>Tractor Loan</fullName>
        <isActive>false</isActive>
        <label>Tractor Loan</label>
    </customValue>
    <customValue>
        <fullName>Three Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Three Wheeler Loan</label>
    </customValue>
    <customValue>
        <fullName>Car Loan</fullName>
        <isActive>false</isActive>
        <label>Car Loan</label>
    </customValue>
    <customValue>
        <fullName>Office Equipment</fullName>
        <isActive>false</isActive>
        <label>Office Equipment</label>
    </customValue>
    <customValue>
        <fullName>Medical Equipment</fullName>
        <isActive>false</isActive>
        <label>Medical Equipment</label>
    </customValue>
    <customValue>
        <fullName>Two Wheeler Loan</fullName>
        <isActive>false</isActive>
        <label>Two Wheeler Loan</label>
    </customValue>
    <masterLabel>Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UB_ProductsSelector.cls
/**
* @File Name          : UB_ProductsSelector.cls
* @Description        : This class used to fetch/query Product records based on conditions.
* @Author             : Mohit
* @Test CLass         : 
*==============================================================================
* Ver         Date                     Author                 Modification
*==============================================================================
* 1.0         26-03-2024               Mohit                 Initial Version
*/
public class UB_ProductsSelector extends fflib_SObjectSelector {
    
    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
           //Product__c.Product_Name__c,
           //Product__c.Product_Code__c,
            Product__c.Name,
            Product__c.Product__c,
            Product__c.Loan_Application__c,
            Product__c.Product_Category__c,
            Product__c.Product_Schemes__c,
            Product__c.Product_Sub_Category__c, 
            Product__c.BL_RCU_Required__c,
            Product__c.BL_Balance_Transfer_Applicable__c,
            Product__c.Sanction_Loan_Amount__c,
            Product__c.BL_Rate_of_Interest__c,
            Product__c.BL_Loan_Tenure_months__c,
            Product__c.BL_Applied_Loan_Amount__c
        };
    }
    
    public Schema.SObjectType getSObjectType(){
        return Product__c.sObjectType;
    }
    
    public List<Product__c> selectById(Set<Id> recordIds){
        //return (List<Product__c>) selectSObjectsById(recordIds);
        fflib_QueryFactory query = newQueryFactory();
        fflib_SObjectSelector vehiclesSelector = new UB_VehiclesSelector();
        vehiclesSelector.addQueryFactorySubselect(query, 'Vehicles__r');
        fflib_SObjectSelector productMastersSelector = new UB_ProductMastersSelector();
        productMastersSelector.configureQueryFactoryFields(query, 'Product__r');
        fflib_SObjectSelector financialAssessmentsSelector = new UB_FinancialAssessmentsSelector();
        financialAssessmentsSelector.addQueryFactorySubselect(query, 'Financial_Assessment__r');

        query.setCondition('Id IN : recordIds');
        return (List<Product__c>) Database.query(query.toSOQL());
    }
    
    public List<Product__c> fetchProductMasterWithId(Set<Id> recordIds){
        fflib_QueryFactory query = newQueryFactory();
        fflib_SObjectSelector productMastersSelector = new UB_ProductMastersSelector();
        productMastersSelector.configureQueryFactoryFields(query, 'Product__r');
        query.setCondition('Id IN : recordIds');
        return (List<Product__c>) Database.query(query.toSOQL());
    }
    
    public List<Product__c> selectByLoanApplicationIds(Set<Id> loanApplicationIds){
        fflib_QueryFactory query = newQueryFactory();
        query.setCondition('Loan_Application__c IN : loanApplicationIds');
        return (List<Product__c>) Database.query(query.toSOQL());
    }
}